import sqlite3, re

DB = 'db/alchemy_timeline.db'

def wc(h):
    return len(re.sub('<[^>]+>', ' ', h or '').split())

conn = sqlite3.connect(DB)
c = conn.cursor()

def add_text(slug, title, text_type, lang, yr_start, yr_end, analysis):
    c.execute('SELECT id FROM texts WHERE slug=?', (slug,))
    if c.fetchone():
        print(f'  [EXISTS] {slug}'); return
    c.execute('''INSERT INTO texts (slug, title, text_type, original_language,
                 composition_year_start, composition_year_end, analysis_html,
                 source_method, review_status, confidence)
                 VALUES (?,?,?,?,?,?,?,?,?,?)''',
              (slug, title, text_type, lang, yr_start, yr_end, analysis,
               'SCHOLARSHIP_BASED', 'DRAFT', 'MEDIUM'))
    conn.commit()
    print(f'  [NEW] {slug}: {wc(analysis)} words')

# --- ALCHEMIA (LIBAVIUS) ---
add_text('alchemia-libavius', 'Alchemia (Libavius)', 'PRIMARY_SOURCE', 'Latin', 1597, 1597, '''
<p>Andreas Libavius's <i>Alchemia</i> (Frankfurt, 1597; expanded edition 1606) is one of the most significant publications in the history of early modern chymistry, widely described as the first systematic chemical textbook. Organized in two major parts — the <i>Encheria</i> (on chemical operations and apparatus) and the <i>Chymia</i> (on the theoretical and practical substance of chemical knowledge) — the work compiled, organized, and systematized the accumulated knowledge of sixteenth-century chymical practice in a pedagogically accessible format that no previous publication had achieved. Its combination of detailed procedural description, systematic apparatus catalogs, and theoretical discussion set a standard for chemical writing that influenced the genre throughout the seventeenth century.</p>

<h2>Structure and Content</h2>
<p>The <i>Encheria</i> section of the <i>Alchemia</i> catalogs chemical operations systematically: distillation (of water, wine spirits, oils, and minerals), sublimation, calcination, solution and crystallization, amalgamation, and a range of specific preparative procedures for pharmaceutical and metallurgical products. Each operation is described in terms of the appropriate apparatus, the specific conditions required, and the expected products, providing enough detail for practitioners to attempt replication. The famous engravings of the ideal chemical laboratory — included in the text as illustrations of the appropriate physical setting for chemical work — depict a purpose-designed building with specialized rooms for different operations and a comprehensive set of standardized apparatus, constituting the most detailed vision of a purpose-built chemical facility produced in the period.</p>
<p>The <i>Chymia</i> section treats the theoretical dimensions of chemical knowledge: the nature and properties of the pharmaceutical preparations, the principles of metallic transformation, and the relationship between chemical knowledge and other branches of natural philosophy. Libavius's treatment of transmutation was guarded: he acknowledged the theoretical possibility but was skeptical of claims to have achieved it, situating himself among those who viewed alchemical gold-making as theoretically possible but practically unproven. This cautious position distinguished him from both enthusiastic transmutational alchemists and thoroughgoing skeptics, reflecting a nuanced engagement with the evidence rather than a simple commitment to either tradition.</p>

<h2>The Ideal Chemical Laboratory</h2>
<p>The most celebrated feature of the <i>Alchemia</i> for historians of science and architecture is its description and illustration of an ideal chemical laboratory. Libavius proposed a purpose-built structure — a "chymist's palace" — divided into specialized spaces: a preparation room, a distillation room, a sublimation furnace room, a room for dry operations (calcination, fusion), a repository for finished products, and a library. Each space was equipped with specific apparatus described in detail, and the building as a whole was designed to enable systematic, organized chemical work rather than the ad hoc improvisation that characterized most contemporary workshops.</p>
<p>This ideal laboratory has been analyzed by historians of science and architectural historians as an early articulation of the concept of the purpose-built scientific laboratory. Bruce Moran and others have situated it within the broader development of court laboratories, pharmaceutical workshops, and university chemical teaching facilities in the late sixteenth and early seventeenth centuries, showing how Libavius's ideal informed the practical design of actual chemical spaces as rulers and universities began to provide physical infrastructure for systematic chemical investigation. The <i>Alchemia</i>'s ideal laboratory thus contributed to the institutionalization of chemistry as a discipline with its own appropriate physical setting, distinct from the workshop of the craftsperson or the apothecary's shop.</p>

<h2>Historiographical Significance</h2>
<p>Owen Hannaway's analysis of the <i>Alchemia</i> in <i>The Chemists and the Word</i> (1975) situated it as one of two competing models for the organization of chemical knowledge in the early seventeenth century — the other being Oswald Croll's emblematic and theosophical <i>Basilica Chymica</i>. Hannaway argued that the <i>Alchemia</i>'s emphasis on public communicability, systematic organization, and institutional pedagogy represented a "rationalist" alternative to the secret, initiated, and emblematically organized knowledge of the Crollian tradition. While subsequent scholars have qualified this contrast, identifying more complexity in both positions than Hannaway's binary allows, the fundamental tension he identified — between open, pedagogically organized and secret, initiated chemical knowledge — remains a useful frame for understanding the intellectual debates of early seventeenth-century chymistry.</p>
<p>Lawrence Principe and William Newman's more recent scholarship has situated the <i>Alchemia</i> within the longer trajectory of chymical development from the Paracelsian reform through the institutionalization of chemistry in European universities and academies. On this account, Libavius's contribution was not simply to rationalize alchemy but to articulate a vision of chymistry as a legitimate academic discipline with its own pedagogy, curriculum, and institutional requirements — a vision that took more than a century to be fully realized but that proved influential in shaping how chemistry was understood, taught, and organized in subsequent decades.</p>
''')

# --- BASILICA CHYMICA ---
add_text('basilica-chymica', 'Basilica Chymica (Croll)', 'PRIMARY_SOURCE', 'Latin', 1609, 1609, '''
<p>Oswald Croll's <i>Basilica Chymica</i> (Frankfurt, 1609), published posthumously, is among the most important Paracelsian pharmaceutical manuals of the seventeenth century and one of the most widely read and reprinted chemical books of the period. The work combines a substantial theoretical preface (the <i>Admonitory Preface</i>) with detailed pharmaceutical recipes organized by disease category, providing both a philosophical rationale for Paracelsian chemical medicine and a practical handbook for its implementation. Its wide dissemination across Protestant and Catholic Europe reflects both the quality of its pharmaceutical content and the growing interest in chemical medicine among European physicians and apothecaries in the early seventeenth century.</p>

<h2>The Admonitory Preface</h2>
<p>The <i>Admonitory Preface</i> that opens the <i>Basilica Chymica</i> is a substantial theological and philosophical treatise in its own right, constituting Croll's most systematic statement of Paracelsian natural philosophy. Drawing on [LINK:paracelsus]'s doctrines of the tria prima (salt, sulfur, mercury), the archeus (vital formative principle), and the macrocosm-microcosm correspondence, Croll argued for the philosophical superiority of chemical medicine over Galenic therapeutics on the grounds that it was grounded in genuine knowledge of the creative principles underlying natural reality rather than in mere empirical observation or textual tradition.</p>
<p>Central to the <i>Preface</i>'s argument is the doctrine of signatures — the idea that the external form of a natural substance indicates its therapeutic properties through analogical correspondence with the properties of the organs or conditions it treats. Croll elaborated this doctrine within a Neoplatonist framework in which the visible world was understood as a continuous text written by God for the physician to read: the external characteristics of plants, minerals, and other natural substances expressed their inner medicinal virtues in a language that the trained and devout physician could interpret. This approach to medical knowledge as a form of theological hermeneutics — reading the book of nature as one reads scripture — distinguished Croll's program from both Galenic empiricism and the emerging mechanist natural philosophy.</p>

<h2>Pharmaceutical Content</h2>
<p>The pharmaceutical section of the <i>Basilica Chymica</i> provides detailed instructions for the preparation of a wide range of chemical remedies, organized by the type of preparation and the disease category they address. The preparations include antimonial compounds (tartar emetic, antimonial wine, crocus of antimony), mercurial preparations, distilled oils and tinctures from medicinal plants, mineral salts, and a range of specific preparations derived from the spagyric method. Many of these preparations can be identified with specific chemical compounds whose pharmacological properties are analyzable by modern chemistry, and laboratory historians including Lawrence Principe have confirmed that many of Croll's procedures produce real chemical products with genuine pharmaceutical activity.</p>
<p>The antimonial preparations have received particular attention from historians because antimony was at the center of one of the most significant medical controversies of the seventeenth century: the French antimony debate. The Paris Faculty of Medicine banned antimony preparations in 1615, partly in response to the spread of Crollian prescriptions among Paracelsian practitioners, and the subsequent controversy — which lasted until 1666 — engaged the major intellectual and institutional figures of French medicine. Principe's detailed account of this controversy situates the <i>Basilica Chymica</i> as one of the key texts that defined the terms of the debate, disseminating Paracelsian pharmaceutical prescriptions while simultaneously providing the theoretical arguments that defenders of antimony would draw on in subsequent decades.</p>

<h2>Reception and Influence</h2>
<p>The <i>Basilica Chymica</i> was reprinted numerous times in Latin and translated into German, French, and English, achieving remarkably wide dissemination for a technical pharmaceutical work. Its influence extended across the ideological spectrum of seventeenth-century natural philosophy: it was used by strict Paracelsians who accepted its theoretical framework, by eclectic physicians who adopted its pharmaceutical prescriptions without the Hermetic preface, and — through [LINK:george-starkey]'s pharmaceutical work analyzed by William Newman — contributed to the development of English chymistry in the mid-seventeenth century. This wide reception illustrates the practical separability of pharmaceutical prescriptions from their theoretical context: practitioners could use Croll's recipes while rejecting or ignoring his Hermetic philosophy.</p>
<p>Owen Hannaway's comparative analysis of Libavius and Croll in <i>The Chemists and the Word</i> (1975) identified the <i>Basilica Chymica</i> as the representative text of an esoteric and theosophical model of chemical knowledge, in which the secrets of nature were accessible only to the initiated and communicable only through emblematic and allegorical forms. While subsequent scholarship has refined this characterization — noting that Croll's pharmaceutical content was often more practically accessible than the <i>Preface</i>'s language implied — the fundamental contrast between open, institutional, and pedagogically organized chemistry (represented by Libavius) and secret, initiated, emblematically communicated chemistry (represented by Croll) captures a genuine tension within early modern chymistry that shaped the social and intellectual organization of the discipline for decades.</p>
''')

# --- COURS DE CHYMIE (LEMERY) ---
add_text('cours-de-chymie', 'Cours de Chymie (Lemery)', 'PRIMARY_SOURCE', 'French', 1675, 1675, '''
<p>Nicolas Lemery's <i>Cours de Chymie</i> (Course of Chemistry, Paris, 1675) became the most widely used chemical textbook of the late seventeenth and early eighteenth centuries, reaching twelve French editions before its author's death and translations into English, German, Latin, Italian, Spanish, and Dutch. The work's success reflected both the clarity and accessibility of Lemery's exposition — which explicitly eschewed the obscure allegorical language of earlier chemical texts in favor of plain descriptions suited to practitioners without extensive philosophical training — and the growing demand for reliable chemical knowledge among physicians, apothecaries, and learned amateurs in the decades after the founding of the major European scientific academies.</p>

<h2>Structure and Theoretical Framework</h2>
<p>The <i>Cours de Chymie</i> is organized as a pharmaceutical chemistry reference, proceeding through the preparation of animal, vegetable, and mineral medicines and providing clear, accessible descriptions of each operation and product. This pharmaceutical organization reflects the origins of French chymistry in the Paracelsian reform of medicine and the ongoing centrality of pharmaceutical applications to the practical work of chemical practitioners. The theoretical framework Lemery employed drew on Cartesian corpuscular philosophy: chemical reactions were explained in terms of the mechanical interactions of material particles of specific shapes and sizes, with acids described as sharp-pointed particles, alkalis as porous particles with channels accommodating acid spikes, and effervescence as the mechanical struggle between incompatible particle shapes.</p>
<p>This corpuscular-mechanical account, while crude by later standards, represented a significant departure from both the Aristotelian elemental framework and the Paracelsian tria prima that had dominated earlier chemical theory. By replacing qualitative principles (combustibility, fusibility, fixity) with mechanical properties (particle shape, size, arrangement), Lemery aligned chemical explanation with the Cartesian natural philosophy that was becoming the dominant intellectual framework for educated Europeans in the late seventeenth century. The resulting synthesis — Cartesian theory with pharmaceutical practice — was accessible to a readership that included both practitioners who needed practical knowledge and educated readers who wanted a framework compatible with the fashionable mechanical philosophy.</p>

<h2>Pedagogical Achievement</h2>
<p>The <i>Cours de Chymie</i>'s most significant achievement was pedagogical: it provided the first comprehensive, clearly written, and theoretically coherent introduction to practical chemical knowledge that was accessible to readers without deep philosophical or medical training. Earlier chemical textbooks — including [LINK:andreas-libavius]'s <i>Alchemia</i> — had been comprehensive but technically demanding; the <i>Cours</i> made similar practical content available in a form that even educated laypeople could follow. This accessibility was crucial for the expansion of chemical knowledge beyond the circle of professional practitioners to include the broader educated public who were interested in natural philosophy and practical chemistry as cultivated pursuits.</p>
<p>The pedagogical clarity of the <i>Cours</i> reflected Lemery's experience as a teacher: the work originated in the public courses he delivered in Paris in the 1670s, and its organization and language were shaped by the practical requirements of teaching non-specialist students the basics of chemical preparation and theory. This pedagogical origin distinguished the <i>Cours</i> from works written primarily for specialist practitioners and gave it the qualities of clarity and accessibility that made it so widely read. The subsequent genre of popular chemistry writing, from the seventeenth century through to the present, drew on the model that Lemery established.</p>

<h2>Legacy and the Chemical Revolution</h2>
<p>The <i>Cours de Chymie</i> remained in print and use well into the period of the Chemical Revolution, with revised editions appearing as late as 1756. This longevity reflects both the practical utility of its pharmaceutical content — which retained its value independent of the specific theoretical framework — and the conservatism of chemical education, which continued to rely on established textbooks even as theoretical innovations were transforming research-level chemistry. Antoine Lavoisier studied chemistry partly through Lemery's textbook and its successors, and the practical pharmaceutical knowledge it transmitted formed part of the background from which the Chemical Revolution emerged.</p>
<p>Historians of chemistry including Lawrence Principe and Jan Golinski have situated the <i>Cours de Chymie</i> within the long transition from Paracelsian to Chemical Revolution chemistry in France, identifying Lemery as a key figure in the institutionalization of chemical knowledge within French scientific culture. His election to the Académie Royale des Sciences in 1699 marked the formal recognition of pharmaceutical chemistry as a legitimate component of French scientific activity, a recognition that had been hard-won through the century of controversy since the Paracelsian reforms. The <i>Cours</i> thus represents the culmination of a process of legitimation and institutionalization that had begun with the Paracelsian controversies of the early seventeenth century and that produced, by the end of the century, a recognizably modern chemical discipline with its own pedagogical standards, institutional homes, and research programs.</p>
''')

print("\n=== Done ===")
conn.close()
