#!/usr/bin/env python3
"""
audit_event_dates.py — find timeline events whose date is implausible for the people
attached to them. Surfaces the mis-dating bug found during enrichment (Bruno events at
1515 though b.1548; al-Razi events at c.630/712 though he lived 864-925).

Method: for each event with a year and associated person(s), check the year against an
acceptable window per person:
  - if the person has itinerary data (newly enriched), use [min_year-50, max_year+50]
    as a lifespan proxy (TIGHT, high-trust);
  - else fall back to the person's coarse era range +/- 80 years (LOOSE).
An event is flagged only if its year fits NONE of its people's windows. Writes
docs/EVENT_DATE_AUDIT.md.
"""
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "db" / "alchemy_timeline.db"

ERA = {"ANTIQUITY": (-800, 300), "LATE_ANTIQUE": (300, 600), "MEDIEVAL": (600, 1450),
       "RENAISSANCE": (1450, 1550), "EARLY_MODERN": (1550, 1700), "ENLIGHTENMENT": (1700, 1850)}


def main():
    c = sqlite3.connect(DB); c.row_factory = sqlite3.Row
    era = {r["slug"]: r["era"] for r in c.execute("select slug,era from persons")}
    name = {r["slug"]: r["name"] for r in c.execute("select slug,name from persons")}
    # itinerary span per person (tight window)
    span = {}
    for r in c.execute("select person_slug, min(year_start) a, max(coalesce(year_end,year_start)) b from person_itinerary group by person_slug"):
        if r["a"] is not None:
            span[r["person_slug"]] = (r["a"], r["b"])
    # event -> persons
    ev_persons = {}
    for r in c.execute("select event_slug, person_slug from person_event_refs"):
        ev_persons.setdefault(r["event_slug"], []).append(r["person_slug"])

    def window(pslug):
        if pslug in span:
            a, b = span[pslug]; return (a - 50, b + 50, "itinerary")
        e = era.get(pslug)
        if e in ERA:
            a, b = ERA[e]; return (a - 80, b + 80, "era")
        return None

    flagged = []
    audited = 0
    for r in c.execute("select slug, date_start_year, date_label from timeline_events where date_start_year is not null"):
        persons = ev_persons.get(r["slug"], [])
        wins = [(p,) + window(p) for p in persons if window(p)]
        if not wins:
            continue
        audited += 1
        y = r["date_start_year"]
        if any(lo <= y <= hi for (_, lo, hi, _src) in wins):
            continue
        # distance to nearest window edge
        nearest = min(wins, key=lambda w: min(abs(y - w[1]), abs(y - w[2])))
        dist = min(abs(y - nearest[1]), abs(y - nearest[2]))
        flagged.append({"event": r["slug"], "year": y, "label": r["date_label"],
                        "persons": persons, "anchor": nearest[0], "anchor_win": (nearest[1], nearest[2]),
                        "basis": nearest[3], "dist": dist})

    flagged.sort(key=lambda f: -f["dist"])
    md = ["# EVENT DATE AUDIT — implausible event dates\n",
          "Auto-generated by `scripts/audit_event_dates.py`. An event is flagged when its "
          "year fits none of its people's plausible windows (tight = enriched itinerary +/-50; "
          "loose = era range +/-80).\n",
          f"- Events with a year AND an attachable person: **{audited}**",
          f"- Flagged as implausible: **{len(flagged)}**",
          f"- High-trust flags (anchored to enriched itinerary data): "
          f"**{sum(1 for f in flagged if f['basis']=='itinerary')}**\n",
          "## Flagged events (worst first)\n",
          "| Event | Event year | Anchor person | Plausible window | Off by | Basis |",
          "|-------|-----:|---------------|------------------|----:|------|"]
    for f in flagged[:60]:
        md.append(f"| {f['event']} | {f['year']} | {name.get(f['anchor'], f['anchor'])} | "
                  f"{f['anchor_win'][0]}–{f['anchor_win'][1]} | {f['dist']}y | {f['basis']} |")
    if len(flagged) > 60:
        md.append(f"\n*(+{len(flagged)-60} more)*")
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "EVENT_DATE_AUDIT.md").write_text("\n".join(md), encoding="utf-8")
    print(f"Audited {audited} datable+attached events; flagged {len(flagged)} implausible "
          f"({sum(1 for f in flagged if f['basis']=='itinerary')} high-trust).")
    print("Worst 8:")
    for f in flagged[:8]:
        print(f"  {f['event'][:42]:<42} year={f['year']:>5}  expect~{f['anchor_win'][0]}-{f['anchor_win'][1]} ({f['anchor']}, off {f['dist']}y)")
    c.close()


if __name__ == "__main__":
    main()
