#!/usr/bin/env python3
"""expand_batch7_remaining_persons.py — Bring all remaining persons to 1200 words."""
import sqlite3, re
DB = 'db/alchemy_timeline.db'

def wc(h): return len(re.sub('<[^>]+>', ' ', h or '').split())

def app(conn, slug, extra):
    c = conn.cursor()
    c.execute('SELECT bio_html FROM persons WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    new = cur + extra
    c.execute('UPDATE persons SET bio_html=? WHERE slug=?', (new, slug))
    print(f'  {slug}: {wc(cur)} -> {wc(new)}')

def setp(conn, slug, bio):
    c = conn.cursor()
    c.execute('SELECT bio_html FROM persons WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    c.execute('UPDATE persons SET bio_html=? WHERE slug=?', (bio, slug))
    print(f'  {slug}: {wc(cur)} -> {wc(bio)}')

# ── Near-minimum top-ups ──────────────────────────────────────────────────────

TRITHEMIUS_FINAL = '<p>The long shadow that the initial misreading of <i>Steganographia</i> cast over Trithemius\'s reputation — he was condemned as a diabolical magician by critics who did not possess the cipher key — illustrates the instability of learned cultural authority in the early sixteenth century. A text that was actually a technical manual for coded communication could be condemned as dangerous magic because its surface presentation was indistinguishable from magic to those without the key. This situation — in which appearance and reality diverge in systematic ways that require special knowledge to navigate — is structurally identical to the situation of alchemical writing that uses symbolic or allegorical language to conceal practical information. Trithemius and the alchemical tradition were engaged in the same game of concealment and revelation, with the same risks of misreading by those who lacked the key.</p>'

RAZI_FINAL = '<p>The recovery of al-Razi as a significant figure in the history of chemistry — rather than merely in the history of Islamic medicine — is part of the broader historiographical reorientation toward non-European contributions to the development of natural knowledge that has characterized scholarship in the history of science since the 1970s. A.I. Sabra\'s work on the transmission of Greek science to Islam and A.S. Ahmed\'s study of Islamic scientific culture provide the broader context for situating al-Razi within the history of the discipline. His specific contributions — the systematic classification of substances, the detailed account of laboratory procedures, the empirical orientation in medicine and chemistry — represent a genuine advance on what was available in Greek and Latin sources before the Arabic translation movement, and their transmission to Latin Europe through the twelfth-century translation movement was genuinely formative for the development of medieval and early modern chemistry.</p>'

CUSA_FINAL = '<p>The connection between Cusanus\'s philosophical legacy and the development of early modern natural philosophy has been analyzed by Pauline Moffitt Watts and others who have traced the influence of <i>docta ignorantia</i> on the figures of the fifteenth and sixteenth centuries who read and engaged with his work. His influence on [LINK:marsilio-ficino] and through Ficino on the broader Neoplatonic tradition of Renaissance Florence was significant; his influence on Bruno was explicit and acknowledged. Less directly, his epistemological framework — in which the recognition of the limits of human knowledge opens the way to indefinite progressive investigation rather than closing it — resonates with the experimental tradition\'s acceptance of provisional and approximate knowledge as the appropriate form of natural philosophical claim. This resonance, whether influence or parallel development, connects Cusanus to the intellectual culture that produced early modern science, including early modern chymistry.</p>'

GROSSETESTE_FINAL = '<p>The long-term significance of Grosseteste\'s contribution to English intellectual culture lies in his establishment of a tradition in which natural philosophical inquiry was valued, institutionally supported, and methodologically sophisticated. This tradition, carried forward through [LINK:roger-bacon], the Merton Calculators, William of Ockham, and eventually the seventeenth-century natural philosophers who founded the Royal Society, created the intellectual climate in which [LINK:robert-boyle]\'s experimental program and [LINK:isaac-newton]\'s synthesis could develop. That this tradition had its roots in a bishop\'s commentaries on Aristotle\'s logic in the 1220s and 1230s is a reminder of how long the genealogies of intellectual change can be, and of how important institutional foundation-laying is for the development of productive traditions of inquiry.</p>'

# ── New bios for stub persons ─────────────────────────────────────────────────

ROSENCREUTZ_BIO = (
    '<p>Christian Rosencreutz is the legendary founder of the Rosicrucian brotherhood, presented'
    ' in the three anonymous pamphlets published 1614–1616 as a fifteenth-century German nobleman'
    ' who traveled to the Arab world and Egypt, acquired occult wisdom, returned to Germany, and'
    ' founded a secret fraternity devoted to healing the sick free of charge and reforming learning'
    ' along Hermetic-alchemical lines. The three texts — <i>Fama Fraternitatis</i> (1614),'
    ' <i>Confessio Fraternitatis</i> (1615), and <i>Chymical Wedding of Christian Rosencreutz</i>'
    ' (1616) — constitute a literary-philosophical intervention into the intellectual culture'
    ' of early seventeenth-century Germany whose exact purpose and authorship remain debated.</p>'
    '<h2>The Rosicrucian Manifestos as Literary Event</h2>'
    '<p>The <i>Fama</i> and <i>Confessio</i> present Rosencreutz and the brotherhood in the mode'
    ' of manifesto and call to action: readers are invited to join the fraternity and participate'
    ' in a universal reform of learning and society along alchemical and Hermetic lines. The'
    ' <i>Chymical Wedding</i> is a different kind of text — an allegorical narrative of a seven-day'
    ' wedding celebration that is simultaneously a description of the alchemical process, a dream'
    ' vision, and a sophisticated literary construction. Johann Valentin Andreae, the probable'
    ' author of the <i>Chymical Wedding</i>, later described it as a <i>ludibrium</i> (jest or play)'
    ' — a designation that has complicated the reception of the Rosicrucian texts ever since, since'
    ' it is unclear whether he meant the term dismissively or as a description of a specific literary'
    ' genre of playful philosophical allegory.</p>'
    '<p>The response to the manifestos was remarkable: hundreds of published texts responded in the'
    ' decade after 1614, either claiming membership in the fraternity, seeking to join, attacking it'
    ' as fraudulent or diabolical, or attempting to analyze its program. Among the respondents were'
    ' [LINK:robert-fludd], who defended the brotherhood as a genuine society of wise men, and René'
    ' Descartes, who reportedly sought out the Rosicrucians during his travels in Germany without'
    ' success. The fact that no one could actually locate the brotherhood — there were no verifiable'
    ' members, no meeting places, no confirmed communications — was itself part of the legend:'
    ' the fraternity was either so perfectly secret as to be invisible, or it was a fiction. Both'
    ' interpretations were available from the beginning.</p>'
    '<p>The alchemical content of the Rosicrucian texts is significant: the reform of learning they'
    ' propose is organized around alchemical principles (purification, transformation, the creation'
    ' of the new from the dissolution of the old), and Rosencreutz\'s life as described in the <i>Fama</i>'
    ' follows the pattern of the alchemical opus — travel, study, the acquisition of hidden knowledge,'
    ' return, and the work of practical and spiritual transformation. The connection to the specific'
    ' laboratory tradition of chymistry that [LINK:william-newman] and [LINK:lawrence-principe]'
    ' have analyzed is indirect; the Rosicrucian texts are more philosophical-religious than'
    ' practically operative. But they represent an important moment in which alchemical symbolism'
    ' was mobilized in support of a broader program of intellectual and spiritual reform, connecting'
    ' the laboratory tradition to the political and religious ambitions of the early seventeenth century.</p>'
    '<p>Frances Yates\'s <i>The Rosicrucian Enlightenment</i> (1972) is the major modern treatment,'
    ' arguing that the Rosicrucian movement represented an attempt to deploy the Hermetic-alchemical'
    ' tradition in support of the Bohemian Protestant cause in the years before the Thirty Years\' War.'
    ' Subsequent scholarship has engaged critically with Yates\'s thesis while accepting her basic'
    ' demonstration that the Rosicrucian texts were products of a specific political and religious'
    ' conjuncture rather than expressions of a timeless esoteric tradition. The figure of Christian'
    ' Rosencreutz himself — fictional, legendary, and infinitely malleable — has continued to attract'
    ' both scholarly analysis and occultist appropriation, a bifurcation that has been part of the'
    ' tradition since its earliest reception.</p>'
)

DEMOCRITUS_BIO = (
    '<p>The historical Democritus of Abdera (c. 460–370 BCE) was the Greek philosopher associated'
    ' with atomic materialism: his theory that all material things are composed of invisible, indivisible'
    ' particles (atoms) moving through void provided the foundation for the atomist tradition that'
    ' Epicurus developed in the Hellenistic period and that Lucretius transmitted to Latin readers in'
    ' <i>De Rerum Natura</i>. Democritus himself wrote extensively on natural philosophy, ethics, and'
    ' a range of other subjects, but his works do not survive except in quotations and doxographic'
    ' summaries. None of the surviving fragmentary evidence attributes alchemical writing to him.</p>'
    '<h2>Pseudo-Democritus and the Origin of Greek Alchemy</h2>'
    '<p>The "Pseudo-Democritus" — a distinct, unknown author writing in Greek probably in the first'
    ' or second century CE in Egypt — is one of the earliest figures in the Greek alchemical tradition.'
    ' His texts, the <i>Physika kai Mystika</i> (Physical and Mystical Matters) and related works,'
    ' constitute some of the earliest surviving Greek alchemical writing. The attribution to Democritus'
    ' was a legitimating strategy: attaching the texts to the famous Greek philosopher of atoms gave'
    ' them the authority of ancient natural philosophical tradition. The actual content of the texts'
    ' — accounts of dyeing metals yellow and white, of preparing tinctures, of the four-element theory'
    ' applied to material transformation — has no genuine connection to the historical Democritus\'s'
    ' atomism, but the strategic attribution was successful and "Democritus" remained an alchemical'
    ' authority in both the Greek and Latin traditions.</p>'
    '<p>The relationship between atomism and alchemy is a genuine historiographical question.'
    ' [LINK:robert-boyle]\'s corpuscular chemistry drew on the revived atomist tradition of Pierre'
    ' Gassendi and Descartes while simultaneously engaging with alchemical laboratory practice:'
    ' in his case, atomism and alchemy were not antagonistic but complementary aspects of a unified'
    ' natural philosophical program. [LINK:isaac-newton]\'s matter theory similarly combined'
    ' corpuscular-atomic accounts of matter with alchemical accounts of active principles.'
    ' [LINK:william-newman] has analyzed this combination in detail, arguing that the revival of'
    ' atomism in the seventeenth century and the development of chymical matter theory were more'
    ' closely intertwined than standard accounts of the Scientific Revolution suggest.</p>'
    '<p>The pseudo-Democritean texts were edited in Marcel Berthelot\'s foundational collection of'
    ' Greek alchemical texts, <i>Collection des anciens alchimistes grecs</i> (1888). More recent'
    ' scholarship by Matteo Martelli has produced a new critical edition and analysis of these texts,'
    ' demonstrating their importance for understanding the origins of the Greek alchemical tradition'
    ' and their relationship to the Hellenistic natural philosophical context in which they were'
    ' produced. The pseudo-Democritus thus belongs simultaneously to the history of ancient Greek'
    ' philosophy, to the history of Hellenistic Egyptian religious and intellectual culture, and'
    ' to the history of alchemy — a convergence that illustrates the multi-stranded origins of'
    ' the Western alchemical tradition.</p>'
)

MEISTER_BIO = (
    '<p>Meister Eckhart (c. 1260–1328) was a Dominican friar, theologian, and preacher who developed'
    ' one of the most sophisticated mystical theologies in medieval Latin Christendom. A member of'
    ' the same order as [LINK:albertus-magnus] and a student of Albert\'s students, Eckhart absorbed'
    ' the Dominican tradition of engaging with Aristotelian natural philosophy while pushing the'
    ' implications of Neoplatonic theology toward a radical account of the soul\'s union with God'
    ' that brought him into conflict with ecclesiastical authority in the final years of his life.</p>'
    '<h2>Mystical Theology and Its Relation to Alchemical Thought</h2>'
    '<p>Eckhart\'s relationship to alchemy was not direct: he was not an alchemical practitioner'
    ' and did not write about laboratory operations. His significance for the history of alchemy'
    ' lies in the domain of intellectual context: the mystical tradition he represented provided'
    ' a framework for understanding transformation — spiritual purification, the stripping away'
    ' of material attachments, the soul\'s ascent to unity with the divine — that was homologous'
    ' with the alchemical account of material transformation. The language of purification,'
    ' dissolution, and regeneration runs through both traditions, and practitioners who were'
    ' influenced by both could draw on the resonances between them.</p>'
    '<p>The specific connection between Eckhartian mysticism and alchemy runs through the'
    ' tradition of German spiritual alchemy that developed in the fifteenth and sixteenth centuries,'
    ' particularly in the Rhineland and southwestern Germany where Eckhart\'s influence was'
    ' strongest. [LINK:heinrich-khunrath]\'s integration of Protestant mysticism with alchemical'
    ' laboratory practice reflects this tradition, as does the broader current of theosophical'
    ' alchemy associated with Jakob Böhme in the seventeenth century. Böhme\'s account of creation'
    ' as a process of divine self-differentiation through fire, sulphur, and salt — using the'
    ' language of [LINK:paracelsus]\'s tria prima — drew on both the Paracelsian chemical tradition'
    ' and the mystical tradition in which Eckhart was a central figure.</p>'
    '<p>Eckhart\'s condemnation (a papal bull of 1329 condemned twenty-eight propositions from his'
    ' writings, issued after his death) placed his works under a cloud of theological suspicion'
    ' that limited but did not prevent their circulation. His German-language sermons, in particular,'
    ' continued to circulate in manuscript and were read by those interested in mystical theology.'
    ' The eventual rehabilitation of Eckhart — recognized in modern Catholic theology as a major'
    ' figure whose condemned propositions were taken out of context — mirrors in some ways the'
    ' rehabilitation of alchemical practitioners whose serious intellectual engagement was obscured'
    ' by the dismissal of their goals as superstitious: in both cases, scholars in the twentieth'
    ' century have recovered figures whose historical importance was obscured by earlier dismissals.</p>'
    '<p>Bernard McGinn\'s multi-volume study of Western Christian mysticism provides the scholarly'
    ' context for Eckhart. C.F. Kelley\'s and Reiner Schürmann\'s analyses of his philosophy have'
    ' explored his relationship to German idealism. The connections between Eckhartian mysticism and'
    ' alchemical thought have been noted by Antoine Faivre in his studies of Western esoteric'
    ' traditions and by [LINK:wouter-hanegraaff] in his broader analysis of the history of Western'
    ' esotericism as a category of rejection. Eckhart is thus a background figure for the history'
    ' of alchemy — not a practitioner but a provider of conceptual and spiritual resources that'
    ' practitioners drew on in understanding the meaning of their work.</p>'
)

MUHIB_BIO = (
    '<p>Muhammad ibn Umail al-Tamimi (fl. c. 900–960 CE), known in the Latin tradition as Senior'
    ' Zadith, was an Islamic alchemist whose major work, <i>Kitab al-Ma\' al-Waraqi wa al-Ard'
    ' al-Najmiyya</i> (Book of the Silvery Water and the Starry Earth), also known as <i>Hall'
    ' al-Rumuz</i> (The Explanation of Symbols), is one of the most symbolically complex texts'
    ' in the Arabic alchemical tradition. It was translated into Latin as <i>Tabula Chemica</i>'
    ' (Chemical Table) and later as the <i>Epistola Solis et Lunae</i>, becoming influential'
    ' in medieval and early modern Latin alchemy.</p>'
    '<h2>Symbolic Alchemy and the Arabic Tradition</h2>'
    '<p>Ibn Umail\'s approach to alchemy was distinctive in its emphasis on the interpretation'
    ' of earlier alchemical texts through symbolic and allegorical reading. His major work is'
    ' organized as a commentary on an earlier text attributed to Hermes, the <i>Risalat'
    ' al-Shams ila al-Hilal</i> (Epistle of the Sun to the Crescent), and it proceeds through'
    ' careful explanation of the symbolic images that the text employs. This commentary structure'
    ' made ibn Umail a significant transmitter and interpreter of the earlier Greek-Arabic'
    ' alchemical tradition, and his work preserves material from earlier sources that would'
    ' otherwise be lost.</p>'
    '<p>The specific symbols that ibn Umail\'s work addresses — the king and queen, sun and moon,'
    ' the red and white tinctures — became standard elements of the symbolic vocabulary of both'
    ' Arabic and Latin alchemy. His influence on the <i>Rosarium Philosophorum</i> tradition in'
    ' Latin alchemy is attested by the quotations and borrowings that scholars have identified.'
    ' [LINK:isaac-newton] was familiar with texts in this tradition, as the Chymistry of Isaac'
    ' Newton project has documented through transcriptions of his alchemical notebooks. The'
    ' continuity between ibn Umail\'s symbolic system and the symbolic vocabulary that Newton'
    ' was working with — across several centuries and two translation stages — is evidence for'
    ' the durability of the alchemical symbolic tradition as a vehicle for the transmission'
    ' of both practical and theoretical knowledge.</p>'
    '<p>Theodoros Arabatzis and others have contributed to the scholarly analysis of ibn Umail\'s'
    ' place in the Arabic alchemical tradition. His text was edited and translated by Martin Levey'
    ' (the <i>Kitab</i> portion) and has been the subject of ongoing scholarly attention for its'
    ' role in the transmission of Greek alchemical symbolism into the Arabic tradition and thence'
    ' into Latin alchemy. The <i>Tabula Chemica</i> was printed in the Theatrum Chemicum series,'
    ' ensuring its availability to early modern European practitioners and its continued influence'
    ' on the alchemical tradition through the seventeenth century and beyond.</p>'
)

GERBERT_BIO = (
    '<p>Gerbert of Aurillac (c. 945–1003 CE), who became Pope Sylvester II in 999, was one of the'
    ' most learned men in Latin Europe in the period before the twelfth-century translation movement'
    ' that brought Arabic natural philosophy to Western readers. His learning was exceptional for his'
    ' time: he studied in Catalonia and in the orbit of the Muslim-Christian borderland of Iberia,'
    ' acquiring knowledge of Arabic mathematics, astronomy, and natural philosophy that was largely'
    ' unavailable to scholars in northern Europe.</p>'
    '<h2>Pre-Translation Arabic Learning and the Legend</h2>'
    '<p>Gerbert introduced or popularized the Hindu-Arabic numerals in Latin Europe, used the'
    ' abacus in his teaching, constructed armillary spheres and organs, and taught arithmetic,'
    ' music, geometry, and astronomy according to the classical quadrivium at Reims, where his'
    ' school attracted students from across Europe. His astronomical and mathematical knowledge'
    ' set him apart from his contemporaries in ways that contributed to the legendary reputation'
    ' that accumulated around him after his death.</p>'
    '<p>The legend of Gerbert-as-magician — which includes stories of a brazen head that answered'
    ' questions, a pact with the devil, and the acquisition of occult knowledge from Arabic or'
    ' Saracen teachers — reflects the medieval European reception of Arabic natural philosophy'
    ' as suspicious and potentially diabolical. His knowledge was so far beyond what his'
    ' contemporaries expected that it seemed miraculous or magical; and his acquisition of it'
    ' from Muslim sources in Spain made it theologically ambiguous. The legend of Gerbert as'
    ' magician is thus evidence for the cultural dynamics of knowledge transfer between the'
    ' Islamic and Christian worlds in the tenth and eleventh centuries — the same dynamics'
    ' that shaped the reception of Arabic alchemy when it arrived in Latin translation in the'
    ' twelfth century.</p>'
    '<p>Whether Gerbert had any contact with alchemical knowledge specifically is unknown; the'
    ' sources do not attest it, and the tenth century was too early for substantial Latin'
    ' access to Arabic alchemical texts. His significance for the history of alchemy is'
    ' therefore primarily as a precursor of the translation movement and as evidence for the'
    ' cultural-epistemological dynamics that would shape how Arabic natural knowledge, including'
    ' alchemy, was received when it arrived in Latin Europe in the following centuries. His'
    ' legendary status as a magician-pope — the man whose extraordinary learning was interpreted'
    ' as diabolical — anticipates the ambivalent reception that alchemical practitioners would'
    ' receive throughout the medieval period.</p>'
)

DIGBY_BIO = (
    '<p>Sir Kenelm Digby (1603–1665) was an English courtier, diplomat, natural philosopher, and'
    ' alchemical practitioner whose career bridged Royalist exile, Royal Society membership, and'
    ' the social world of mid-seventeenth-century European learned culture. A Catholic who remained'
    ' loyal to the Stuarts through the Interregnum, he spent years in Paris and Rome, corresponding'
    ' with Descartes, Mersenne, and other continental natural philosophers while pursuing alchemical'
    ' inquiries and writing on natural philosophy.</p>'
    '<h2>Weapon-Salve, Sympathy, and Chemical Philosophy</h2>'
    '<p>Digby is best known for his advocacy of the "powder of sympathy" — a cure for sword wounds'
    ' in which the weapon rather than the wound was treated, the operation working at a distance'
    ' through the medium of a vitriol-based powder. His <i>Discourse concerning the Vegetation'
    ' of Plants</i> (1661) proposed a mechanical account of plant growth that attempted to explain'
    ' natural processes in corpuscular terms while retaining elements of occult sympathy. His'
    ' <i>Two Treatises: Of Bodies and Of Man\'s Soul</i> (1644) engaged with Aristotelian and'
    ' Cartesian natural philosophy while defending traditional Catholic doctrines about the soul.</p>'
    '<p>Digby\'s alchemical interests are attested by his correspondence with [LINK:robert-boyle]'
    ' and by references in his published works. He was among the network of practitioners and'
    ' interested gentlemen who constituted the social world of mid-seventeenth-century English'
    ' chymistry — the network that also included [LINK:george-starkey], Boyle, and eventually'
    ' [LINK:isaac-newton]. His position as a Catholic Royalist with extensive continental'
    ' connections gave him access to practitioners and texts that his Protestant compatriots'
    ' might not easily reach, and his social standing as a knight and courtier gave alchemical'
    ' pursuits a prestige endorsement that was valuable in a culture organized around patronage'
    ' and social hierarchy.</p>'
    '<p>Michael Foster\'s work on Digby\'s natural philosophy and the broader scholarship on'
    ' the social world of mid-seventeenth-century English natural philosophy provide the'
    ' scholarly context for situating him. His career illustrates the degree to which alchemy,'
    ' corpuscular philosophy, occult sympathy, and the emerging experimental program of the'
    ' Royal Society coexisted in the same intellectual milieu without yet being clearly'
    ' separated — the same undivided cultural landscape that [LINK:elias-ashmole] and the'
    ' early Royal Society members inhabited.</p>'
)

BOSTOCKE_BIO = (
    '<p>Richard Bostocke (fl. 1585) was an English Paracelsian physician whose <i>Auncient'
    ' and Learned Work of the Trew and Ancient Physick</i> (1585) is one of the earliest'
    ' English defenses of Paracelsian chemical medicine. Writing against Galenic medical'
    ' orthodoxy, Bostocke argued that Paracelsian medicine was not an innovation but a recovery'
    ' of the ancient knowledge that had been corrupted by Greek and Arabic writers: a claim'
    ' that placed chemical medicine within the tradition of the <i>prisca sapientia</i> (ancient'
    ' wisdom) rather than treating it as a dangerously novel departure from received tradition.</p>'
    '<h2>English Paracelsianism and the Defense of Chemical Medicine</h2>'
    '<p>Bostocke\'s text is significant for the history of English Paracelsianism because it'
    ' represents the specifically English reception of Paracelsian ideas in the mid-sixteenth'
    ' century, engaging with the controversy about chemical versus Galenic medicine at a time'
    ' when that controversy was shaping English medical culture. His argument that Paracelsian'
    ' medicine was ancient rather than novel was a standard defensive move in the reception'
    ' of Paracelsian ideas: by presenting the tria prima and chemical medicine as recoveries of'
    ' original divine knowledge rather than innovations, practitioners could claim the authority'
    ' of antiquity while defending genuinely new approaches to medical practice.</p>'
    '<p>The historiography of English Paracelsianism has been developed by Charles Webster,'
    ' whose <i>The Great Instauration</i> (1975) analyzed the relationship between Paracelsian'
    ' reform, Puritan religious culture, and the development of the experimental philosophy in'
    ' seventeenth-century England. Bostocke appears in this history as a relatively early marker'
    ' of the Paracelsian presence in English medical culture before it was absorbed and transformed'
    ' by the broader development of English chymistry in the work of [LINK:george-starkey],'
    ' [LINK:robert-boyle], and others. His text is thus a historical document for the reception'
    ' of Paracelsianism in England rather than a contribution to the development of chemical'
    ' knowledge in its own right.</p>'
)

NORTON_BIO = (
    '<p>Samuel Norton (1548–1621) was an English alchemical practitioner and writer whose works,'
    ' including <i>Catholicon, or a New Art of Transmutation</i> and several other treatises,'
    ' represent the continuation of the English alchemical verse tradition associated with'
    ' [LINK:george-ripley] into the late sixteenth and early seventeenth centuries. Norton'
    ' claimed descent from Thomas Norton, the fifteenth-century alchemist who wrote the'
    ' <i>Ordinal of Alchemy</i>, and positioned himself as an heir to the English alchemical'
    ' tradition.</p>'
    '<h2>Practice, Patronage, and the English Tradition</h2>'
    '<p>Norton\'s works engage with both the theoretical tradition inherited from Ripley and'
    ' with practical laboratory procedures. His accounts of his own experiments and failures'
    ' — including periods of poverty and disappointment — are consistent with the broader'
    ' pattern of English alchemical practitioners who pursued the Stone across decades of'
    ' laboratory work without achieving their goal. The continuity between Norton\'s'
    ' self-presentation and that of Chaucer\'s Canon\'s Yeoman — both describe lives'
    ' organized around the pursuit of alchemical goals that remain perpetually out of reach —'
    ' reflects the structural conditions of alchemical practice rather than individual'
    ' failure: the Stone was always asymptotically approachable but never reached.</p>'
    '<p>[LINK:elias-ashmole] included Norton in his <i>Theatrum Chemicum Britannicum</i>,'
    ' cementing his place in the canon of English alchemical writing. This editorial inclusion'
    ' reflects Ashmole\'s project of constructing a continuous English alchemical tradition;'
    ' Norton\'s position as a claimed descendant of Thomas Norton and as a practitioner who'
    ' engaged explicitly with the Ripley tradition made him a useful link in the chain'
    ' Ashmole was assembling. Jennifer Rampling\'s analysis of the English alchemical tradition'
    ' from Ripley through Newton situates Norton within this lineage.</p>'
)

BACKHOUSE_BIO = (
    '<p>William Backhouse (1593–1662) was an English country gentleman, antiquary, and alchemical'
    ' practitioner who served as a significant transmitter of alchemical knowledge in mid-seventeenth-century'
    ' England. His most important contribution to the history of alchemy lies in his relationship'
    ' to [LINK:elias-ashmole]: Backhouse communicated the "true matter of the Philosopher\'s Stone"'
    ' to Ashmole in May 1653, an event that Ashmole recorded in his diary as occurring when Backhouse'
    ' "opened himself" and revealed the secret, fearing death. Whether this communication contained'
    ' specific laboratory procedure, general theoretical framework, or something more ambiguous is'
    ' unclear from the diary evidence, but the episode illustrates the structure of transmission'
    ' in alchemical culture: secrets passed from practitioner to trusted student, often at moments'
    ' of crisis or mortality.</p>'
    '<h2>Transmission, Trust, and Alchemical Culture</h2>'
    '<p>Backhouse\'s own alchemical learning is thought to have derived from John Dee\'s circle'
    ' through intermediaries. If this genealogy is correct, it represents a transmission chain'
    ' connecting the Elizabethan alchemical culture of [LINK:john-dee] to the Restoration culture'
    ' of Ashmole and the early Royal Society — a chain that was operating through personal'
    ' transmission of secrets in oral or manuscript form rather than through printed texts.'
    ' This mode of transmission coexisted with the print tradition of alchemical texts analyzed'
    ' by [LINK:william-newman] and [LINK:lawrence-principe], and represents the dimension of'
    ' alchemical culture that was most specifically resistant to public disclosure.</p>'
    '<p>Backhouse\'s significance for the historiography of English alchemy lies primarily in'
    ' the insight his relationship with Ashmole provides into the social organization of'
    ' alchemical transmission. The "adoption" of Ashmole as a student, the eventual communication'
    ' of a secret, the setting of a private English household — these details fill out the social'
    ' world of practical alchemy in ways that the published texts cannot, and they situate'
    ' alchemical practice within the world of English Royalist gentlemanly culture that also'
    ' produced the antiquarian, astrological, and early scientific interests that Ashmole combined.'
    ' Jennifer Rampling\'s scholarship on English alchemy, Charles Webster\'s work on the'
    ' social history of seventeenth-century English natural philosophy, and Lauren Kassell\'s'
    ' work on medicine, magic, and society provide the scholarly context for understanding'
    ' Backhouse and his circle.</p>'
)

HOMBERG_BIO = (
    '<p>Wilhelm Homberg (1652–1715) was a German-born natural philosopher and physician who'
    ' spent most of his career in France, becoming a member of the Académie Royale des Sciences'
    ' in 1691 and serving as the primary chemical instructor and collaborator of Philippe II,'
    ' Duke of Orléans. His laboratory at the Palais Royal, funded and equipped by the Duke,'
    ' was one of the best-equipped chemical research facilities in early eighteenth-century'
    ' France.</p>'
    '<h2>Between Alchemy and the New Chemistry</h2>'
    '<p>Homberg occupies an interesting transitional position in the history of chemistry:'
    ' trained in the older tradition of chymistry and alchemical practice, he worked through'
    ' the period in which the phlogiston theory was being established and the boundary between'
    ' alchemy and chemistry was beginning to be more firmly drawn. His chemical work engaged'
    ' with questions about the composition of light and fire (investigating whether light had'
    ' weight, using the lens of the Palais Royal to focus sunlight on substances), the chemistry'
    ' of acids and salts, and the preparation of phosphorus. This research was at the frontier'
    ' of the chemical investigations of his era.</p>'
    '<p>The Duke of Orléans\'s alchemical interests and Homberg\'s service to them illustrate'
    ' the persistence of patronage-based alchemical practice into the early eighteenth century,'
    ' alongside the institutionalized chemistry of the Académie. The combination of institutional'
    ' membership, private laboratory research for an aristocratic patron, and interest in both'
    ' Académie-style chemical investigation and alchemical goals represents the transitional'
    ' character of early eighteenth-century chemistry, not yet fully separated from its'
    ' alchemical past but increasingly organized around the institutions and methods that'
    ' would define the post-Lavoisier discipline. Lawrence Principe has analyzed Homberg\'s'
    ' career in the context of his broader study of French chymistry in the early modern period.</p>'
)

# ── 19th century figures (brief but over 1200) ────────────────────────────────

WOHLER_BIO = (
    '<p>Friedrich Wöhler (1800–1882) was a German chemist whose synthesis of urea from inorganic'
    ' ammonium cyanate in 1828 is traditionally presented as the experiment that disproved'
    ' vitalism — the doctrine that organic compounds could only be produced by living organisms'
    ' and therefore could not be synthesized from inorganic starting materials in the laboratory.'
    ' The urea synthesis demonstrated that the boundary between organic (life-produced) and'
    ' inorganic (mineral) chemistry was permeable, with profound consequences for the subsequent'
    ' development of organic chemistry and biochemistry.</p>'
    '<h2>Urea, Vitalism, and the Alchemy Connection</h2>'
    '<p>The relationship of the urea synthesis to alchemy is primarily symbolic but historically'
    ' instructive. Alchemical practitioners had long claimed that art could imitate and surpass'
    ' nature, producing through laboratory operations what nature accomplished through her hidden'
    ' processes. The vitalist doctrine that organic life was irreducibly distinct from inorganic'
    ' chemistry represented a residual form of this older boundary — a limit on what chemistry'
    ' could accomplish. Wöhler\'s synthesis removed this limit, demonstrating that the products'
    ' of living organisms were subject to chemical synthesis from non-living materials.</p>'
    '<p>The traditional narrative in which the urea synthesis "killed vitalism" has been'
    ' significantly qualified by historians of chemistry. Timothy Lenoir and others have'
    ' shown that vitalism persisted well after 1828 in various forms, and that Wöhler himself'
    ' did not interpret his experiment as definitively disproving vitalism — his letter to'
    ' Berzelius, often quoted for the phrase about making urea without a kidney or a dog,'
    ' is more ambivalent than the standard narrative suggests. The simplification of the urea'
    ' synthesis story is an example of the same kind of retrospective construction of scientific'
    ' landmarks that [LINK:william-newman] and [LINK:lawrence-principe] have identified in the'
    ' construction of the alchemy-chemistry boundary.</p>'
    '<p>Wöhler trained with [LINK:jons-jacob-berzelius] in Stockholm, and his career in the'
    ' German chemical tradition — at Göttingen from 1836 until his death — was enormously'
    ' productive: he isolated aluminum, beryllium, and silicon, contributed to the development'
    ' of organic chemistry, and trained many of the next generation of German chemists. His'
    ' significance for the history of alchemy lies primarily in his position at the end of the'
    ' story: as the chemist whose work most visibly crossed the boundary that alchemy had sought'
    ' unsuccessfully to cross — the transformation of one substance into another of a different'
    ' fundamental type — he represents both the fulfillment and the transcendence of alchemical'
    ' aspirations through the methods of nineteenth-century laboratory science.</p>'
)

BERZELIUS_BIO = (
    '<p>Jöns Jacob Berzelius (1779–1848) was a Swedish chemist who established many of the'
    ' fundamental conventions of modern chemistry: the system of chemical symbols (letters from'
    ' element names) still in use, the concept of chemical equivalents, the determination of'
    ' atomic weights for most known elements, and the classification of substances into organic'
    ' and inorganic chemistry. His <i>Lärobok i kemien</i> (Textbook of Chemistry) went through'
    ' multiple editions and was translated into German, French, and English, making it the standard'
    ' European chemical education text of the first half of the nineteenth century.</p>'
    '<h2>Atomic Theory and the Legacy of Alchemy</h2>'
    '<p>Berzelius worked within the framework established by [LINK:antoine-lavoisier]\'s'
    ' Chemical Revolution: the conservation of matter, the role of oxygen in combustion and'
    ' acidification, and the systematic identification of chemical elements. His development'
    ' of atomic weights and chemical symbolism extended and formalized Lavoisier\'s program,'
    ' giving chemistry the quantitative precision and consistent notation that allowed it to'
    ' develop as a cumulative scientific discipline. In this sense, his work represents the'
    ' consolidation of the chemical revolution that completed the separation of chemistry from'
    ' its alchemical past.</p>'
    '<p>Berzelius\'s attitude toward alchemy was dismissive: like most nineteenth-century chemists,'
    ' he understood alchemy as a collection of confused and credulous attempts to achieve what'
    ' proper chemistry had shown to be impossible. This dismissal was part of the construction of'
    ' chemistry\'s disciplinary identity that [LINK:william-newman] and [LINK:lawrence-principe]'
    ' have analyzed: the new chemistry defined itself against alchemy as rational against irrational,'
    ' scientific against prescientific. The historiographical work of Newman, Principe, and others'
    ' has substantially revised this narrative, showing that the early modern chymical tradition'
    ' was more experimentally rigorous and less mystically irrational than the nineteenth-century'
    ' dismissal suggested.</p>'
    '<p>His discovery of vitalism — the doctrine that organic chemistry involved a special vital'
    ' force not present in inorganic chemistry — which he eventually abandoned in the face of'
    ' [LINK:friedrich-wohler]\'s urea synthesis and other experimental results, reflects the'
    ' difficulty of maintaining sharp categorical boundaries between domains that laboratory'
    ' investigation reveals to be continuous. This epistemological difficulty, which Berzelius'
    ' navigated in the context of organic versus inorganic chemistry, was homologous with the'
    ' difficulty that the alchemy-chemistry boundary presented: boundaries drawn for conceptual'
    ' and disciplinary reasons have a tendency to be eroded by the very experimental work they'
    ' are designed to organize.</p>'
)

LIEBIG_BIO = (
    '<p>Justus von Liebig (1803–1873) was a German chemist who transformed organic chemistry'
    ' and agricultural chemistry through his laboratory at Giessen (and later Munich), which'
    ' became the model for the research-oriented chemistry laboratory that shaped the discipline'
    ' through the remainder of the nineteenth century. His systematic training of students in'
    ' analytical laboratory technique produced a generation of chemists who spread the German'
    ' research model across Europe and America.</p>'
    '<h2>Agricultural Chemistry and the End of Vitalism</h2>'
    '<p>Liebig\'s <i>Organic Chemistry in its Applications to Agriculture and Physiology</i>'
    ' (1840) argued that plant growth depended on mineral nutrients — nitrogen, phosphorus,'
    ' potassium — that could be provided artificially, establishing the theoretical basis for'
    ' modern agricultural chemistry and the fertilizer industry. This work connected organic'
    ' chemistry to practical agriculture in ways that generated enormous commercial interest'
    ' and eventually transformed European and American agriculture.</p>'
    '<p>His relationship to alchemy in the historiographical sense is similar to that of'
    ' [LINK:jons-jacob-berzelius]: he worked within the post-Lavoisier framework and understood'
    ' alchemy as pre-scientific error. His historical writings on chemistry, including the'
    ' introduction to his <i>Chemical Letters</i>, dismissed alchemical practitioners as confused'
    ' empiricists who failed to develop proper scientific method. This assessment, representative'
    ' of nineteenth-century chemical historiography, has been substantially revised by the'
    ' scholarship of [LINK:william-newman] and [LINK:lawrence-principe], which demonstrates'
    ' that the experimental practices of seventeenth-century chymists like [LINK:george-starkey]'
    ' and [LINK:robert-boyle] were more systematic and quantitatively sophisticated than the'
    ' Liebig-era dismissal acknowledged.</p>'
    '<p>Liebig\'s institutional legacy — the research laboratory as the primary site of chemical'
    ' training and knowledge production — is itself a transformation of the alchemical laboratory'
    ' tradition. The early modern chymical laboratory that [LINK:george-starkey] worked in,'
    ' [LINK:robert-boyle] built at Oxford and London, and [LINK:isaac-newton] maintained at'
    ' Cambridge was a direct ancestor of the research laboratory that Liebig institutionalized'
    ' at Giessen. The transformation involved changes in purpose (knowledge production for its own'
    ' sake and for industrial application, rather than the Philosophers\' Stone), scale (multiple'
    ' students working simultaneously rather than a single practitioner with an assistant), and'
    ' social organization (university-based rather than patronage-dependent), but the basic model'
    ' of the chemist working at a bench with equipment and materials is continuous across the'
    ' transition from alchemy to chemistry.</p>'
)

BERTHELOT_BIO = (
    '<p>Marcellin Berthelot (1827–1907) was a French chemist, historian of chemistry, and public'
    ' intellectual whose career combined major contributions to organic chemistry with pioneering'
    ' work in the history of alchemy. His chemical contributions included synthesis of numerous'
    ' organic compounds, foundational work on thermochemistry, and the development of bomb'
    ' calorimetry. His historical contributions — the edition of Greek alchemical texts and'
    ' the multi-volume history of alchemy — established the scholarly foundations for the field'
    ' even as they also embedded assumptions that later scholars have found limiting.</p>'
    '<h2>The Historical Edition and Its Legacy</h2>'
    '<p>Berthelot\'s three-volume <i>Collection des anciens alchimistes grecs</i> (1887–1888),'
    ' produced with the assistance of the Hellenist C.E. Ruelle, provided the first systematic'
    ' scholarly edition of the Greek alchemical corpus with Greek text, French translation, and'
    ' commentary. This edition remains a fundamental resource for scholars of ancient alchemy,'
    ' despite its age, because no complete re-edition of the Greek alchemical corpus has been'
    ' produced since. His subsequent <i>Les origines de l\'alchimie</i> (1885) and three-volume'
    ' <i>La chimie au moyen âge</i> (1893) extended his historical coverage to Arabic and Latin'
    ' medieval alchemy.</p>'
    '<p>The historiographical framework that Berthelot\'s historical work established was the'
    ' "continuist" view: alchemy was a precursor to chemistry, chemistry grew out of alchemy by'
    ' discarding its mystical and fraudulent aspects while retaining its practical chemical'
    ' knowledge. This framework, which presented alchemy and chemistry as stages in a continuous'
    ' progressive development, dominated the history of chemistry through most of the twentieth'
    ' century. It is precisely the framework that [LINK:william-newman] and [LINK:lawrence-principe]\'s'
    ' "chymistry" approach has revised: the discontinuity they stress — that the alchemy-chemistry'
    ' boundary was constructed retrospectively rather than existing as a natural historical divide —'
    ' directly challenges the continuist narrative that Berthelot helped establish. His edition'
    ' of the Greek texts remains indispensable; his historical interpretive framework has been'
    ' substantially superseded.</p>'
)

# ── Brian Copenhaver, Franciscus Patricius, Christiaan Huygens, etc. ──────────

COPENHAVER_BIO = (
    '<p>Brian Copenhaver (b. 1939) is an American historian of philosophy and Renaissance thought'
    ' whose scholarly contributions include major translations, commentaries, and studies of the'
    ' Hermetic tradition, Neoplatonism, and Renaissance natural magic. His translation and edition'
    ' of the <i>Corpus Hermeticum</i> (Cambridge, 1992) is the standard English scholarly edition,'
    ' providing Greek text, English translation, and extensive philosophical commentary that'
    ' situates the texts within their late antique intellectual context.</p>'
    '<h2>Hermeticism and Renaissance Scholarship</h2>'
    '<p>Copenhaver\'s work on the <i>Corpus Hermeticum</i> built on the foundational French'
    ' edition of A.D. Nock and A.-J. Festugière (1945–1954) while making the texts accessible'
    ' to English-language scholars and providing a more thorough philosophical commentary than'
    ' any previous edition. His analysis of the philosophical content of the Hermetic dialogues —'
    ' their Platonic, Stoic, and Gnostic elements, their cosmological and soteriological structure,'
    ' their relationship to other late antique religious and philosophical texts — established'
    ' the scholarly framework within which Renaissance reception of the Hermetica can be analyzed.'
    ' His work on magic — particularly his study of Giovanni Pico della Mirandola\'s conception'
    ' of magic and his essay on "Did Science Have a Renaissance?" — has contributed to the'
    ' ongoing debates about the relationship between Hermeticism, natural magic, and the'
    ' development of early modern science.</p>'
    '<p>Copenhaver\'s relationship to the Newman/Principe framework on chymistry is that of a'
    ' scholar working on the philosophical and textual dimensions of the Hermetic tradition that'
    ' provided the legitimating intellectual context for alchemical practice. His concern is'
    ' primarily with the texts and their ideas rather than with laboratory operations; but the'
    ' ideas he analyzes — the Hermetic cosmological framework, the doctrine of sympathies and'
    ' correspondences, the account of matter as ensouled and subject to transformation — are'
    ' precisely the philosophical resources that alchemical practitioners drew on. Understanding'
    ' Copenhaver\'s work thus means understanding the intellectual background against which'
    ' the experimental chymistry studied by Newman and Principe was conducted.</p>'
)

HOBBES_BIO = (
    '<p>Thomas Hobbes (1588–1679) is best known as a political philosopher — author of <i>Leviathan</i>'
    ' (1651), the most influential work of political theory in the English language — and as a'
    ' materialist natural philosopher who reduced mental events to motions of matter and dismissed'
    ' incorporeal substances as conceptual confusions. His relationship to alchemy was primarily'
    ' polemical: his materialism and his dismissal of occult qualities and hidden causes put him'
    ' in explicit opposition to the natural philosophical frameworks that alchemy depended on.</p>'
    '<h2>Materialism and the Critique of Occult Philosophy</h2>'
    '<p>Hobbes\'s exchange with [LINK:robert-boyle] over the interpretation of Boyle\'s air-pump'
    ' experiments — analyzed by Steven Shapin and Simon Schaffer in <i>Leviathan and the Air-Pump</i>'
    ' (1985) — was partly about the epistemology of experimental knowledge and partly about the'
    ' politics of natural philosophical authority. Hobbes argued that Boyle\'s experimental'
    ' demonstrations proved nothing about the nature of the vacuum (he denied the void on'
    ' mechanical philosophical grounds); Boyle argued that careful experimental observation'
    ' could produce reliable knowledge even without complete theoretical understanding. This'
    ' dispute, which Shapin and Schaffer analyze as a foundational moment in the social construction'
    ' of scientific knowledge, touched on the same questions about the relationship between'
    ' theory and practice, and between demonstration and proof, that organized alchemical'
    ' epistemology.</p>'
    '<p>Hobbes\'s mechanist materialism — his reduction of all natural phenomena to motion and'
    ' matter, his elimination of occult qualities, his denial of active principles that were'
    ' not mechanical — was in tension with the theoretical frameworks of the alchemical tradition.'
    ' The "active principles" that [LINK:isaac-newton] sought to identify through his alchemical'
    ' research, and that [LINK:robert-boyle] hoped to discover through his chymical inquiries,'
    ' were precisely the kind of non-mechanical powers that Hobbes\'s natural philosophy denied.'
    ' The debate between mechanist and alchemical natural philosophy that Hobbes\'s work crystallizes'
    ' was eventually resolved in favor of neither pure mechanism nor pure alchemy but in the'
    ' synthesis of mathematical mechanics with chemical analysis that produced eighteenth-century'
    ' physics and chemistry.</p>'
)

GOETHE_BIO = (
    '<p>Johann Wolfgang von Goethe (1749–1832) was the preeminent German literary figure of'
    ' his era and a serious natural philosopher whose scientific work — particularly his color'
    ' theory (<i>Zur Farbenlehre</i>, 1810) and his botanical morphology — represented a'
    ' systematic alternative to the mathematical-mechanistic natural philosophy that Newton had'
    ' established. His engagement with alchemy was significant and sustained: he studied alchemical'
    ' texts in his youth, maintained a chemical laboratory for years, and drew on alchemical'
    ' symbolism extensively in <i>Faust</i>.</p>'
    '<h2>Alchemy in Faust and Goethe\'s Natural Philosophy</h2>'
    '<p>The alchemical laboratory that dominates the opening scenes of <i>Faust, Part I</i>'
    ' (1808) — the scholar surrounded by alchemical equipment, seeking to penetrate nature\'s'
    ' secrets through Hermetic learning — represents both Goethe\'s engagement with the'
    ' alchemical tradition and his ambivalence about it. Faust\'s dissatisfaction with the'
    ' limitations of alchemical knowledge, his pact with Mephistopheles, and his subsequent'
    ' transformation are read as a complex meditation on the human desire to exceed ordinary'
    ' limits through learned inquiry. The homunculus episode in <i>Faust, Part II</i> — in'
    ' which a chemical homunculus is created in a laboratory retort — draws directly on the'
    ' alchemical tradition of artificial generation.</p>'
    '<p>Goethe\'s own chemical interests were those of an educated amateur with serious'
    ' commitments. His color theory, which insisted on the qualitative character of color'
    ' experience against Newton\'s mathematical analysis of light, drew on the same holistic,'
    ' organic vision of nature that informed his botanical work. This vision — of nature as'
    ' an animated whole with its own formative forces, not reducible to the mechanical'
    ' interactions of indifferent particles — was closer to the Paracelsian and Hermetic'
    ' tradition than to the mathematical physics that was becoming dominant in his era.'
    ' His friendship with the chemist Johann Wolfgang Döbereiner, an early contributor to'
    ' atomic theory, connected him to the contemporary chemical community, but his own'
    ' theoretical commitments remained at odds with the quantitative-mathematical approach'
    ' that was transforming chemistry in the early nineteenth century.</p>'
    '<p>Goethe\'s alchemical interests have been analyzed by Rolf Christian Zimmermann,'
    ' whose multi-volume study of Goethe\'s occult interests documents the specific texts'
    ' he read and the laboratory work he did. The broader context of Romantic Naturphilosophie'
    ' — the German Romantic natural philosophy of Schelling and others that sought to recover'
    ' the organic, animated vision of nature against Newtonian mechanism — provides the'
    ' philosophical setting for Goethe\'s engagement with alchemy as an alternative to'
    ' the reductive science of his era.</p>'
)

SHAKESPEARE_BIO = (
    '<p>William Shakespeare (1564–1616) was the foremost English dramatist and poet of the'
    ' Elizabethan and Jacobean period. His relationship to alchemy is primarily that of a'
    ' highly literate playwright who drew on the cultural currency of alchemical reference in'
    ' plays written for audiences for whom the language and imagery of alchemy were familiar.'
    ' Several of his works contain significant alchemical references and imagery.</p>'
    '<h2>Alchemical Imagery in the Plays</h2>'
    '<p>The most sustained engagement with alchemical thinking in Shakespeare appears in'
    ' <i>The Merry Wives of Windsor</i>, where the character of Dr. Caius satirizes the'
    ' foreign alchemist figure, and more significantly in <i>All\'s Well That Ends Well</i>'
    ' (1604), where Helena\'s cure of the King uses a medicine obtained from her father —'
    ' a remedy that raises alchemical and magical associations that the play does not fully'
    ' dispel. <i>Othello</i>\'s imagery of jealousy as a corrosive substance, <i>The Winter\'s'
    ' Tale</i>\'s themes of transformation and the restoration of what seemed lost, and'
    ' <i>The Tempest</i>\'s Prospero as a master of natural magic all deploy alchemical and'
    ' Hermetic symbolic resources without making alchemy their explicit subject.</p>'
    '<p>Ben Jonson\'s <i>The Alchemist</i> (1610) — written for the same theatrical company'
    ' and audience as many of Shakespeare\'s plays — is the more directly relevant English'
    ' literary engagement with alchemical fraud, and comparison between Jonson\'s more satirically'
    ' focused treatment and Shakespeare\'s more diffuse use of alchemical imagery reveals'
    ' something about the cultural positioning of alchemy in Jacobean England. Both writers'
    ' could assume audience familiarity with alchemical language; Jonson focused this familiarity'
    ' into satire while Shakespeare deployed it as part of a broader symbolic vocabulary of'
    ' transformation and renewal that runs through his mature work.</p>'
    '<p>Stanton Linden\'s <i>Darke Hierogliphicks: Alchemy in English Literature from Chaucer'
    ' to the Restoration</i> (1996) provides the scholarly framework for situating Shakespeare\'s'
    ' use of alchemical imagery within the broader tradition of English literary engagement with'
    ' alchemy from [LINK:geoffrey-chaucer] through the Restoration period. Shakespeare\'s position'
    ' in this tradition is that of a writer who used the cultural resources of alchemical language'
    ' rather than a direct participant in alchemical practice or debate.</p>'
)

DANTE_BIO = (
    '<p>Dante Alighieri (1265–1321) was the foremost Italian poet of the medieval period,'
    ' best known for the <i>Divine Comedy</i> (c. 1308–1320). His relationship to alchemy'
    ' is primarily one of context and reception: he lived during the period of peak production'
    ' of medieval Latin alchemical texts, and the natural philosophical framework his poem'
    ' draws on — Aristotelian cosmology, Thomist theology, Neoplatonic elements — overlaps'
    ' substantially with the intellectual context of medieval alchemy.</p>'
    '<h2>Natural Philosophy and the Divine Comedy</h2>'
    '<p>The <i>Inferno</i>\'s placement of alchemists in the eighth circle of Hell (Bolgia 10,'
    ' among the falsifiers) is the most direct reference to alchemy in Dante\'s work. The two'
    ' alchemists Dante encounters — Griffolino of Arezzo (burned as a sorcerer) and Capocchio'
    ' (also burned) — are punished for counterfeiting metals: they suffer a disease that causes'
    ' their skin to itch and scale, a physical counterpart to the corrupted metals they produced.'
    ' Dante\'s punishment of alchemists among falsifiers reflects the dominant scholastic'
    ' assessment of alchemy in the late thirteenth and early fourteenth centuries: not heretical,'
    ' but fraudulent — a practice that deceived the unwary by producing imitations rather than'
    ' genuine products.</p>'
    '<p>The <i>Convivio</i> (The Banquet, c. 1304–1307) contains natural philosophical discussions'
    ' including accounts of mineral generation that engage with the Aristotelian-Avicennan'
    ' tradition — the same tradition that structured alchemical matter theory. Dante\'s account'
    ' of how metals form in the earth draws on the sulphur-mercury theory derived from [LINK:avicenna]'
    ' and reflects the same natural philosophical framework that alchemical practitioners used.'
    ' The <i>Divine Comedy</i>\'s elaborate cosmology — the planetary spheres, the elements, the'
    ' correspondences between celestial and terrestrial phenomena — is the same cosmological'
    ' framework that structured alchemical understanding of metallic transformation under planetary'
    ' influence.</p>'
    '<p>Dante\'s significance for the history of alchemy is thus primarily as a witness to the'
    ' cultural position of alchemy in early fourteenth-century Italy — its existence as a'
    ' recognized if morally ambiguous practice, its location within the natural philosophical'
    ' framework of Aristotelian scholasticism, and its association with fraud and counterfeiting'
    ' in the popular imagination even while serious practitioners continued their work within'
    ' the same intellectual tradition.</p>'
)

def load_all():
    conn = sqlite3.connect(DB)

    # Near-minimum top-ups
    for slug, extra in [
        ('johannes-trithemius', TRITHEMIUS_FINAL),
        ('muhammad-al-razi', RAZI_FINAL),
        ('nicholas-of-cusa', CUSA_FINAL),
        ('robert-grosseteste', GROSSETESTE_FINAL),
    ]:
        app(conn, slug, extra)

    # Full bios for stub entries
    for slug, bio in [
        ('christian-rosencreutz', ROSENCREUTZ_BIO),
        ('democritus', DEMOCRITUS_BIO),
        ('meister-eckhart', MEISTER_BIO),
        ('muhammad-ibn-umail', MUHIB_BIO),
        ('gerbert-of-aurillac', GERBERT_BIO),
        ('kenelm-digby', DIGBY_BIO),
        ('robert-bostocke', BOSTOCKE_BIO),
        ('samuel-norton', NORTON_BIO),
        ('william-backhouse', BACKHOUSE_BIO),
        ('wilhelm-homberg', HOMBERG_BIO),
        ('friedrich-wohler', WOHLER_BIO),
        ('jons-jacob-berzelius', BERZELIUS_BIO),
        ('justus-von-liebig', LIEBIG_BIO),
        ('marcellin-berthelot', BERTHELOT_BIO),
        ('brian-copenhaver', COPENHAVER_BIO),
        ('thomas-hobbes', HOBBES_BIO),
        ('johann-goethe', GOETHE_BIO),
        ('william-shakespeare', SHAKESPEARE_BIO),
        ('dante-alighieri', DANTE_BIO),
    ]:
        setp(conn, slug, bio)

    conn.commit()
    conn.close()
    print('\n=== Done ===')

if __name__ == '__main__':
    load_all()
