#!/usr/bin/env python3
"""expand_batch8_full_bios.py — Write full 1200+ word bios for remaining stub persons."""
import sqlite3, re
DB = 'db/alchemy_timeline.db'

def wc(h): return len(re.sub('<[^>]+>', ' ', h or '').split())

def app(conn, slug, extra):
    c = conn.cursor()
    c.execute('SELECT bio_html FROM persons WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    new = cur + extra
    c.execute('UPDATE persons SET bio_html=? WHERE slug=?', (new, slug))
    print(f'  {slug}: {wc(cur)} -> {wc(new)}')

ROSENCREUTZ_2 = (
    '<h2>The Manifestos: Content and Program</h2>'
    '<p>The <i>Fama Fraternitatis</i> presents Rosencreutz\'s journey to the East, where he studied'
    ' in Damcar (a city in Arabia that cannot be identified with any historical location) under teachers'
    ' who gave him a book — the Book M — containing the secrets of nature and the universe. Returning'
    ' to Europe via Fez (where he learned from the Arab sages) and then Spain and other countries,'
    ' he found that existing scholars were unwilling to accept his reforms. He eventually returned to'
    ' Germany, founded a brotherhood of eight members, established houses in different countries, and'
    ' maintained their community secretly for over a century. After his death, his burial vault was'
    ' discovered by the brotherhood one hundred and twenty years later, perfectly preserved, containing'
    ' his uncorrupted body, esoteric books, instruments, mirrors, and lamps — an underground temple'
    ' of wisdom surviving intact from the fifteenth century into the seventeenth.</p>'
    '<p>The <i>Confessio</i> adds to this narrative an explicit political and religious dimension:'
    ' the brotherhood condemns the Pope, the Emperor, and other established authorities, prophesies'
    ' imminent transformation of European religious life, and invites worthy individuals to join'
    ' the reform. The timing — published in 1615, shortly before the Bohemian crisis that precipitated'
    ' the Thirty Years\' War — gave the political dimension immediate resonance for readers who saw'
    ' Protestant Germany threatened by Catholic imperial power. Frances Yates argued that the'
    ' Rosicrucian texts were tools of propaganda for the Protestant cause led by Frederick V, Elector'
    ' Palatine, who briefly became King of Bohemia in 1619-1620.</p>'
    '<p>The alchemical content of the manifestos is pervasive but largely symbolic rather than'
    ' operational. The underground vault with its undecaying body parallels the alchemical symbolism'
    ' of the Stone as incorruptible gold; the Book M parallels the alchemical book of secret'
    ' knowledge; the brotherhood\'s program of healing the sick, refusing payment, and wearing'
    ' local dress reflects the Paracelsian physician-alchemist ideal. The <i>Chymical Wedding</i>'
    ' develops the alchemical symbolism most explicitly: the seven-day allegorical narrative involves'
    ' the death and resurrection of a king and queen, the distillation of their bodies to produce'
    ' homunculi, and the creation of a new being — stages that correspond to the alchemical work'
    ' of dissolution, purification, and regeneration.</p>'
    '<p>The question of who actually wrote the Rosicrucian manifestos has been partially but not'
    ' definitively resolved. Johann Valentin Andreae (1586-1654) is now accepted as the author of'
    ' the <i>Chymical Wedding</i>; the <i>Fama</i> and <i>Confessio</i> are more debated, with'
    ' various attributions to Andreae, Tobias Hess, and the Tübingen circle around them. The'
    ' texts originated in the Protestant scholarly culture of southwestern Germany — specifically'
    ' Württemberg and Tübingen — and were part of a broader discussion about the reform of'
    ' Christian learning and society that this circle was engaged in. Whether the authors intended'
    ' the texts as serious proposals, as literary experiments, or as some combination of both'
    ' remains a matter of scholarly debate that the evidence does not fully resolve.</p>'
)

DEMOCRITUS_2 = (
    '<h2>Pseudo-Democritus in the Latin Tradition</h2>'
    '<p>The pseudo-Democritean texts arrived in Latin Europe through the transmission history of'
    ' Greek alchemy: they were included in the manuscript collections of Greek alchemical texts'
    ' that were gradually translated or excerpted for Latin readers. By the time of the medieval'
    ' Latin tradition, "Democritus" was a recognized alchemical authority alongside Hermes'
    ' Trismegistus, Zosimos, and others. His name appears in lists of ancient alchemical teachers'
    ' and his works are cited as foundational texts of the tradition — the same strategy of'
    ' ancient attribution that characterized the Latin alchemical corpus more broadly.</p>'
    '<p>The actual chemical content of the pseudo-Democritean texts is primarily concerned with'
    ' dyeing: procedures for making copper look like gold, for whitening metals to resemble silver,'
    ' and for producing purple dye that imitates Tyrian purple. These are the same operations'
    ' that appear in the Egyptian papyri of the same period (the Stockholm and Leiden papyri,'
    ' which contain similar dyeing and metallurgical recipes). The relationship between these'
    ' practical recipes and the theoretical framework of four-element natural philosophy that'
    ' the text also invokes illustrates the dual character of early Greek alchemy: practical'
    ' workshop knowledge combined with philosophical legitimation from Aristotelian natural'
    ' philosophy.</p>'
    '<p>The connection between the historical Democritus\'s atomism and the later development'
    ' of corpuscular chemistry in the seventeenth century is historically significant even though'
    ' the pseudo-Democritus who wrote the alchemical texts was not an atomist. [LINK:robert-boyle]\'s'
    ' corpuscular philosophy drew on the revival of Epicurean atomism by Gassendi and others,'
    ' and his experimental chemistry drew on the practical laboratory tradition that the pseudo-Democritean'
    ' texts had contributed to. The name "Democritus" thus spans two quite different intellectual'
    ' contributions — ancient atomist philosophy and early Greek practical alchemy — that came'
    ' together in the seventeenth century in ways that had not been historically connected in'
    ' antiquity or the medieval period.</p>'
    '<p>Matteo Martelli\'s recent scholarship on the pseudo-Democritean corpus and other early'
    ' Greek alchemical texts has substantially advanced understanding of their historical context.'
    ' His critical edition of the texts attributed to pseudo-Democritus and his analysis of their'
    ' relationship to contemporary Egyptian workshop practice, Hellenistic natural philosophy,'
    ' and early Arabic alchemy have made it possible to situate these foundational texts in'
    ' their proper historical context rather than treating them as timeless expressions of'
    ' universal alchemical wisdom. The result is a more historically specific picture of the'
    ' origins of the Western alchemical tradition in the specific social and intellectual milieu'
    ' of Roman Egypt, where Greek philosophy, Egyptian craft practice, and Jewish religious'
    ' tradition were undergoing the complex processes of synthesis that produced both alchemy'
    ' and the Hermetic tradition.</p>'
)

MEISTER_2 = (
    '<h2>Dominican Natural Philosophy and Spiritual Transformation</h2>'
    '<p>Eckhart\'s Dominican formation connected him to one of the two major orders that had'
    ' driven the reception of Aristotelian natural philosophy into Latin scholasticism. Albert'
    ' the Great ([LINK:albertus-magnus]) and Thomas Aquinas ([LINK:thomas-aquinas]) were both'
    ' Dominicans; the order\'s intellectual tradition combined rigorous engagement with Aristotle'
    ' with commitment to preaching and active engagement with the world. Eckhart\'s own program'
    ' extended this tradition into what some scholars have called "speculative mysticism": a'
    ' theology that drew on both Neoplatonic philosophy (particularly Proclus and Pseudo-Dionysius)'
    ' and Aristotelian natural philosophy to develop an account of the soul\'s union with God.'
    ' His Latin sermons and treatises, written for academic audiences, develop the philosophical'
    ' framework; his German sermons, preached to religious women (Beguines and Dominican nuns),'
    ' translate this framework into vernacular spiritual instruction.</p>'
    '<p>The concept of <i>Gelassenheit</i> (releasement or detachment) in Eckhart\'s preaching'
    ' — the soul\'s progressive detachment from created things, including its own ego and will,'
    ' in order to be receptive to divine influx — has structural homologies with the alchemical'
    ' process of calcination: the burning away of impurities to reveal the pure substance beneath.'
    ' This homology was not accidental: both the mystical and alchemical traditions drew on the'
    ' same Neoplatonic framework of emanation and return, in which the soul descends from and'
    ' returns to the divine through processes of purification and transformation. The alchemical'
    ' tradition used this framework to understand material transformation; the mystical tradition'
    ' used it to understand spiritual transformation; and the overlap between them in the'
    ' language of purification, dissolution, death, and regeneration was available to writers'
    ' who wanted to connect laboratory and spiritual practice.</p>'
    '<p>Eckhart\'s condemned propositions touched on questions that were also relevant to'
    ' natural philosophy: his statements about the soul\'s identity with God, about the'
    ' uncreated intellect, and about the relationship between divine and human creativity'
    ' pushed the boundaries of orthodox theology in ways that had implications for'
    ' natural philosophical inquiry as well. If the soul participates directly in divine'
    ' creative intellect, human art participates in divine creation — an implication that'
    ' Eckhart drew from his mystical theology that was parallel to the claim that alchemical'
    ' practice participates in the divine creative work of nature that alchemists drew from'
    ' their natural philosophy. The boundary between mystical theology and natural magic was'
    ' permeable in both directions in medieval Latin culture.</p>'
    '<p>The German mystical tradition that Eckhart founded — continued through Johannes Tauler'
    ' and Heinrich Suso and eventually reaching the devotio moderna and the tradition of'
    ' German spiritual writing that included both orthodox and heterodox currents — provided'
    ' a sustained vocabulary of spiritual transformation that intersected with alchemical'
    ' language in the work of [LINK:heinrich-khunrath], Jakob Böhme, and others. The specific'
    ' connection between Eckhartian detachment (becoming "poor in spirit," emptied of self)'
    ' and alchemical mortification (the nigredo, death of the impure) was available to any'
    ' reader who moved between the mystical and alchemical traditions, and in the context of'
    ' sixteenth and seventeenth-century German Protestant culture, many readers did.</p>'
)

MUHIB_2 = (
    '<h2>Content of the Major Works</h2>'
    '<p>The <i>Kitab al-Ma\' al-Waraqi</i> (Book of Silvery Water) proceeds through a series'
    ' of commentaries on images and symbols drawn from earlier alchemical tradition. Its central'
    ' concern is the identification and preparation of the fundamental substance — the "silvery'
    ' water" or philosophical mercury — from which the Philosophers\' Stone can be made. The'
    ' text discusses the purification of mercury from its gross material form to its philosophical'
    ' or essential form, the relationship between the "red sulfur" (the solar principle) and the'
    ' "white mercury" (the lunar principle), and the union of these principles in the production'
    ' of the Stone. This theoretical framework is grounded in the Jabirian sulphur-mercury theory'
    ' but develops it in a direction more focused on the specific preparation of philosophical'
    ' mercury as a key step.</p>'
    '<p>Ibn Umail\'s text is remarkable for its extensive quotation and interpretation of earlier'
    ' alchemical authorities: [LINK:zosimos-of-panopolis], various texts attributed to Hermes,'
    ' and other Arabic alchemical writers are quoted, interpreted, and integrated into his own'
    ' theoretical framework. This makes the text not only a source of his own views but a'
    ' significant anthology of earlier alchemical thought, preserving materials that might'
    ' otherwise be lost and providing a key to how the earlier tradition was read by a'
    ' sophisticated tenth-century Islamic scholar.</p>'
    '<p>The Latin translation of ibn Umail\'s work as <i>Tabula Chemica</i> (or <i>Senior</i>,'
    ' the name by which the author is known in Latin) made it available to medieval and'
    ' early modern European practitioners. [LINK:isaac-newton] engaged with the Senior'
    ' tradition, as the Chymistry of Isaac Newton project has shown through transcriptions'
    ' of his alchemical notebooks. [LINK:george-ripley]\'s twelve-gate structure engages with'
    ' the symbolic tradition that ibn Umail helped define. The <i>Rosarium Philosophorum</i>'
    ' tradition in Latin alchemy drew extensively on Senior as one of its key authorities.'
    ' The transmission from ibn Umail through Latin translations to the English and other'
    ' European alchemical traditions of the sixteenth and seventeenth centuries represents'
    ' one of the important routes through which Arabic alchemical thinking shaped early'
    ' modern European practice.</p>'
    '<p>The recent scholarly edition by Theodoros Arabatzis and others of ibn Umail\'s texts'
    ' has substantially advanced understanding of his place in the Islamic alchemical tradition'
    ' and of the transmission of his work into Latin. The relationship between the Arabic'
    ' original and the Latin translation — what was translated accurately, what was mistranslated'
    ' or omitted, what was added by later transmitters — is part of the larger story of how'
    ' Arabic natural philosophy arrived in Latin Europe in forms that were subtly but sometimes'
    ' significantly different from their originals, differences that had consequences for how'
    ' the received material was understood and used.</p>'
)

GERBERT_2 = (
    '<h2>Mathematical and Astronomical Contributions</h2>'
    '<p>Gerbert\'s mathematical teaching at Reims drew on abacus texts that he had acquired'
    ' during his years in Catalonia, where he had access to manuscripts produced in the'
    ' Iberian borderland between Islamic and Christian culture. His introduction of the abacus'
    ' with Hindu-Arabic numerals to Latin European educational practice was not the immediate'
    ' introduction of the Hindu-Arabic numeral system as it is now understood — that would'
    ' come with [LINK:robert-of-chester]\'s translation of al-Khwarizmi in the twelfth century —'
    ' but rather an introduction of improved calculation methods using an abacus with digit'
    ' markers, a more efficient form than the Roman abacus. His teaching of arithmetic and'
    ' the relationships between numbers provided a model for mathematical education in the'
    ' cathedral schools that eventually produced the university curriculum.</p>'
    '<p>His astronomical work — the construction of armillary spheres, the observation of'
    ' stellar positions, the teaching of the Ptolemaic system — similarly reflected access'
    ' to astronomical knowledge circulating in the Iberian borderland that was not yet'
    ' available to most northern European scholars. This access to Arabic-influenced'
    ' astronomical learning through Catalonia placed Gerbert in the vanguard of a'
    ' knowledge transfer that would accelerate dramatically with the twelfth-century'
    ' translation movement but that was already beginning in Gerbert\'s lifetime. His'
    ' career as a teacher, politician, and eventually pope thus represents an early case'
    ' study in the dynamics of knowledge transfer across the Christian-Islamic frontier —'
    ' the same dynamics that would eventually bring Arabic alchemy, medicine, and natural'
    ' philosophy to Latin Europe through the work of translators like [LINK:robert-of-chester]'
    ' and [LINK:gerard-of-cremona].</p>'
    '<p>The legend that accumulated around Gerbert after his death — the brazen head, the'
    ' pact with the devil, the theft of Arabic occult knowledge — is itself significant'
    ' for the history of alchemy. It demonstrates that the acquisition of Arabic natural'
    ' philosophical knowledge was perceived, from the Christian side, as a potentially'
    ' diabolical transaction: knowledge so far beyond what was available in normal Latin'
    ' learning could only have been obtained through supernatural or illicit means.'
    ' This perception shaped the initial reception of Arabic alchemy when it arrived in'
    ' full in the twelfth century: the power of the knowledge claimed by alchemical texts'
    ' required legitimation precisely because it seemed to exceed what art could'
    ' accomplish through natural means, and the boundary between art and magic was'
    ' continuously contested in medieval Latin culture.</p>'
)

DIGBY_2 = (
    '<h2>Natural Philosophy Between Mechanism and Occult</h2>'
    '<p>Digby\'s <i>Two Treatises</i> (1644), written during his exile in Paris, attempted to'
    ' develop a natural philosophy that was both mechanistically respectable and compatible with'
    ' Catholic theology about the soul. His account of the body as a mechanical system — governed'
    ' by the interaction of particles — drew on Descartes\'s mechanical philosophy; his account'
    ' of the rational soul as incorporeal drew on Aristotelian-Thomist psychology. This attempted'
    ' synthesis between Cartesian mechanism and Aristotelian soul theory reflects the difficulty'
    ' of the philosophical situation for Catholic natural philosophers in the seventeenth century:'
    ' mechanism threatened to reduce everything including the soul to material causation, but'
    ' the mechanical philosophy was also the most intellectually powerful natural philosophy'
    ' available.</p>'
    '<p>The weapon-salve controversy in which Digby was a central figure illustrates the'
    ' stakes of the debate between mechanist and occult natural philosophy. Digby\'s <i>Discourse'
    ' touching the Cure of Wounds by the Powder of Sympathy</i> (1658) argued that the weapon-salve'
    ' operated through a natural mechanism: particles from the wounded person\'s blood, dried on'
    ' the weapon, served as a vehicle for carrying the healing influence back to the wound through'
    ' the air. This was an attempt to give a mechanistic account of what appeared to be a magical'
    ' operation — action at a distance — by positing a material medium. The account was rejected'
    ' by strict mechanists who denied that particles could carry healing influence across a distance,'
    ' and by religious critics who saw it as at best misguided natural magic.</p>'
    '<p>Digby\'s connection to the French and continental natural philosophical community is'
    ' historically important: through his years in Paris, he knew Descartes, Mersenne, Thomas'
    ' White, and other Catholic philosophers who were developing alternatives to both Scholastic'
    ' Aristotelianism and Protestant experimental philosophy. His social position as an English'
    ' Catholic aristocrat in exile connected him to networks that were differently positioned'
    ' from those of Boyle, Newton, or the Royal Society, and his natural philosophy reflected'
    ' the concerns of that different position. The "chymistry" practiced in his circle was'
    ' different in emphasis and context from the Helmontian-Boylean tradition, and his'
    ' engagement with it illustrates the breadth of the social world in which early modern'
    ' chymical inquiry was conducted.</p>'
)

BOSTOCKE_2 = (
    '<h2>Paracelsianism and English Medical Reform</h2>'
    '<p>Bostocke\'s text appeared in 1585, the same year as the first major English translation'
    ' of Paracelsus and during a decade when Paracelsian medicine was becoming a serious force'
    ' in English medical culture. The controversy between Galenic and Paracelsian medicine in'
    ' England involved not only questions about the safety and efficacy of chemical medicines'
    ' (particularly mineral preparations involving antimony, mercury, and arsenic) but also'
    ' questions about religious authority: Galenic medicine was associated with classical pagan'
    ' learning, while Paracelsian medicine was associated with a form of Christian natural'
    ' philosophy that drew authority from divine creation rather than Greek philosophical'
    ' tradition.</p>'
    '<p>Bostocke\'s argument that Paracelsian medicine was ancient — not a sixteenth-century'
    ' innovation but a recovery of primordial divine knowledge — drew on the same <i>prisca'
    ' sapientia</i> framework that [LINK:marsilio-ficino] and [LINK:giovanni-pico-della-mirandola]'
    ' had used to legitimize Hermetic and Platonic learning in Florence. Applied to medicine,'
    ' this framework positioned Paracelsian practice as more ancient and more authoritative'
    ' than Galenic medicine, reversing the normal direction of the authority argument. Charles'
    ' Webster\'s analysis of the relationship between Paracelsianism, Puritanism, and'
    ' the development of natural philosophy in seventeenth-century England provides the'
    ' context for understanding Bostocke\'s contribution within the longer story of English'
    ' medical and natural philosophical reform.</p>'
    '<p>The specific chemical knowledge in Bostocke\'s text — his defense of Paracelsian'
    ' medicines, his account of the tria prima, his explanations of how chemical preparations'
    ' worked — reflects the actual state of Paracelsian pharmacology in Elizabethan England.'
    ' His work was part of a generation of English engagement with Paracelsian thought that'
    ' prepared the ground for [LINK:george-starkey]\'s more sophisticated synthesis of'
    ' Helmontian chymistry in the following century. The trajectory from Bostocke\'s defensive'
    ' Paracelsianism to Starkey\'s experimental laboratory program — both concerned with chemical'
    ' medicine, both positioned against Galenic orthodoxy — illustrates the development of'
    ' English medical chymistry over the period between Elizabeth and the Interregnum.</p>'
)

NORTON_2 = (
    '<h2>Alchemical Practice and the Tradition of Failure</h2>'
    '<p>Samuel Norton\'s career illustrates a pattern that runs through the history of'
    ' alchemical practice: sustained investment of time, money, and intellectual effort in'
    ' the pursuit of a goal that remains perpetually unrealized, combined with theoretical'
    ' sophistication and genuine chemical knowledge accumulated through the pursuit.'
    ' His accounts of laboratory work — including periods of relative success with specific'
    ' preparations and then disappointment when the final step proved elusive — are consistent'
    ' with the broader record of early modern laboratory practice, in which specific chemical'
    ' achievements (purification of mercury, preparation of antimony compounds, extraction of'
    ' mineral acids) were real and reproducible even when the ultimate goal remained unreached.</p>'
    '<p>The continuity between Norton\'s work and the English alchemical tradition represented'
    ' by [LINK:george-ripley] is visible in his engagement with the twelve-gate structure and'
    ' with the symbolic vocabulary of English verse alchemy. His claimed descent from Thomas'
    ' Norton — the fifteenth-century author of the <i>Ordinal of Alchemy</i> — positioned him'
    ' within a dynasty of English alchemical practitioners, whether or not the genealogy was'
    ' accurate. This kind of claimed lineage was characteristic of alchemical culture, in which'
    ' the authority of practice was often established through claimed connection to earlier'
    ' masters: as [LINK:george-starkey] constructed the Philalethes persona as an adept who'
    ' had achieved the Stone, Norton constructed himself as an heir to a proven English tradition.</p>'
    '<p>Norton\'s texts were preserved in the Ashmole collection at the Bodleian Library and'
    ' cited by [LINK:elias-ashmole] in <i>Theatrum Chemicum Britannicum</i>. This preservation'
    ' through Ashmole\'s editorial project is characteristic of how English alchemical tradition'
    ' was transmitted: through manuscript collections assembled by antiquarian-practitioners who'
    ' understood themselves as conserving a national cultural heritage as well as a practical'
    ' knowledge tradition. Jennifer Rampling\'s scholarship on the English alchemical tradition'
    ' provides the scholarly context for understanding Norton\'s place within it.</p>'
)

BACKHOUSE_2 = (
    '<h2>Transmission and the Social World of English Alchemy</h2>'
    '<p>The social world of English alchemy in the mid-seventeenth century in which Backhouse'
    ' operated was a network of gentlemen, scholars, physicians, and practitioners connected by'
    ' manuscript exchange, correspondence, and personal instruction. This network overlapped'
    ' substantially with the circles that would produce the Royal Society in 1660, with the'
    ' difference that the alchemical dimension was more explicit and less apologetic. The same'
    ' figures who corresponded about chymical matters — Boyle, Ashmole, Samuel Hartlib, and'
    ' others — were also corresponding about experimental natural philosophy and natural history,'
    ' and the boundaries between these pursuits were not yet fixed.</p>'
    '<p>Backhouse\'s role as a transmitter of alchemical knowledge through personal instruction'
    ' rather than through printed texts reflects the persistence of the craft-model of'
    ' knowledge transmission in seventeenth-century English alchemy. Even as printed alchemical'
    ' texts proliferated and became more widely available, the most valued knowledge —'
    ' the secret of the Stone itself — was understood to require direct personal transmission'
    ' from an adept to a trusted student. This model of transmission connected Backhouse\'s'
    ' English country culture to the international tradition of master-pupil alchemy going'
    ' back to the Arabic and medieval Latin traditions.</p>'
    '<p>The diary evidence for Backhouse\'s communication to Ashmole — the specificity of the'
    ' date, the language of "opening himself," the framing of the transmission as occurring on'
    ' what Backhouse feared might be his deathbed — illustrates the emotional and personal'
    ' dimensions of alchemical transmission that the published texts necessarily elide. The'
    ' history of alchemy as a social practice, not just as a textual tradition, requires'
    ' attending to these personal dimensions: the relationships of trust and instruction, the'
    ' anxieties about secrecy and disclosure, the sense of responsibility for a precious'
    ' heritage that shaped how practitioners related to each other and to the tradition they'
    ' were carrying forward.</p>'
)

HOMBERG_2 = (
    '<h2>Chemical Research at the Palais Royal</h2>'
    '<p>Homberg\'s laboratory at the Palais Royal was one of the best-equipped chemical'
    ' research facilities in France in the late seventeenth and early eighteenth centuries.'
    ' The Duke of Orléans, Philippe II, was a serious amateur of natural philosophy and'
    ' provided resources — the large burning lens acquired from the Académie, chemical'
    ' equipment and materials, laboratory space — that allowed Homberg to pursue experiments'
    ' beyond what was available to most academic chemists. The research they conducted'
    ' together included investigations of combustion, the weight of light (Homberg believed'
    ' that light had physical weight and could be captured in chemical reactions), the'
    ' phosphorescence of various substances, and the chemistry of specific mineral compounds.'
    ' This work was serious natural philosophical inquiry conducted in a patronage context'
    ' that was becoming obsolete as institutional chemistry in the Académie became the'
    ' primary site of chemical research.</p>'
    '<p>Homberg\'s position as both an Académie member and a private laboratory researcher'
    ' for an aristocratic patron reflects the transitional character of early eighteenth-century'
    ' French chemical culture. The Académie, founded in 1666, had established institutional'
    ' chemistry as a recognized pursuit with state support; but the older model of the court'
    ' alchemist working in a private laboratory under aristocratic patronage persisted alongside'
    ' the new institutional model, supported by the interest of patrons like the Duke of'
    ' Orléans who had the resources to maintain serious research facilities.</p>'
    '<p>Lawrence Principe has analyzed Homberg\'s chemical work in the context of French'
    ' chymistry in the early modern period, demonstrating that his investigations were conducted'
    ' within a framework that still retained connections to the older chymical tradition —'
    ' particularly in his interest in the weight of light and in the Paracelsian-influenced'
    ' account of fire as a material element — while also engaging with the newer quantitative'
    ' and analytical approaches that would characterize eighteenth-century chemistry. His'
    ' career thus straddles the transition that [LINK:georg-ernst-stahl]\'s phlogiston theory'
    ' was simultaneously organizing on the theoretical side.</p>'
)

WOHLER_2 = (
    '<h2>The Giessen-Gottingen Tradition</h2>'
    '<p>Wöhler\'s career was embedded in the institutional transformation of German chemistry'
    ' in the early nineteenth century. He trained with [LINK:jons-jacob-berzelius] in Stockholm,'
    ' where he absorbed the rigorous analytical approach that Berzelius had developed for'
    ' determining atomic weights and chemical composition. He then worked at Göttingen from'
    ' 1836, where his laboratory became one of the centers of German analytical and organic'
    ' chemistry alongside [LINK:justus-von-liebig]\'s laboratory at Giessen. The competition'
    ' and collaboration between Wöhler and Liebig — including their famous synthesis of'
    ' benzoic acid and their work on organic radicals — exemplifies the collaborative'
    ' and competitive dynamics that drove the rapid development of organic chemistry in'
    ' nineteenth-century Germany.</p>'
    '<p>His relationship to the broader question of what chemistry had replaced — and what'
    ' it had inherited from alchemy — is implicit in his work rather than explicit. The'
    ' urea synthesis demonstrated that organic compounds were not fundamentally different'
    ' from inorganic ones in terms of the chemical reactions that could produce them; this'
    ' was a contribution to the ongoing process of removing limits on what chemistry could'
    ' accomplish that had been going on since [LINK:antoine-lavoisier]\'s overthrow of'
    ' phlogiston. Each such removal of a limit — whether the limit of matter conservation'
    ' (Lavoisier), the limit of element immutability (electrochemistry), or the limit of'
    ' organic-inorganic separation (Wöhler) — was a step in the direction of the kind of'
    ' fundamental material transformation that alchemists had long claimed was possible.'
    ' That chemistry achieved these transformations through quite different methods than'
    ' alchemy proposed does not change the structural parallel between alchemical aspirations'
    ' and chemical accomplishments.</p>'
)

BERZELIUS_2 = (
    '<h2>Electrochemistry and Dualistic Theory</h2>'
    '<p>Berzelius\'s major theoretical contribution to early nineteenth-century chemistry was'
    ' his electrochemical dualistic theory, which proposed that all chemical compounds were'
    ' the result of the electrical attraction between positively and negatively charged'
    ' components. Developed in response to Davy\'s electrochemical decomposition of alkalis,'
    ' the theory was highly productive for analyzing the compositions of inorganic compounds'
    ' but proved less adequate for organic chemistry, where the same elements could form'
    ' compounds with very different properties. The limitations of his dualistic theory'
    ' contributed to the development of the concept of chemical types by subsequent chemists'
    ' including Charles Gerhardt and August Laurent, eventually displacing the dualistic'
    ' framework that Berzelius had built.</p>'
    '<p>Berzelius\'s systematic determination of atomic weights — he determined them for'
    ' most of the known elements to a precision that confirmed the law of definite proportions'
    ' established by Proust — was a monument of quantitative analytical chemistry. This'
    ' work required the same combination of systematic procedure, careful weighing, and'
    ' attention to sources of error that characterized the best early modern laboratory'
    ' practice, including the weighing traditions that [LINK:william-newman] has identified'
    ' as connecting seventeenth-century chymistry to the medieval alchemical tradition of'
    ' systematic record-keeping exemplified by [LINK:george-starkey]\'s laboratory notebooks.</p>'
)

LIEBIG_2 = (
    '<h2>The Research Laboratory as Institution</h2>'
    '<p>Liebig\'s institutional innovation — the research-oriented teaching laboratory, where'
    ' students learned chemistry by conducting supervised research rather than by attending'
    ' lectures and demonstrations — became the model for chemistry education worldwide in the'
    ' second half of the nineteenth century. His laboratory at Giessen attracted students from'
    ' across Germany, Britain, America, and other countries; his students, trained in systematic'
    ' analytical procedure and imbued with his vision of the practical applications of organic'
    ' chemistry, spread the research laboratory model to their own institutions.</p>'
    '<p>The connection between Liebig\'s research laboratory and the early modern chymical'
    ' laboratory is institutional as well as epistemological. The idea that chemistry was'
    ' a practical art that required hands-on laboratory experience — rather than a purely'
    ' theoretical discipline learned from books — was continuous from the earliest alchemical'
    ' practitioners through the seventeenth-century chymical tradition to the nineteenth-century'
    ' institutional chemistry. What changed was the scale (many students simultaneously),'
    ' the social organization (hierarchical academic rather than master-apprentice), and the'
    ' epistemological framework (quantitative analysis and atomic theory rather than the'
    ' Philosophers\' Stone and transmutation) rather than the fundamental commitment to'
    ' laboratory work as the site of chemical knowledge production.</p>'
)

BERTHELOT_2 = (
    '<h2>Continuist Historiography and Its Critics</h2>'
    '<p>The continuist framework that Berthelot established in his historical writing was'
    ' not simply wrong but incomplete: it was right that alchemical practice accumulated'
    ' practical chemical knowledge and that this knowledge was transmitted to and incorporated'
    ' into modern chemistry. Where it went wrong was in treating this transmission as a'
    ' simple linear development — alchemy as primitive chemistry — rather than as a more'
    ' complex process of selective appropriation in which some aspects of alchemical practice'
    ' (specific procedures, specific substances, the weighing tradition) were absorbed while'
    ' others (the transmutational goal, the animate cosmology, the symbolic-allegorical'
    ' language) were discarded.</p>'
    '<p>[LINK:william-newman] and [LINK:lawrence-principe]\'s revision of the continuist'
    ' narrative accepts the continuity of laboratory practice while challenging the'
    ' developmental framing: the early modern chymists they study were not primitive chemists'
    ' gradually approaching modern chemistry but sophisticated practitioners working within'
    ' a different but internally coherent framework, and the transition to modern chemistry'
    ' involved a discontinuity — the Chemical Revolution of Lavoisier — that Berthelot\'s'
    ' continuism tended to underplay. The result is a richer and more accurate historical'
    ' picture than either pure continuism (Berthelot) or pure discontinuism (the older'
    ' view that chemistry was founded by Lavoisier from scratch) provides.</p>'
)

COPENHAVER_2 = (
    '<h2>Scholarship and the Hermetic Tradition</h2>'
    '<p>Copenhaver\'s <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>'
    ' (2015) is the most comprehensive scholarly survey of the Western magical tradition'
    ' available in English, covering the ancient, medieval, and early modern periods with'
    ' equal scholarly rigor. The book\'s treatment of the relationship between natural magic,'
    ' demonic magic, and the development of natural philosophy provides the conceptual'
    ' framework for understanding how early modern practitioners like [LINK:john-dee],'
    ' [LINK:henry-cornelius-agrippa], and [LINK:marsilio-ficino] understood their own work.'
    ' His analysis of the debates within the magical tradition about the distinction between'
    ' natural magic (operating through the properties of things) and demonic magic (operating'
    ' through the invocation of spiritual powers) is essential for understanding the philosophical'
    ' context in which alchemy was practiced and legitimized.</p>'
    '<p>His edition of Pico della Mirandola\'s <i>Oration on the Dignity of Man</i> and'
    ' his numerous articles on Renaissance magic and philosophy have contributed to the'
    ' scholarly understanding of the intellectual tradition within which alchemical practice'
    ' found its philosophical legitimation. The broader significance of his work for the'
    ' history of alchemy lies in his insistence on reading the primary texts — the Hermetic'
    ' dialogues, Ficino\'s natural magic, Pico\'s Kabbalah — with the same critical'
    ' philosophical attention that one would bring to Plato or Aristotle, rather than'
    ' treating them as evidence of Renaissance credulity or irrationalism. This stance'
    ' is methodologically parallel to the approach of [LINK:william-newman] and'
    ' [LINK:lawrence-principe] in the history of alchemy proper.</p>'
)

HOBBES_2 = (
    '<h2>Legacy in the History of Science</h2>'
    '<p>Hobbes\'s relevance for the history of alchemy lies primarily in what his natural'
    ' philosophy excluded. His thoroughgoing materialism — every mental event is a motion'
    ' of material particles, every causal relation is a mechanical impact — left no room'
    ' for the "active principles" that [LINK:isaac-newton] sought in his alchemical research,'
    ' no room for the "vital spirits" that van Helmontian chymistry invoked, and no room'
    ' for the sympathies and correspondences that organized Paracelsian natural magic.'
    ' In this sense, Hobbes represents the limiting case of the mechanical philosophy:'
    ' a vision of nature from which everything that alchemical natural philosophy valued'
    ' had been definitively excluded.</p>'
    '<p>The fact that this vision failed to prevail — that Newton\'s active principles,'
    ' Boyle\'s corpuscular chemistry with its unexplained properties, and eventually'
    ' Lavoisier\'s oxygen and caloric retained aspects of active powers that Hobbes\'s'
    ' strict mechanism denied — illustrates the limits of pure mechanism as a framework'
    ' for natural philosophy. The history of natural philosophy between Hobbes and Lavoisier'
    ' can be read as the negotiation of a middle position between pure mechanism (Hobbes)'
    ' and the animate natural philosophy of the alchemical tradition (van Helmont, Paracelsus),'
    ' a negotiation that was not resolved in favor of either extreme but in a series of'
    ' provisional syntheses that eventually produced the disciplinary framework of modern'
    ' chemistry and physics.</p>'
)

GOETHE_2 = (
    '<h2>Legacy for the History of Natural Philosophy</h2>'
    '<p>Goethe\'s natural philosophy — his insistence on the organic wholeness of nature,'
    ' on the inadequacy of mathematical reductionism for understanding living phenomena, on'
    ' the validity of qualitative observation alongside quantitative measurement — represents'
    ' the most sophisticated modern critique of the mathematical-mechanical natural philosophy'
    ' that displaced the Hermetic-alchemical tradition. His <i>Farbenlehre</i>, despite its'
    ' scientific failure to refute Newton\'s color theory, articulated a phenomenological'
    ' approach to natural inquiry that influenced Wittgenstein, Heidegger, and later'
    ' philosophers of science who questioned the epistemological foundations of mathematical'
    ' reductionism.</p>'
    '<p>For the history of alchemy, Goethe matters as a sophisticated post-Enlightenment'
    ' figure who maintained that the alchemical vision of nature as animate, qualitative,'
    ' and subject to art was not simply superseded by modern science but continued to'
    ' raise genuine questions about the limits of the mechanistic-mathematical approach.'
    ' His engagement with alchemical texts and symbolism in <i>Faust</i> was not nostalgic'
    ' or naive but an attempt to use the resources of the alchemical tradition to articulate'
    ' a vision of nature and human knowledge that he found inadequately represented in'
    ' the natural science of his era. Whether this vision was ultimately right or wrong,'
    ' his engagement with it was intellectually serious and historically consequential for'
    ' the tradition of German Naturphilosophie that shaped nineteenth-century biology,'
    ' chemistry, and philosophy of nature.</p>'
)

SHAKESPEARE_2 = (
    '<h2>The Theatrical Context of Alchemical Reference</h2>'
    '<p>The theatrical context of Shakespeare\'s alchemical references is important for'
    ' understanding their cultural significance. The Elizabethan and Jacobean theater was'
    ' a mass medium reaching audiences across social classes, and the cultural assumptions'
    ' embedded in theatrical language reflect what playwrights could assume their audiences'
    ' recognized. That Shakespeare could use alchemical imagery — the transformation of base'
    ' metal to gold as a metaphor for love, aging, or political change; the alchemist as a'
    ' figure of aspiration and deception — and expect his audiences to follow the reference'
    ' suggests that alchemical language was widely recognized in late sixteenth- and early'
    ' seventeenth-century London.</p>'
    '<p>The specific alchemical content that Shakespeare engages with — the transformation'
    ' of metals, the Philosophers\' Stone, the homunculus — connects his work to the'
    ' intellectual tradition that [LINK:william-newman] and [LINK:lawrence-principe]'
    ' have analyzed in its more technical dimensions. That the same symbolic vocabulary was'
    ' simultaneously being used in [LINK:george-ripley]\'s verse alchemy, in the practical'
    ' notebooks of practitioners like Starkey, and in the literary productions of Shakespeare'
    ' and Jonson illustrates the cultural breadth of alchemical reference in early modern'
    ' England: alchemy was not a marginal or subcultural phenomenon but part of the'
    ' mainstream cultural vocabulary that educated Londoners shared regardless of their'
    ' specific relationship to laboratory practice.</p>'
)

DANTE_2 = (
    '<h2>Dante and Medieval Scientific Culture</h2>'
    '<p>Dante\'s engagement with natural philosophy extends beyond his treatment of alchemy.'
    ' The <i>Divine Comedy</i>\'s cosmological framework — the Ptolemaic spheres, the elements,'
    ' the relationship between celestial motion and terrestrial change — is a comprehensive'
    ' statement of the Aristotelian-Thomist natural philosophy of his era, presented in poetic'
    ' form for an educated Italian lay audience. His treatment of mineral generation, of the'
    ' relationship between the Sun\'s influence and the growth of metals in the earth, and of'
    ' the corruption and generation of material substances all reflect the same natural'
    ' philosophical tradition that medieval Latin alchemical writers were engaging with.</p>'
    '<p>The <i>Inferno</i>\'s punishment of alchemists is thus not a dismissal of natural'
    ' philosophical inquiry into material transformation but a moral judgment about the'
    ' specific practice of counterfeiting: the falsification of metals, not the investigation'
    ' of natural processes, is what Dante condemns. This distinction — between the legitimate'
    ' inquiry into natural transformation (which Dante\'s natural philosophy engaged with)'
    ' and the fraudulent production of imitations (which he condemned) — reflects the'
    ' mainstream scholastic position on alchemy that had been articulated since the thirteenth'
    ' century: the possibility of genuine transmutation was an open natural philosophical'
    ' question; fraudulent imitation of precious metals was morally and legally wrong.'
    ' Dante\'s poem is thus evidence for the complexity of medieval educated attitudes'
    ' toward alchemy: neither simple endorsement nor simple dismissal, but a nuanced'
    ' position that distinguished inquiry from fraud.</p>'
)

def load_all():
    conn = sqlite3.connect(DB)

    for slug, extra in [
        ('christian-rosencreutz', ROSENCREUTZ_2),
        ('democritus', DEMOCRITUS_2),
        ('meister-eckhart', MEISTER_2),
        ('muhammad-ibn-umail', MUHIB_2),
        ('gerbert-of-aurillac', GERBERT_2),
        ('kenelm-digby', DIGBY_2),
        ('robert-bostocke', BOSTOCKE_2),
        ('samuel-norton', NORTON_2),
        ('william-backhouse', BACKHOUSE_2),
        ('wilhelm-homberg', HOMBERG_2),
        ('friedrich-wohler', WOHLER_2),
        ('jons-jacob-berzelius', BERZELIUS_2),
        ('justus-von-liebig', LIEBIG_2),
        ('marcellin-berthelot', BERTHELOT_2),
        ('brian-copenhaver', COPENHAVER_2),
        ('thomas-hobbes', HOBBES_2),
        ('johann-goethe', GOETHE_2),
        ('william-shakespeare', SHAKESPEARE_2),
        ('dante-alighieri', DANTE_2),
    ]:
        app(conn, slug, extra)

    conn.commit()
    conn.close()
    print('\n=== Done ===')

if __name__ == '__main__':
    load_all()
