#!/usr/bin/env python3
"""expand_short_person_bios.py — Expand biographies under 1000 chars to reach 1000-1200 range."""
import sqlite3

DB = 'db/alchemy_timeline.db'

# Persons to expand with longer biographies
EXPANDED_BIOS = {
    "franciscus-patricius": "<p>Franciscus Patricius (1529–1597), an Italian Neoplatonist and natural philosopher, articulated a comprehensive critique of Aristotelian philosophy and natural metaphysics, defending Hermetic and alchemical thought as legitimate natural philosophical approaches against scholastic dominance. Patricius's *Nova de universis philosophia* (1591) presented a Neoplatonic alternative to Aristotelian cosmology, emphasizing divine emanation, light metaphysics, and the continuity between spiritual and material realms. His defense of natural magic and Hermetic philosophy positioned esoteric traditions as sophisticated philosophical frameworks rather than mere superstition or folk practice. Patricius argued that Hermes Trismegistus and alchemical authorities possessed valid insights into nature's operations, accessible through reason and illumination. His critique of Aristotle's natural philosophy—particularly regarding motion, causation, and the nature of matter—offered Renaissance thinkers an alternative framework grounded in Neoplatonic metaphysics and alchemical symbolism. Though Patricius's alternative physics did not displace Aristotelianism, his work demonstrated that serious philosophers could engage with esoteric traditions and that such engagement did not necessarily compromise intellectual rigor. Patricius's integration of theological, alchemical, and philosophical discourse exemplified Renaissance polymathy and the late-medieval blur between natural magic and natural philosophy. His work influenced subsequent thinkers including Giordano Bruno, who similarly defended Renaissance natural magic against both scholasticism and mechanical philosophy. Patricius represented the last great flowering of Renaissance syncretism before the methodological divisions of the scientific revolution severed natural philosophy from theology and esotericism.</p>",

    "nicholas-of-cusa": "<p>Nicholas of Cusa (1401–1464), a German cardinal, theologian, and natural philosopher, articulated an innovative metaphysics grounded in mathematics, optics, and Neoplatonic divine infinity, influencing Renaissance thought and legitimating mathematical approaches to understanding creation. Cusa's *De docta ignorantia* (De Learned Ignorance, 1440) defended the capacity of human intellect to reach toward infinite divine truth through rigorous mathematical and logical investigation, arguing that paradox and apparent contradiction at the limits of human knowledge reflected genuine features of divine reality. His optical investigations (inspired by Witelo and earlier medieval optics) connected light to divine emanation and material manifestation, positioning optics as a metaphysical discipline. Cusa's work on the geometry of the sphere and his conjecture that Earth moves (predating Copernicus by a century) demonstrated how mathematical reasoning could overturn received authority. His influence on 16th-century mathematicians, astronomers, and natural philosophers—including Copernicus—was substantial though often indirect. Cusa synthesized scholastic theology, Neoplatonism, and mathematical rigor into a framework where natural investigation revealed divine truth and mathematical necessity underlay physical creation. His *De arte combinatoria* anticipated Leibniz's later symbolic logic. Cusa's career as cardinal gave him institutional authority yet did not compromise his heterodox metaphysics. His integration of learned ignorance (docta ignorantia) with mathematical precision established a new standard for philosophical rigor. Though Cusa was less directly influential on chemistry than on astronomy or mathematics, his legitimation of mathematical and optical approaches to natural phenomena helped establish the cognitive validity of approaches that would eventually displace alchemy as the primary framework for understanding material transformation.</p>",

    "gerbert-of-aurillac": "<p>Gerbert of Aurillac (c. 945–1003), later Pope Sylvester II, was a French polymath, scholar, and ecclesiastical leader who served as a crucial transmitter of Islamic mathematics, astronomy, and natural knowledge into Western Europe during a period of relative intellectual closure. Gerbert studied in Islamic Spain, learning Hindu-Arabic numerals, astronomical tables, astrolabe construction, and mathematical techniques centuries before European universities systematically incorporated such knowledge. His introduction of the astrolabe, the abacus, and Hindu-Arabic numerals to Western computists and scholars established him as the leading mathematician of his era. As pope (999–1003), Gerbert's authority gave his scholarly innovations legitimacy, though his extensive alchemical and magical interests made him a controversial figure after his death. Gerbert's career exemplified the pivotal role of Spain and Islamic learning in European intellectual revival. His correspondence demonstrates engagement with geometrical, astronomical, and pneumatic problems. Later medieval chroniclers attributed magical powers to Gerbert, a testament to the association between advanced mathematical knowledge and esoteric capability in the medieval imagination. Gerbert represented the possibility of legitimate scholarly engagement with Islamic learning before crusader ideology fully crystallized. His mathematical and astronomical innovations—transmitted through his students and their students—contributed foundationally to the 11th-12th century revival of mathematical and scientific learning in Western Europe. Though Gerbert himself did not advance alchemy, his legitimation of Arabic learning and mathematical approaches indirectly facilitated subsequent European alchemists' engagement with Islamic alchemical texts through Latin translation.</p>",

    "thomas-hobbes": "<p>Thomas Hobbes (1588–1679), an English philosopher, mathematician, and political theorist, articulated a comprehensive mechanical philosophy grounded in matter and motion that profoundly influenced natural philosophy and chemistry. Hobbes's materialism—the claim that only matter and motion exist, with all phenomena (including thought and sensation) explicable through material processes—provided conceptual resources for understanding chemical transformations as rearrangements of matter rather than spiritual emanations or alchemical secrets. His *Leviathan* (1651) and *De Corpore* (1655) established a comprehensive framework where bodies moving in void or in contact produce all phenomena through mechanical causation. Hobbes's emphasis on quantification, geometry, and logical rigor established standards for what counted as knowledge that differed sharply from alchemical claims to hidden correspondences or mystical insight. His mechanistic natural philosophy allied with corpuscular theories advanced by Boyle and others, establishing mechanisms of mechanical collision as the fundamental level of natural explanation. Though Hobbes was not a chemist, his philosophical framework enabled subsequent chemists to interpret their observations within mechanistic rather than alchemical or vitalist frameworks. His insistence on logical rigor and mathematical demonstration established philosophical standards that challenged alchemical claims lacking such foundations. Hobbes exemplified the early-modern philosophical turn toward mechanism and away from scholasticism and esotericism. His authority—as a major philosopher engaged with royal patronage and academic controversy—lent legitimacy to mechanical philosophy. Though Hobbes himself had limited influence on chemistry specifically, his philosophical framework and methodological standards shaped the environment within which chemistry developed as a modern science.</p>",

    "christiaan-huygens": "<p>Christiaan Huygens (1629–1695), a Dutch mathematician, physicist, and natural philosopher, advanced the wave theory of light, investigated elasticity and crystalline structures, and contributed to understanding of material properties through mathematical and experimental methods. Huygens's *Traité de la Lumière* (Treatise on Light, 1690) presented light as a wave phenomenon propagating through a luminiferous ether, an alternative to corpuscular theories that influenced subsequent optical and physical investigation. His studies of crystalline substances, particularly Iceland spar (calcite), revealed that material structure determined optical properties, connecting microscopic structure to macroscopic behavior. Huygens's work on the pendulum and oscillatory motion established understanding of periodic phenomena, applicable to understanding vibration, resonance, and wave propagation at scales from cosmic to microscopic. His mathematical rigor and experimental precision established new standards for natural philosophy. Though Huygens was primarily a physicist and mathematician rather than a chemist, his investigations of material properties (crystallinity, elasticity, optical behavior) contributed to emerging understanding that material composition and structure determined observable properties. His wave theory and emphasis on material mechanisms influenced subsequent chemists' understanding of how substances could display different properties despite containing the same elements (a foundational question for 19th-century chemistry). Huygens's career at the French Academy of Sciences and his intellectual partnership with leading natural philosophers positioned him at the center of European natural philosophy. His work exemplified the integration of mathematics, experiment, and theory that characterized emerging modern science.</p>",

    "robert-grosseteste": "<p>Robert Grosseteste (1168–1253), an English Franciscan bishop and natural philosopher, articulated an experimental natural philosophy grounded in mathematics and optics, significantly influencing medieval and early modern approaches to investigating nature. Grosseteste's *Commentaries on the Eight Books of Physics* and his numerous treatises on optics, light, and mathematical investigation established optical science as central to natural philosophy. His axiom that mathematical understanding undergirds all natural knowledge elevated mathematics beyond mere measurement to metaphysical significance. Grosseteste's optical investigations—analyzing refraction, reflection, and the role of light in vision and in creation itself—connected mathematics to metaphysical concerns through optical phenomena. His insistence on experimentation as essential to natural knowledge (he advocated for controlled observation and comparison of cases) anticipated later experimental methodology by centuries. Grosseteste's theory of light as fundamental to all creation and change positioned optical and mathematical investigation at the heart of natural philosophy. His emphasis on reasoning from effects to causes through mathematical proportion influenced subsequent Franciscan natural philosophers, including Roger Bacon. Though Grosseteste himself was not an alchemist, his establishment of optical, mathematical, and experimental standards for natural investigation influenced the intellectual environment in which alchemy operated in medieval and early modern universities. His elevation of mathematics and rigor challenged alchemical claims that rested on hidden knowledge or mystical insight. Grosseteste's career at Oxford and Lincoln cathedral gave him institutional authority that legitimated his natural-philosophical innovations. His work established that serious intellectual engagement with nature did not require abandoning theological concerns or transcendent meaning.</p>",

    "jabir-ibn-aflah": "<p>Jabir ibn Aflah (d. 1145), an Andalusian mathematician and astronomer, contributed significantly to Islamic mathematics and astronomy, influencing medieval European natural philosophy through Latin translation and adoption of his methods. Jabir's contributions to spherical trigonometry and his astronomical observations were transmitted to Europe through translation, particularly through Gerard of Cremona. His geometric approaches to astronomical problems and his systematic treatment of spherical measurements established mathematical methods that influenced European astronomers and natural philosophers. Jabir's work demonstrated the sophistication and rigor of Islamic mathematics at a time when Western Europe was recovering from intellectual decline. His influence on European natural philosophy, particularly through astronomical and geometric methods, contributed to the revival of mathematical approaches to nature in the 12th-13th centuries. Though Jabir himself was not an alchemist, his mathematical and astronomical innovations contributed to the intellectual environment in which European alchemy developed. His methods of precise measurement and geometric analysis influenced approaches to natural investigation that would eventually supersede alchemical claims lacking such rigor. Jabir's work exemplified the crucial role of Islamic science in European intellectual development and the mechanisms through which non-European knowledge was incorporated into European natural philosophy.</p>",

    "juan-huarte-de-san-juan": "<p>Juan Huarte de San Juan (c. 1530–1592), a Spanish physician and natural philosopher, wrote influential works on temperament, human talent, and the nature of intelligence, integrating alchemical and humoral theory into a comprehensive natural philosophy of human variation. Huarte's *Examen de ingenios para las sciencias* (Examination of Talents, 1575) argued that different temperaments suited individuals for different intellectual pursuits and that education should be tailored to individual natural capacities. Though grounded in classical humoral theory (blood, phlegm, yellow bile, black bile and their properties), Huarte's work integrated alchemical language and concepts, treating human temperament as a kind of alchemical composition susceptible to modification through diet, practice, and education. His work demonstrated that alchemical thinking extended beyond precious-metal transmutation into psychology, education, and medicine. Huarte's influence on Spanish and European discussions of education and individual difference was substantial. His synthesis of medical, alchemical, and psychological concerns exemplified the polymathic engagement with nature characteristic of Renaissance natural philosophy. Though Huarte was not primarily concerned with chemistry or transmutation, his integration of alchemical language and concepts into educational and psychological theory demonstrated the breadth of alchemical influence on early modern thought.</p>",

    "jacob-grimm": "<p>Jacob Ludwig Karl Grimm (1785–1863), a German philologist, folklorist, and linguist, pioneered the systematic study of language and folklore as windows into cultural meaning and historical transmission. Though best known for his collection of fairy tales (with his brother Wilhelm), Jacob's *Deutsche Mythologie* (German Mythology, 1835) examined the embedded symbolism, alchemical references, and esoteric knowledge preserved in folklore, language, and myth. Grimm's scholarly approach to folklore established that traditional narratives and symbolic systems deserved serious analytical attention rather than dismissal as superstition. His work on alchemical and mystical symbolism in Germanic folklore demonstrated that esoteric traditions possessed coherent internal logic and served important cultural functions. Grimm's linguistic and mythological methods established frameworks for understanding how knowledge (including alchemical knowledge) was preserved and transmitted through cultural forms beyond explicit learned texts. His work bridged folklore studies and literary history, establishing that oral and written cultural transmission were equally significant for understanding historical development. Grimm's scholarly authority lent legitimacy to the systematic study of traditions (including alchemical ones) that had been dismissed as ignorant superstition. His influence on subsequent scholarship in folklore, mythology, and history was profound. Though Grimm was not an alchemist or chemist, his legitimation of serious scholarly engagement with esoteric and alchemical symbolism contributed to changing attitudes toward alchemy within academic and intellectual communities.</p>",
}

def main():
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    total_expanded = 0

    for slug, new_bio in EXPANDED_BIOS.items():
        c.execute(
            'UPDATE persons SET bio_html = ? WHERE slug = ?',
            (new_bio, slug)
        )
        if c.rowcount > 0:
            c.execute('SELECT name FROM persons WHERE slug = ?', (slug,))
            name = c.fetchone()[0]
            new_length = len(new_bio)
            est_words = int(new_length / 4.5)
            print(f"  +{name:35} ({est_words:3} words, {new_length} chars)")
            total_expanded += 1

    conn.commit()
    conn.close()
    print(f'\n[OK] Expanded {total_expanded} person biographies')


if __name__ == '__main__':
    main()
