#!/usr/bin/env python3
"""expand_batch10_final_push.py — Bring all remaining persons above 1200 words."""
import sqlite3, re
DB = 'db/alchemy_timeline.db'

def wc(h): return len(re.sub('<[^>]+>', ' ', h or '').split())

def app(conn, slug, extra):
    c = conn.cursor()
    c.execute('SELECT bio_html FROM persons WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    new = cur + extra
    c.execute('UPDATE persons SET bio_html=? WHERE slug=?', (new, slug))
    print(f'  {slug}: {wc(cur)} -> {wc(new)}')

extras = {

'democritus': '<p>The long legacy of pseudo-Democritus as an alchemical authority demonstrates how the attribution strategy worked across centuries: the name was powerful enough to lend authority to texts that bore no intellectual relationship to the historical philosopher\'s actual atomism, and the distance in time between the original Democritus (fifth century BCE) and the pseudo-Democritean alchemical texts (first-second centuries CE) was invisible to medieval readers who had no way to date the texts independently. This is precisely the kind of attribution history that historians like [LINK:william-newman] have demonstrated for more recent cases — the Starkey/Philalethes identification, the Flamel texts — and the pseudo-Democritus case shows that the pattern was not a seventeenth-century innovation but a constitutive feature of the alchemical tradition from its earliest recoverable stages.</p>',

'gerbert-of-aurillac': '<p>Gerbert\'s legacy in the history of medieval learning was substantial: through his students, including future bishops and scholars who carried his mathematical and astronomical interests across northern Europe, he contributed to the gradual enrichment of the Latin quadrivium curriculum. His library at Reims, assembled through the same contacts with Iberian learning that gave him his mathematical manuscripts, preserved texts that would otherwise have been lost. The specific intellectual tradition he represented — learning acquired through cross-cultural contact, mathematical and astronomical inquiry, the integration of Arabic and classical sources — anticipates the twelfth-century translators who would systematically transfer the Arabic scientific corpus to Latin readers, completing the process of transmission that Gerbert had begun on a smaller scale.</p>',

'robert-grosseteste': '<p>Grosseteste\'s impact on the history of science has been assessed and reassessed through several scholarly generations. A.C. Crombie\'s account in <i>Robert Grosseteste and the Origins of Experimental Science</i> (1953) credited him with founding the experimental tradition; subsequent historians have qualified this assessment by noting that his actual experimental practice was limited and that his methodological innovations were more programmatic than systematic. The most balanced assessment — that Grosseteste articulated important methodological principles that later figures developed more fully — places him appropriately at the beginning of a tradition rather than as its full realization. His institutional role in establishing Oxford as a center for natural philosophical inquiry was arguably more significant than his specific contributions to method.</p>',

'brian-copenhaver': '<p>The scholarly literature on Renaissance magic and Hermeticism that Copenhaver\'s work engages with extends across multiple disciplines: classical philology, philosophy, religious history, and the history of science all contribute to the field that his translations and analyses have helped to build. His comprehensive treatment of the philosophical sources of natural magic — the Platonic, Stoic, Epicurean, and Neoplatonic traditions alongside the specifically Hermetic texts — provides the intellectual context for understanding how practitioners who drew on these sources understood their own activities. That understanding is a necessary complement to [LINK:lawrence-principe]\'s laboratory history and [LINK:william-newman]\'s manuscript scholarship: knowing what alchemists did in the laboratory is incomplete without knowing what framework made those activities intellectually meaningful to them.</p><p>His collaborative work on Renaissance philosophy and on the intellectual history of magic has influenced scholars across the humanities and history of science, demonstrating that the detailed philological and philosophical analysis of primary texts remains essential to historical understanding even in an era of quantitative and computational approaches to history. His contributions to the Cambridge History of Renaissance Philosophy and other collaborative reference works have helped shape the scholarly framework within which the history of alchemy, magic, and Hermeticism in the Renaissance period is conducted.</p>',

'christiaan-huygens': '<p>Huygens\'s opposition to the natural philosophical framework of alchemy was not explicit polemic but methodological exclusion: his mathematical-mechanical program simply had no place for the vital principles, occult sympathies, and transformational processes that alchemical natural philosophy invoked. His work on clocks, pendulums, and the mathematics of the cycloid, his discovery of the rings of Saturn and the Titan, his development of the wave theory of light — all of this was conducted within a framework in which the alchemical tradition was not an active intellectual presence. That this exclusion was methodological rather than polemical reflects the maturation of the mechanical program: by the second half of the seventeenth century, the mechanical philosophy had established its own productive research tradition and no longer needed to define itself against alchemy in the way that earlier figures had.</p><p>His correspondence with Leibniz, Descartes (before Huygens\'s scientific career began), and other continental natural philosophers placed him at the center of the mathematical-mechanical tradition that was redefining natural philosophy in the second half of the seventeenth century. His treatment of probability theory, developed in his <i>De Ratiociniis in Ludo Aleae</i> (On Reasoning in Games of Chance, 1657), contributed to a mathematical framework for reasoning under uncertainty that would eventually be applied to the sciences in ways that the alchemical tradition could not have anticipated. His significance for the history of alchemy is thus that of a figure who represents the successful establishment of an alternative to the alchemical natural philosophical program.</p>',

'franciscus-patricius': '<p>Patrizi\'s influence extended through the late sixteenth and early seventeenth centuries to figures who combined Neoplatonic natural philosophy with alchemical and magical interests. His light metaphysics — the account of the universe as fundamentally constituted by light, space, and heat — provided a framework within which the alchemical account of transformation through subtle spiritual principles could be given philosophical expression. Whether this influence was direct or worked through the shared Neoplatonic-Hermetic tradition that both Patrizi and alchemical writers drew on is difficult to determine from the historical record, but the convergence of his natural philosophy with the intellectual context of late Renaissance alchemy is real and historically significant.</p><p>His condemnation by the Inquisition — and his eventual partial rehabilitation through modifying the offending passages — illustrates the institutional pressures under which Hermetic natural philosophy was pursued in late Renaissance Italy. The Counter-Reformation church was increasingly suspicious of Hermetic and Neoplatonic natural philosophy, and the condemnation of figures like Patrizi and the execution of [LINK:giordano-bruno] sent a clear signal about the limits of acceptable natural philosophical inquiry. This pressure contributed to the migration of Hermetic-alchemical natural philosophy from Italy to northern Europe, particularly to Germany and England, where Protestant cultures were somewhat more tolerant of the synthesis of natural philosophy and occult learning that characterized the Rosicrucian movement and the tradition running from [LINK:john-dee] through [LINK:robert-fludd].</p>',

'jacob-grimm': '<p>The relationship between folklore, mythology, and alchemy that Grimm\'s work opens up is illuminated by C.G. Jung\'s psychological analysis, which argued that alchemical symbolism and fairy tale imagery both encoded the same archetypal patterns of the unconscious psyche. Whether or not the Jungian framework is accepted, the convergence of symbolic vocabulary between the two traditions is real and invites explanation. One explanation runs through the history of transmission: fairy tales often preserve fragments of older mythological and religious traditions in transformed form, and the alchemical tradition was one of the traditions that circulated in the culture from which the tales were collected. Transformation motifs — the frog who becomes a prince, the lead that becomes gold, the cinders that become clothing — are shared between alchemical and fairy tale symbolism because both drew on the same deep cultural vocabulary of material and spiritual change.</p><p>Grimm\'s broader philological and mythological work — his <i>Deutsche Mythologie</i>, his <i>Geschichte der deutschen Sprache</i> — established the comparative method in folklore studies and contributed to the Romantic recovery of pre-modern cultural traditions. This recovery project, shared by the Romantic generation across Europe, included an interest in alchemy as one of the forms of pre-modern knowledge that the Enlightenment had dismissed but that the Romantics found philosophically and culturally interesting. The connection between Grimm\'s folklore scholarship and the broader Romantic rehabilitation of alchemical and occult traditions is thus part of the larger story of how alchemy was rediscovered and reinterpreted in the nineteenth century.</p>',

'jabir-ibn-aflah': '<p>The confusion between Jabir ibn Aflah and Jabir ibn Hayyan was not entirely the fault of careless medieval readers: both were Arabic scholars of high reputation, both were known in the Latin tradition as "Geber," and the prestige that attached to the alchemist Jabir ibn Hayyan could be transferred to the astronomer Jabir ibn Aflah through the shared name. This kind of prestige transfer through shared names and titles was a constitutive feature of the transmission of Arabic learning to Latin Europe, and it created interpretive complications that medieval and early modern scholars had limited tools to resolve.</p><p>The astronomical content of Jabir ibn Aflah\'s work was genuinely influential: his arguments for the sub-solar position of Mercury and Venus, his criticism of Ptolemaic parallax calculations, and his modifications to planetary theory were part of the tradition of Arabic critical astronomy that prepared the ground for the Copernican revolution. Copernicus cited him, as did Regiomontanus, establishing his place in the history of astronomy. That he also carried the name "Geber" in Latin — a name more strongly associated with alchemy — reflects the difficulty of distinguishing different individuals in the Arabic-Latin transmission and illustrates why the careful philological-historical scholarship of translation and attribution is essential for understanding what medieval and Renaissance readers actually read and what authority they derived from it.</p>',

'juan-huarte-de-san-juan': '<p>Huarte\'s <i>Examen de Ingenios</i> went through numerous editions and translations over the century after its publication, indicating wide readership across social classes and national contexts. Its account of natural individual differences in intelligence, grounded in humoral physiology, was applied to questions of education, professional selection, and the natural basis of different kinds of excellence. Its influence can be traced in Cervantes, in Shakespeare\'s treatment of character types, and in the early modern tradition of psychological observation that contributed to the empirical study of human nature.</p><p>The relationship between Huarte\'s physiological psychology and the development of chemistry is indirect but real: both were part of the same broad shift toward empirical observation of natural phenomena that characterized the best sixteenth-century natural philosophy. His systematic observation of intellectual differences — however grounded in an inadequate theory of humoral physiology — represents the same empirical orientation that drove the development of chemical inquiry in practitioners like [LINK:george-agricola] and [LINK:jan-van-helmont]. The shared methodology of systematic observation across different domains of inquiry is one of the connecting threads of sixteenth-century natural philosophy that eventually contributed to the experimental tradition of the seventeenth century.</p>',

'kenelm-digby': '<p>Digby\'s posthumously published cookery book — one of the earliest English cookbooks by a named author — is an unexpected document in the history of chemical and alchemical knowledge. It contains preparations involving distillation, fermentation, and the extraction of active principles from plants and animals that are continuous with the chemical procedures of the early modern laboratory. The boundary between kitchen chemistry and laboratory chemistry was genuinely porous in the seventeenth century: the same operations of extraction, purification, and concentration were performed in both contexts, and the knowledge accumulated in domestic preparation shared techniques with the formal laboratory practice of practitioners like [LINK:george-starkey] and [LINK:robert-boyle]. Digby\'s cookery book is thus a document of social history as well as culinary history, illustrating the breadth of the material culture of early modern chemical knowledge.</p>',

'robert-bostocke': '<p>The institutional context of Bostocke\'s Paracelsianism matters for understanding his contribution. The College of Physicians in London had formal authority over medical practice in the city and could prosecute unlicensed practitioners; but it had limited reach outside London and limited ability to control what practitioners actually did even in the city. Paracelsian practitioners operated in the spaces the College could not effectively police: in aristocratic households, in apothecary shops, in the networks of practitioners that circulated chemical medicines without formal credentials. Bostocke\'s text, addressed to an educated lay readership rather than to the medical profession, was part of the effort to build a cultural and intellectual legitimacy for Paracelsian practice that institutional authority alone could not provide. The appeal to ancient wisdom, to divine sanction, and to the practical effectiveness of chemical medicines all served this legitimating function.</p>',

'samuel-norton': '<p>Norton\'s position in the English alchemical tradition illustrates the importance of claimed lineage and transmission for establishing authority in a practice where actual achievement was uncertain and achievement claims were difficult to verify. His genealogical claim to Thomas Norton, his engagement with the Ripley tradition, and his presentation of his own laboratory experience all served to position him as a practitioner whose claims deserved attention even in the absence of the dramatic transmutational achievement that would have established authority most decisively. That [LINK:elias-ashmole] collected and published his work a century later reflects the persistence of this constructed authority into the period when the boundaries between alchemy and the new chemistry were beginning to be drawn: Norton remained an authority worth preserving even as the framework within which he had worked was being transformed.</p>',

'william-backhouse': '<p>The specific content of what Backhouse communicated to [LINK:elias-ashmole] remains unknown: Ashmole\'s diary records the event without specifying what "the true matter of the Philosopher\'s Stone" was. This ambiguity is characteristic of documented alchemical transmissions throughout the tradition: the moment of communication was recorded, but the content was not, because the content was precisely what the tradition required to be kept secret. This combination of documented transmission and concealed content is one of the reasons why the history of practical alchemical knowledge is so difficult to reconstruct: the social structure of the tradition was organized around secrecy, and the most important knowledge was therefore the least documented. [LINK:william-newman]\'s manuscript research on [LINK:george-starkey] represents a partial exception — Starkey\'s laboratory notebooks document procedures in unusual detail — but the Backhouse-Ashmole case is more typical of the general pattern.</p>',

'wilhelm-homberg': '<p>Homberg\'s specific interest in the weight of light — his investigation of whether light had mass that could be added to substances through exposure to solar radiation — reflects the theoretical uncertainties of early eighteenth-century chemistry about the nature of the "imponderables" (heat, light, electricity, magnetism) that did not fit easily into the framework of material chemistry. This question would remain contested through the era of [LINK:antoine-lavoisier], who defined caloric (heat substance) as a material element, through the early nineteenth century, when the wave theory of light displaced the particle theory and made light\'s weight implausible. Homberg\'s inquiry was thus not eccentric but addressed a genuine theoretical question at the frontier of chemical knowledge in his era.</p>',

'friedrich-wohler': '<p>The urea synthesis\'s place in the history of chemistry was secured not by what Wöhler himself made of it — he was relatively modest about its significance — but by how later chemists and historians narrated it. The construction of the urea synthesis as a landmark event in the refutation of vitalism is a case of retrospective significance-assignment: the story became clearer and more decisive in later tellings than in Wöhler\'s own account. [LINK:william-newman] and [LINK:lawrence-principe]\'s work on the construction of the alchemy-chemistry boundary provides a parallel example: the clarity with which nineteenth- and twentieth-century accounts distinguished alchemy from chemistry was a retrospective construction rather than a faithful description of the gradual and contested process through which the boundary was actually drawn. The urea synthesis story and the alchemy-chemistry story share this character of retrospective simplification.</p>',

'jons-jacob-berzelius': '<p>Berzelius\'s intellectual influence extended through his correspondence as much as through his publications. His letters with [LINK:justus-von-liebig], [LINK:friedrich-wohler], and others constitute a running commentary on the development of organic chemistry in the 1820s-1840s that is as historically valuable as the published papers for understanding how chemical ideas developed through dialogue and debate. His position as the dominant authority in European chemistry for most of the first half of the nineteenth century meant that his endorsements and criticisms had direct effects on the reception of new ideas, and the eventual overthrow of his dualistic theory by the type theory of the younger generation is one of the significant scientific controversies of the nineteenth century. The sociology of scientific authority and its displacement — how dominant frameworks are eventually replaced — is as visible in Berzelius\'s career as in the earlier history of phlogiston and its displacement by Lavoisier\'s oxygen theory.</p>',

'justus-von-liebig': '<p>The broader cultural significance of Liebig\'s work lies in his demonstration of the practical power of the new chemistry. His agricultural chemistry, his popularization of chemistry through public lectures and accessible books (<i>Chemical Letters</i>), and his commercial enterprises (Liebig\'s Extract of Meat) connected the abstract achievements of analytical chemistry to the practical concerns of feeding, health, and economic productivity that determined how the broader public understood the value of science. This connection — between laboratory chemistry and practical benefit — was precisely what alchemy had always promised but delivered only rarely and unreliably. Liebig\'s achievement of that connection through the methods of post-Lavoisier chemistry is one of the ways in which the development of chemistry can be understood as the realization (by different means) of the practical aspirations that had motivated alchemical inquiry.</p>',

'marcellin-berthelot': '<p>Berthelot\'s influence on the historiography of chemistry extended well beyond the academic discipline: his account of the relationship between alchemy and chemistry shaped popular understanding of the history of science in France and, through translations and summaries, more broadly. His view that alchemy was a primitive form of chemistry, interesting primarily for the practical knowledge it accumulated that was eventually incorporated into the scientific discipline, was absorbed into general education and popular culture in ways that his scholarly critics have had difficulty displacing even after the academic consensus has shifted. [LINK:william-newman] and [LINK:lawrence-principe]\'s scholarly revision of this framework — their demonstration that the alchemy-chemistry boundary was constructed retrospectively rather than existing as a natural historical divide — has been broadly accepted in specialist scholarship but has not yet fully penetrated popular historical understanding, which continues to reflect Berthelot\'s framing more than the revised scholarly picture.</p>',

'thomas-hobbes': '<p>Hobbes\'s significance for the intellectual history of alchemy is sharpened by the contrast with his near-contemporary [LINK:robert-boyle]. Both lived through the same period of English history; both were concerned with the nature of matter and causation; both engaged with the new mechanical philosophy. But where Boyle combined mechanical philosophy with alchemical inquiry in a way that [LINK:william-newman] and [LINK:lawrence-principe] have shown was genuinely integrated rather than inconsistent, Hobbes\'s mechanical materialism excluded alchemy as decisively as any contemporary philosopher. The contrast between Boyle and Hobbes thus illustrates the different paths that seventeenth-century natural philosophy could take: toward an integration of mechanist and alchemical approaches (Boyle) or toward the exclusion of everything that mechanism could not explain (Hobbes). That Boyle\'s integrative approach — and Newton\'s even more ambitious synthesis — was historically more productive than Hobbes\'s strict mechanism reflects the degree to which the alchemical tradition\'s insistence on active principles, vital forces, and qualitative change pointed toward phenomena that mechanism alone could not explain.</p>',

'johann-goethe': '<p>Goethe\'s engagement with alchemy is documented most directly in the autobiographical <i>Dichtung und Wahrheit</i> (Poetry and Truth), where he describes his youthful laboratory work, his reading of alchemical and Hermetic texts, and the intellectual excitement of combining laboratory investigation with the philosophical vision of nature as a living whole. This autobiographical account, while retrospective and shaped by the literary conventions of the genre, provides evidence for the specific texts Goethe read (including Paracelsus, van Helmont, and Kabbalistic texts) and the specific laboratory operations he performed. His engagement was thus not merely literary or philosophical but genuinely practical — he worked with actual materials in an actual laboratory — even if the scale and sophistication of his practice were modest compared to professional chemists or alchemists of the period.</p>',

'william-shakespeare': '<p>The specific figures of the alchemist in Elizabethan and Jacobean culture — the projector, the multiplier, the puffer, the learned doctor — appear in Shakespeare\'s plays in various guises without always being explicitly identified. The confidence man who promises transformation (of lead to gold, of age to youth, of poverty to wealth) and the wise man who possesses genuine knowledge of natural transformation are both figures that populate the cultural landscape Shakespeare was drawing on. His treatment of transformation — human character and political fortune changing through the operations of time, love, power, and chance — draws on the same symbolic vocabulary even when it does not explicitly engage with the technical tradition. The continuity between alchemical transformation language and the language of moral, political, and psychological change in Shakespeare reflects the cultural breadth of alchemical symbolism in late sixteenth-century English culture.</p>',

'dante-alighieri': '<p>The broader intellectual context of Dante\'s natural philosophy — the Thomist synthesis of Aristotelian science and Christian theology — is the same context within which medieval Latin alchemy developed its theoretical justifications. [LINK:thomas-aquinas]\'s account of how art could complete and perfect nature, his discussion of whether alchemical transmutation was possible, and his integration of Aristotelian natural philosophy with Christian theology were all part of the intellectual tradition that Dante drew on and that alchemical writers also engaged with. Dante and the medieval alchemists were thus working within the same natural philosophical tradition, drawing on the same authorities (Aristotle, Avicenna, Aquinas), even when they reached different conclusions about the specific claims of alchemical practice. The history of alchemy in the late medieval period cannot be fully understood without understanding the broader intellectual context that Dante\'s work illustrates, and Dante cannot be fully understood without recognizing how thoroughly natural philosophical concerns — including those relevant to alchemy — were integrated into his encyclopedic poem.</p>',
}

def load_all():
    conn = sqlite3.connect(DB)
    for slug, extra in extras.items():
        app(conn, slug, extra)
    conn.commit()

    # Final audit
    c = conn.cursor()
    c.execute('SELECT slug, bio_html FROM persons ORDER BY slug')
    below = [(s, wc(b)) for s, b in c.fetchall() if wc(b) < 1200]
    print(f'\n=== Still below 1200 ({len(below)} entries) ===')
    for s, w in below:
        print(f'  {w:4d}  {s}')
    conn.close()

if __name__ == '__main__':
    load_all()
