#!/usr/bin/env python3
"""expand_batch9_final_persons.py — Final pass to bring all persons above 1200 words."""
import sqlite3, re
DB = 'db/alchemy_timeline.db'

def wc(h): return len(re.sub('<[^>]+>', ' ', h or '').split())

def app(conn, slug, extra):
    c = conn.cursor()
    c.execute('SELECT bio_html FROM persons WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    new = cur + extra
    c.execute('UPDATE persons SET bio_html=? WHERE slug=?', (new, slug))
    print(f'  {slug}: {wc(cur)} -> {wc(new)}')

extras = {

'christian-rosencreutz': (
    '<h2>Reception and Lasting Influence</h2>'
    '<p>The Rosicrucian manifestos had an enormous immediate response: contemporary publications'
    ' numbered in the hundreds as writers tried to contact the brotherhood, attack it, defend it,'
    ' or decode its meaning. No actual members of the brotherhood were ever identified, and the'
    ' question of whether the brotherhood existed continued to generate debate. René Descartes'
    ' reportedly searched for the Rosicrucians during his travels in Germany and failed to find'
    ' them; his failure was interpreted as evidence of their perfect secrecy. The absence of'
    ' verifiable members became a defining feature of the tradition: the brotherhood was'
    ' simultaneously everywhere (every learned reformer might secretly be a member) and nowhere'
    ' (no one could be definitively identified as one).</p>'
    '<p>The long-term influence of the Rosicrucian tradition extended through the seventeenth'
    ' and eighteenth centuries into Freemasonry (which incorporated Rosicrucian degrees in'
    ' the eighteenth century), into nineteenth-century occultism (the Hermetic Order of the'
    ' Golden Dawn drew on Rosicrucian material), and into modern esoteric culture. The'
    ' Rosicrucian Antiquus Mysticus Ordo Rosae Crucis (AMORC) and similar organizations'
    ' present themselves as heirs to the historical brotherhood, though their claims to'
    ' historical continuity with the early seventeenth-century texts are not supported by'
    ' scholarly evidence. For the history of alchemy, the Rosicrucian movement represents'
    ' a moment at which alchemical symbolism was mobilized for a broad program of social,'
    ' religious, and intellectual reform — a moment that illustrates both the cultural power'
    ' of alchemical language and its susceptibility to uses far removed from laboratory practice.</p>'
),

'democritus': (
    '<h2>Atomism and Early Modern Chemistry</h2>'
    '<p>The revival of ancient atomism in the seventeenth century — through the publication'
    ' of Lucretius\'s <i>De Rerum Natura</i>, the philosophical work of Pierre Gassendi, and'
    ' Descartes\'s corpuscular mechanics — brought the historical Democritus back into the'
    ' center of natural philosophical debate. [LINK:robert-boyle]\'s corpuscular chemistry,'
    ' which proposed that the properties of material substances derived from the size, shape,'
    ' and motion of the corpuscles composing them, drew on this atomist revival while also'
    ' drawing on the practical laboratory tradition of chymistry. The combination in Boyle\'s'
    ' work of ancient atomist philosophy with early modern laboratory practice is one of the'
    ' defining features of seventeenth-century natural philosophy.</p>'
    '<p>The pseudo-Democritean alchemical texts thus stand at the beginning of a tradition'
    ' that eventually connected to the atomist natural philosophy that bore Democritus\'s name'
    ' through an entirely different intellectual genealogy. When Boyle invoked Democritean'
    ' atomism in his corpuscular chemistry, he was engaging with the ancient philosopher whose'
    ' name also labeled the oldest Greek alchemical texts — a coincidence that is historically'
    ' accidental but philosophically significant, since it means that the name "Democritus"'
    ' appears at both the beginning of the laboratory tradition (pseudo-Democritus, c. first'
    ' century CE) and at the theoretical foundation of the corpuscular philosophy that'
    ' eventually gave chemistry its conceptual framework (historical Democritus, through'
    ' the atomist revival of the seventeenth century).</p>'
    '<p>The specific interest of the pseudo-Democritean texts for historians of ancient alchemy'
    ' is their relationship to the Hellenistic Egyptian cultural context that Garth Fowden and'
    ' others have analyzed for the Hermetic texts. The same milieu of Greco-Egyptian religious'
    ' and cultural synthesis that produced the Hermetica produced the earliest alchemical texts,'
    ' and the pseudo-Democritus stands as evidence for the antiquity and breadth of this'
    ' synthetic tradition. Understanding the origins of Greek alchemy requires understanding'
    ' the specific social and intellectual conditions of Roman Egypt, and Matteo Martelli\'s'
    ' work on the pseudo-Democritean corpus is among the most important recent contributions'
    ' to that understanding.</p>'
),

'meister-eckhart': (
    '<p>The specific philosophical concepts that Eckhart developed — the <i>Funklein</i>'
    ' (little spark) of the soul that remains united with God even when the soul is embodied,'
    ' the <i>Abgeschiedenheit</i> (detachment) through which the soul empties itself to'
    ' receive the divine, the <i>Geburt Gottes</i> (birth of God) in the soul as the'
    ' culmination of spiritual practice — all use the language of interior transformation'
    ' that runs parallel to the language of exterior transformation in alchemy. Whether'
    ' practitioners who engaged with both traditions drew explicit connections between them'
    ' or simply operated in a shared symbolic environment is a question that historians of'
    ' spirituality and alchemy are still exploring. What is clear is that the shared vocabulary'
    ' of purification, transformation, death, and renewal was available to anyone who moved'
    ' between the two traditions, and that several figures — [LINK:heinrich-khunrath], Jakob'
    ' Böhme, and others — explicitly connected them.</p>'
    '<p>Bernard McGinn\'s analysis of Eckhart in his <i>Mystical Thought of Meister Eckhart</i>'
    ' (2001) provides the scholarly foundation for his philosophical theology. Reiner'
    ' Schürmann\'s <i>Meister Eckhart: Mystic and Philosopher</i> (1978) explores his'
    ' relationship to German idealism and to the philosophy of being. The connection between'
    ' Eckhart and the alchemical tradition has been explored by Antoine Faivre in his'
    ' studies of Western esotericism, and by Stanton Linden in the context of English'
    ' alchemical literature. His place in the history of alchemy is that of a background'
    ' figure whose conceptual vocabulary shaped the spiritual dimensions of laboratory'
    ' practice without himself engaging with the laboratory.</p>'
),

'muhammad-ibn-umail': (
    '<h2>The Symbology of the Arabic Alchemical Tradition</h2>'
    '<p>Ibn Umail\'s approach to the earlier alchemical tradition reflects a broader'
    ' feature of Arabic alchemy in the Islamic Golden Age: the combination of systematic'
    ' classification and practical procedure with symbolic and allegorical interpretation.'
    ' The Arabic alchemical tradition had inherited from Greek alchemy both the laboratory'
    ' techniques and the symbolic language, and major practitioners worked across both'
    ' dimensions — al-Razi\'s practical classification coexisted with ibn Umail\'s symbolic'
    ' commentary. This dual character of Islamic alchemy — simultaneously practical and'
    ' interpretive — was transmitted to Latin Europe through translation and shaped the'
    ' character of medieval and early modern European alchemy.</p>'
    '<p>The specific doctrine of the "silvery water" (philosophical mercury) that ibn Umail'
    ' developed became one of the most influential concepts in the Latin alchemical tradition.'
    ' His identification of the philosophical mercury — the specially prepared form of'
    ' mercury that was the foundation of the alchemical work — with the "water that does'
    ' not wet the hands" (an untouchable yet active liquid principle) and with the union'
    ' of solar and lunar principles provided the symbolic vocabulary for the philosophical'
    ' mercury tradition that runs through [LINK:george-ripley], the pseudo-Lullian texts,'
    ' and eventually [LINK:george-starkey]\'s laboratory work on the "sophic mercury."'
    ' [LINK:william-newman] has analyzed this tradition in detail, demonstrating the'
    ' specific transmission routes through which ibn Umail\'s concepts arrived in'
    ' seventeenth-century English chymistry.</p>'
),

'gerbert-of-aurillac': (
    '<h2>Pope Sylvester II and the Boundary of Knowledge</h2>'
    '<p>Gerbert\'s elevation to the papacy as Sylvester II in 999 made him the first French'
    ' pope and placed him at the center of the Gregorian reform movement that was beginning'
    ' to transform the institutional church. His combination of intellectual achievement and'
    ' ecclesiastical authority was unusual even by the standards of educated prelates of the'
    ' period, and the contrast between his learning (gained partly from Muslim sources in'
    ' Spain) and his eventual position as head of Latin Christendom made the legend of the'
    ' magic-practicing pope particularly potent. The legend grew through the medieval period,'
    ' adding new elements — he had sold his soul, he had obtained forbidden books from an'
    ' Arab sorcerer, his brazen head gave prophecies — and was still being told and embellished'
    ' in the fifteenth and sixteenth centuries.</p>'
    '<p>Gerbert\'s career is relevant to the history of alchemy as a marker of the cultural'
    ' dynamics that shaped the reception of Arabic natural philosophy in Latin Europe. His'
    ' acquisition of mathematical and astronomical knowledge through contact with the'
    ' Iberian borderland was the precursor to the more systematic translation movement'
    ' of the twelfth century that brought Arabic alchemy to Latin readers. The legend that'
    ' attached to him — that his learning was diabolical, obtained through illicit contact'
    ' with Muslim (and implicitly occult) sources — anticipated the ambivalent reception'
    ' that would greet Arabic alchemy when it arrived in full. The very power of Arabic'
    ' natural knowledge — its mathematical sophistication, its medical and chemical claims —'
    ' made it theologically suspicious in a culture that associated such power with the devil.</p>'
    '<p>The rehabilitation of Gerbert by modern historians — who recognize him as a genuine'
    ' intellectual innovator rather than a diabolical magician — parallels the rehabilitation'
    ' of alchemical practitioners advanced by [LINK:william-newman] and [LINK:lawrence-principe]:'
    ' in both cases, dismissive legends have been replaced by careful historical analysis of'
    ' what the figures actually did and why it seemed extraordinary to their contemporaries.'
    ' Gerbert\'s extraordinary knowledge reflected access to an intellectual tradition that'
    ' most of his contemporaries lacked; alchemical practitioners\' extraordinary claims'
    ' reflected genuine laboratory achievements that most of their contemporaries could'
    ' not evaluate. The dynamic of knowledge that appears extraordinary to those without'
    ' the relevant background — and therefore susceptible to legendary accretion — is'
    ' common to both cases.</p>'
),

'kenelm-digby': (
    '<h2>Alchemy, Chemistry, and the Restoration Network</h2>'
    '<p>Digby\'s membership in the Royal Society from its foundation in 1660 placed him within'
    ' the institutional network that was establishing the social and epistemological norms for'
    ' the new experimental philosophy. His continued pursuit of alchemical inquiries alongside'
    ' this institutional membership illustrates the degree to which the boundary between'
    ' alchemy and legitimate experimental science was still permeable in the early Restoration'
    ' period. The Royal Society in its early years included members with significant alchemical'
    ' interests alongside the advocates of pure mechanical natural philosophy, and the gradual'
    ' clarification of that boundary — which Newman and Principe have analyzed as primarily a'
    ' rhetorical and social process rather than a straightforwardly epistemological one —'
    ' took place over decades rather than at a single moment.</p>'
    '<p>Digby\'s <i>Discourse touching the Vegetation of Plants</i>, presented to the Royal'
    ' Society in 1660 and published in 1661, attempts to explain plant growth through the'
    ' action of a niter-like aerial component — a concept that connects to [LINK:michael-sendivogius]\'s'
    ' spirit of niter and that anticipates in some respects the pneumatic chemistry that would'
    ' become dominant in the next century. His attempt to give a mechanistic account of this'
    ' aerial niter — explaining sympathetic action through material particles rather than'
    ' immaterial correspondences — reflects the intellectual pressures of the early Restoration'
    ' period, when natural philosophers were expected to give mechanical explanations of'
    ' phenomena that the Paracelsian-Helmontian tradition had explained through vital forces'
    ' and occult sympathies.</p>'
    '<p>His culinary legacy — the <i>Closet of the Eminently Learned Sir Kenelme Digby Kt.'
    ' Opened</i> (1669), published posthumously and containing recipes and household wisdom'
    ' including alchemically-inflected health preparations — connects the practical chemical'
    ' knowledge of the chymical tradition to the domestic sphere of food preparation and'
    ' medicine. This connection between laboratory chemistry and household chemical practice'
    ' is a dimension of the history of alchemy that [LINK:pamela-smith]\'s work on material'
    ' culture and workshop practice has helped scholars attend to: the knowledge of materials,'
    ' transformations, and chemical processes was distributed across many social settings'
    ' beyond the formal laboratory, and the boundary between the kitchen and the chemical'
    ' laboratory was not yet as sharp as it would later become.</p>'
),

'robert-bostocke': (
    '<h2>Chemical Medicine in Elizabethan Context</h2>'
    '<p>The Elizabethan medical context in which Bostocke wrote was characterized by significant'
    ' conflict between the established Galenic medical profession (organized through the College'
    ' of Physicians, founded 1518) and practitioners of Paracelsian and empirical medicine who'
    ' challenged Galenic authority. The College of Physicians controlled medical practice in'
    ' London and prosecuted unlicensed practitioners; Paracelsian practitioners were often at'
    ' odds with the College because their practices did not conform to Galenic standards and'
    ' their theoretical framework directly challenged Galenic humoralism.</p>'
    '<p>Bostocke\'s text entered this conflict on the Paracelsian side, arguing that the ancient'
    ' wisdom that Paracelsus had recovered was more authoritative than the Greek and Arabic'
    ' learning on which Galenic medicine was based. This claim — that Paracelsian medicine'
    ' was older than Galenism — drew on the <i>prisca sapientia</i> tradition and positioned'
    ' chemical medicine as recovering original divine knowledge rather than introducing novel'
    ' and dangerous practices. Charles Webster\'s analysis of Paracelsianism in England provides'
    ' the historical context for understanding Bostocke\'s contribution, which is significant'
    ' as an early English defense of the Paracelsian program rather than for its specific'
    ' chemical content.</p>'
    '<p>The transmission of Paracelsian medicine to England through Bostocke and other'
    ' early advocates prepared the ground for the more sophisticated engagement with'
    ' Helmontian chymistry in the following century. [LINK:george-starkey]\'s combination'
    ' of Helmontian natural philosophy with rigorous laboratory practice built on a'
    ' Paracelsian foundation that Bostocke and others had helped establish in English'
    ' medical culture. The development from Bostocke\'s defensive paracelsianism to'
    ' Starkey\'s experimental program illustrates how a tradition of practice can be'
    ' transformed through the engagement of practitioners with more rigorous experimental'
    ' standards while retaining continuity of theoretical orientation and practical focus.</p>'
),

'samuel-norton': (
    '<h2>Norton\'s Works and the Ripley Tradition</h2>'
    '<p>Norton\'s principal works — <i>Catholicon: or a New Art of Transmutation</i> and'
    ' <i>Mercurius Redivivus</i> — engage with the theoretical tradition inherited from'
    ' [LINK:george-ripley] while developing their own accounts of the alchemical process.'
    ' The claim of descent from Thomas Norton positioned Samuel Norton as an heir to'
    ' a two-generation English alchemical dynasty, establishing through genealogy the'
    ' kind of practical authority that the tradition otherwise established through claims'
    ' of achieved transmutation or direct teaching by an adept. Whether the claimed descent'
    ' was accurate — Thomas Norton was a real historical figure who wrote the <i>Ordinal'
    ' of Alchemy</i> in the fifteenth century — the strategy of claiming family connection'
    ' to an established practitioner reflects the importance of lineage and transmission'
    ' in alchemical culture.</p>'
    '<p>Norton\'s texts show familiarity with the laboratory as well as with the literary'
    ' tradition. His accounts of specific operations — the preparation of mercury, the'
    ' production of sulfurous principles, the stages of the work — reflect engagement with'
    ' actual laboratory practice rather than purely textual transmission. This combination'
    ' of practical engagement with literary tradition is characteristic of the best'
    ' sixteenth-century English alchemy, and it anticipates the more rigorous laboratory'
    ' orientation of [LINK:george-starkey]\'s chymistry in the following century.'
    ' [LINK:elias-ashmole]\'s inclusion of Norton in <i>Theatrum Chemicum Britannicum</i>'
    ' secured his place in the canon, and his works continued to be copied and referenced'
    ' by English alchemical practitioners through the seventeenth century.</p>'
    '<p>The context of Norton\'s life — the uncertainties of patronage pursuit, the'
    ' economic pressures of sustained laboratory work, the social dynamics of alchemical'
    ' practice in Elizabethan England — has been analyzed by Jennifer Rampling in her'
    ' work on the English alchemical tradition. Her research demonstrates the continuity'
    ' of the English tradition from Ripley through Samuel Norton and beyond, tracing'
    ' the transmission of texts, procedures, and theoretical concepts across the period.'
    ' Norton is thus a link in a chain of transmission rather than an isolated figure,'
    ' and understanding his significance requires understanding the broader tradition'
    ' of which he was part.</p>'
),

'william-backhouse': (
    '<h2>Antiquarian Alchemy and the Ashmolean Legacy</h2>'
    '<p>Backhouse\'s significance for the historiography of English alchemy lies primarily'
    ' in his relationship to [LINK:elias-ashmole], which provides one of the clearest'
    ' documented cases of the personal transmission of alchemical knowledge that was'
    ' otherwise difficult to document from the historical record. Most alchemical'
    ' master-student relationships are inferred from textual parallels, manuscript'
    ' connections, and circumstantial evidence; the Backhouse-Ashmole transmission'
    ' is documented in Ashmole\'s own diary with specific dates, places, and descriptions'
    ' of the communication, providing a rare first-person account of how alchemical'
    ' knowledge actually moved between practitioners in seventeenth-century England.</p>'
    '<p>Backhouse\'s own alchemical learning, and its specific content, are harder to'
    ' document. His claimed connection to the [LINK:john-dee] tradition — mediated through'
    ' figures whose identities and specific knowledge are uncertain — represents a genealogy'
    ' that, if accurate, would link mid-seventeenth-century English alchemy directly to'
    ' the Elizabethan magical-alchemical culture. Whether or not the genealogy is accurate,'
    ' the claim itself reflects the culture of transmission in which Backhouse operated:'
    ' authority derived from connection to established figures, and the value of a'
    ' communication depended partly on its claimed lineage.</p>'
    '<p>The materials in the Ashmole collection at the Bodleian Library — manuscripts that'
    ' came to Ashmole through Backhouse and other collectors — constitute a significant'
    ' portion of what survives of the English alchemical manuscript tradition. The'
    ' preservation of this material through Ashmole\'s collecting activity and its eventual'
    ' institutional deposit at Oxford has made it available for the scholarship of Jennifer'
    ' Rampling, Lauren Kassell, and others who have used it to reconstruct the social and'
    ' intellectual history of English alchemy. Backhouse is thus important not only as a'
    ' practitioner but as a conduit for the preservation of a documentary tradition that'
    ' would otherwise have been dispersed and lost.</p>'
),

'wilhelm-homberg': (
    '<h2>Chemistry and Patronage in the Regency</h2>'
    '<p>The Duke of Orléans\'s alchemical interests were part of a broader pattern of'
    ' aristocratic engagement with chemical inquiry in early eighteenth-century France.'
    ' The patronage culture that had supported alchemical research in the courts of Rudolf II,'
    ' the German princes, and French aristocrats persisted into the early Enlightenment period,'
    ' coexisting uneasily with the emerging institutional chemistry of the Académie Royale'
    ' des Sciences. Homberg\'s position at the intersection of these two modes of chemical'
    ' inquiry — the court laboratory and the learned academy — gave him resources and freedom'
    ' of inquiry that most academic chemists lacked but at the cost of serving the intellectual'
    ' interests of a patron who was interested in both the practical applications of chemistry'
    ' and its alchemical possibilities.</p>'
    '<p>Homberg\'s technical innovations in the Académie context included his work on'
    ' phosphorescence, his analysis of the composition of salts, and his investigations'
    ' of acids and their properties. This work contributed to the stock of chemical'
    ' knowledge that [LINK:georg-ernst-stahl]\'s phlogiston theory was organizing on'
    ' the theoretical side in the same period. The relationship between Homberg\'s practical'
    ' contributions and the theoretical developments of the early eighteenth century is'
    ' an example of how laboratory innovation and theoretical development proceed in'
    ' parallel rather than in a simple sequence, each informing and constraining the other.</p>'
    '<p>Lawrence Principe\'s research on Homberg and the Duke of Orléans has recovered'
    ' details of their alchemical collaboration that illuminate the persistence of alchemical'
    ' practice into the era of institutional chemistry. That a major figure in the Académie'
    ' Royale des Sciences was simultaneously conducting alchemical experiments in a private'
    ' ducal laboratory in the 1700s — the century of Enlightenment that is supposed to have'
    ' definitively separated science from alchemy — is a salutary reminder that the boundaries'
    ' historians draw for analytical purposes rarely correspond to clean historical transitions.'
    ' The "end of alchemy" was a much more gradual and contested process than the standard'
    ' narrative of the Chemical Revolution suggests.</p>'
),

'friedrich-wohler': (
    '<h2>Legacy in the History of Chemistry</h2>'
    '<p>Wöhler\'s place in the historical narrative of chemistry\'s relationship to alchemy'
    ' is emblematic rather than direct. He did not study alchemy, did not write about it,'
    ' and did not present his work in the context of the alchemical tradition. But his'
    ' synthesis of urea — and his broader career in organic chemistry — represents the'
    ' fulfillment, through entirely different methods, of one of alchemy\'s central aspirations:'
    ' the transformation of common substances into substances of different and valuable'
    ' character through art. That this fulfillment came through quantitative analytical'
    ' chemistry rather than through the sulphur-mercury theory, through university-based'
    ' research rather than individual patronage pursuit, and through published transparent'
    ' methodology rather than secret transmission does not change the structural parallel'
    ' between what alchemists sought and what chemists eventually achieved.</p>'
    '<p>The more historically direct connection is through Wöhler\'s training. He studied with'
    ' Berzelius, who represented the direct institutional lineage from Lavoisier\'s Chemical'
    ' Revolution. Lavoisier had worked in a tradition of French chemistry that had absorbed and'
    ' transformed the earlier chymical tradition. The specific laboratory procedures of weighing,'
    ' measuring, distilling, and analyzing substances that Wöhler practiced were refined from'
    ' procedures that [LINK:george-starkey] and [LINK:robert-boyle] had used two centuries'
    ' earlier, which were themselves developments of the Arabic and medieval Latin laboratory'
    ' traditions. The instruments were different, the theoretical framework was different,'
    ' but the basic commitment to laboratory-based investigation of material transformations'
    ' was continuous across the transition from alchemy to chemistry.</p>'
),

'jons-jacob-berzelius': (
    '<h2>Systematic Chemistry and Its Alchemical Legacy</h2>'
    '<p>Berzelius\'s systematic chemistry — his determination of atomic weights, his notation'
    ' system, his electrochemical dualistic theory — represented the consolidation of the'
    ' quantitative program that Lavoisier had inaugurated. The systematic determination of'
    ' what substances are composed of, and in what proportions, is a direct extension of'
    ' the weighing and measuring tradition that runs from [LINK:joseph-black]\'s fixed air'
    ' experiments through Lavoisier\'s conservation of mass to Berzelius\'s atomic weights.'
    ' The continuity of method across the supposed alchemy-chemistry boundary is precisely'
    ' what [LINK:william-newman] and [LINK:lawrence-principe] have identified in their'
    ' analysis of the seventeenth-century chymical tradition: the laboratory procedures'
    ' of careful weighing, systematic observation, and comparative analysis were continuous'
    ' from medieval alchemical practice through Berzelius\'s nineteenth-century chemistry.</p>'
    '<p>His discovery and naming of silicon, selenium, thorium, and cerium added substantially'
    ' to the periodic table in its pre-Mendeleev form. His systematic study of chemical'
    ' compounds and their compositions laid the groundwork for the development of structural'
    ' organic chemistry by the next generation. The laboratory culture he established'
    ' through his Stockholm laboratory and his extensive correspondence network — which'
    ' spread the analytical approach he had developed to chemists across Europe — had an'
    ' institutional impact comparable to what [LINK:justus-von-liebig]\'s Giessen laboratory'
    ' achieved for the next generation of German chemists.</p>'
),

'justus-von-liebig': (
    '<h2>Chemistry and Agriculture: Practical Consequences</h2>'
    '<p>Liebig\'s agricultural chemistry had immediate practical consequences that alchemy had'
    ' always promised but never delivered in the same systematic way. His demonstration that'
    ' plant growth required specific mineral nutrients — that agriculture could be transformed'
    ' by the application of chemical knowledge — fulfilled in a specific domain the alchemical'
    ' promise that mastery of nature\'s chemical processes would yield practical benefit.'
    ' The fertilizer industry that grew from his work transformed agricultural productivity'
    ' across Europe and eventually worldwide, arguably the largest-scale practical consequence'
    ' of chemical knowledge up to that point.</p>'
    '<p>His controversy with Justus Mulder over the nature of protein — a dispute that turned'
    ' on questions of organic chemical theory that were not fully resolved until later in the'
    ' century — illustrates the theoretical difficulties of nineteenth-century organic chemistry.'
    ' These difficulties were in some ways analogous to the theoretical difficulties of'
    ' early modern chymistry: a body of practical knowledge accumulating more rapidly than'
    ' the theoretical frameworks available to organize it, leading to competing theoretical'
    ' accounts and heated disputes among practitioners. The emotional intensity of chemical'
    ' controversies in the nineteenth century — Liebig was notorious for the ferocity of'
    ' his polemical writing — reflects the same dynamics of priority, authority, and'
    ' intellectual investment that characterized alchemical disputes in the early modern period.</p>'
),

'marcellin-berthelot': (
    '<h2>Thermochemistry and the Synthesis Program</h2>'
    '<p>Berthelot\'s chemical work was as significant as his historical work, though they are'
    ' rarely discussed together. His thermochemistry — the systematic measurement of the'
    ' heat produced by chemical reactions, using the bomb calorimeter he developed — established'
    ' a quantitative framework for understanding the energy changes involved in chemical'
    ' transformations. His synthesis program — his goal of producing all organic compounds'
    ' through synthesis from inorganic starting materials, without the intervention of living'
    ' organisms — extended the implications of [LINK:friedrich-wohler]\'s urea synthesis'
    ' to a general programmatic commitment to chemical synthesis as a research strategy.</p>'
    '<p>The combination of his chemical achievements with his historical work on alchemy is'
    ' historically characteristic of the French chemical tradition of the late nineteenth'
    ' century: the same rigor applied to understanding the history of the discipline was'
    ' applied to advancing it. His edition of the Greek alchemical texts was undertaken with'
    ' the same systematic analytical approach that he brought to thermochemistry — identifying'
    ' sources, comparing manuscripts, analyzing the chemical content — and while later scholars'
    ' have found his chemical interpretations of ancient procedures sometimes anachronistic,'
    ' his editorial work established standards for the field. [LINK:william-newman] and'
    ' [LINK:lawrence-principe]\'s revision of the historiographical framework he established'
    ' builds on but does not diminish the foundational importance of his editorial contributions.</p>'
),

'brian-copenhaver': (
    '<h2>Philosophy of Magic and Its Scholarly Analysis</h2>'
    '<p>Copenhaver\'s engagement with the philosophical dimensions of Renaissance magic,'
    ' Hermeticism, and natural philosophy has been sustained and methodologically rigorous.'
    ' His argument that the philosophers of the Renaissance took magic seriously as a'
    ' philosophical enterprise — not as superstition or popular credulity — parallels'
    ' the argument of [LINK:william-newman] and [LINK:lawrence-principe] that early modern'
    ' alchemists took their laboratory work seriously as natural philosophical inquiry.'
    ' Both arguments require resisting the retrospective imposition of modern disciplinary'
    ' categories on historical material that did not recognize those categories, and both'
    ' require attending to primary sources on their own terms rather than filtering them'
    ' through later frameworks.</p>'
    '<p>His work on the <i>Picatrix</i>, the influential medieval Arabic text on astral'
    ' magic translated into Latin in the thirteenth century, connects his scholarship on'
    ' philosophical magic to the specific texts that informed alchemical practitioners\''
    ' understanding of the relationship between celestial influences and material transformation.'
    ' The <i>Picatrix</i>\'s account of how stellar and planetary powers could be channeled'
    ' through material objects — stones, metals, plants, images — provided one of the theoretical'
    ' resources for understanding why alchemy, which worked with the same metals and minerals'
    ' that the <i>Picatrix</i> described as having planetary affinities, might be able to'
    ' transform materials by aligning them with their celestial principles.</p>'
    '<p>The broader significance of Copenhaver\'s scholarship for the history of alchemy'
    ' lies in his recovery of the philosophical seriousness of the Hermetic tradition that'
    ' provided alchemy\'s intellectual legitimation. Understanding alchemy historically'
    ' requires understanding not only what practitioners did in the laboratory but what'
    ' intellectual framework made those activities meaningful and authoritative. The'
    ' [LINK:hermes-trismegistus] of the <i>Corpus Hermeticum</i>, the [LINK:marsilio-ficino]'
    ' who translated those texts, and the tradition of natural magic that followed from that'
    ' translation are all part of the intellectual context that Copenhaver\'s scholarship'
    ' illuminates, and without which the laboratory tradition studied by Newman and Principe'
    ' cannot be fully understood.</p>'
),

'thomas-hobbes': (
    '<h2>The Mechanist Challenge to Alchemical Natural Philosophy</h2>'
    '<p>Hobbes\'s challenge to the theoretical foundations of alchemy was more fundamental'
    ' than the specific critiques that had been directed at alchemical practice throughout'
    ' the medieval and early modern periods. The scholastic critics had questioned whether'
    ' art could replicate the natural processes of metallic generation; the humanist satirists'
    ' had attacked the fraudulent practitioners who deceived credulous clients; the early'
    ' chemists had questioned whether transmutation was experimentally achievable. Hobbes'
    ' questioned whether the theoretical framework of alchemical natural philosophy —'
    ' with its vital principles, its occult sympathies, its animate nature — was'
    ' philosophically coherent at all. His reduction of all causation to motion and matter'
    ' left no explanatory role for the kinds of active, spiritual, or vital principles that'
    ' alchemical theory required.</p>'
    '<p>The failure of strict Hobbesian mechanism to prevail in seventeenth-century natural'
    ' philosophy is historically significant. [LINK:isaac-newton]\'s active principles,'
    ' [LINK:robert-boyle]\'s corpuscular properties that could not be reduced to size, shape,'
    ' and motion, and eventually Lavoisier\'s caloric (heat as a material substance) all'
    ' retained elements of explanatory irreducibility that Hobbes\'s strict mechanism denied.'
    ' This persistent need for something beyond strict mechanism in natural philosophical'
    ' explanation is part of what makes the history of the transition from alchemy to'
    ' chemistry more complex than the standard narrative of progressive rationalization suggests:'
    ' the concepts that mechanism was supposed to replace did not simply disappear but'
    ' transformed into new forms that continued to do explanatory work.</p>'
    '<p>Steven Shapin and Simon Schaffer\'s <i>Leviathan and the Air-Pump</i> (1985) is the'
    ' foundational text for understanding the Hobbes-Boyle controversy and its significance'
    ' for the history of scientific knowledge. Their analysis — which situates the dispute'
    ' within the political and social context of Restoration England and argues that the'
    ' epistemological norms of experimental science were established through social negotiation'
    ' rather than purely epistemic merit — has been enormously influential in science studies'
    ' and in the history of science, though it has also generated substantial critical response.'
    ' For the history of alchemy, the Hobbes-Boyle controversy is significant because it'
    ' marks the moment when the epistemological and ontological claims of the chymical'
    ' tradition were explicitly challenged by a competing natural philosophical framework.</p>'
),

'johann-goethe': (
    '<h2>Romantic Science and the Alchemical Inheritance</h2>'
    '<p>Goethe\'s natural philosophy was developed in explicit reaction against Newtonian'
    ' mechanism, and his engagement with alchemy was part of this reaction. He saw in'
    ' alchemy a tradition that had treated nature as alive, as qualitatively rich, as'
    ' subject to artistic participation and transformation rather than merely to mathematical'
    ' description. His <i>Farbenlehre</i>\'s polemic against Newton was not the work of an'
    ' incompetent amateur but of a sophisticated observer who had spent decades studying'
    ' color phenomena and who believed that Newton\'s prismatic analysis missed something'
    ' essential about the qualitative character of color experience. Whether he was right'
    ' or wrong about Newton\'s optics, his challenge identified a genuine tension between'
    ' quantitative mathematical description and qualitative phenomenological understanding'
    ' that remains philosophically contested.</p>'
    '<p>The German Romantic Naturphilosophie tradition that Goethe participated in alongside'
    ' figures like Schelling, Lorenz Oken, and Henrik Steffens sought to develop a science'
    ' that preserved the organic, teleological character of natural phenomena against the'
    ' mechanistic reductionism of Newtonian physics. This tradition drew explicitly on the'
    ' Paracelsian-Hermetic natural philosophy that alchemical practitioners had used, and'
    ' several Naturphilosophen engaged seriously with alchemical texts. The historical'
    ' connection between Romantic Naturphilosophie and the alchemical tradition has been'
    ' analyzed by historians including John Tresch, whose <i>The Romantic Machine</i> (2012)'
    ' situates Romantic science within the broader cultural history of nineteenth-century'
    ' natural philosophy.</p>'
),

'william-shakespeare': (
    '<h2>Alchemy in the Late Plays</h2>'
    '<p>Shakespeare\'s late plays — <i>The Winter\'s Tale</i>, <i>The Tempest</i>, <i>Cymbeline</i>'
    ' — deploy the language and imagery of transformation, resurrection, and the restoration'
    ' of what seemed lost in ways that are consistent with the alchemical symbolic tradition'
    ' even when they do not engage directly with alchemical practice. Hermione\'s restoration'
    ' to life at the end of <i>The Winter\'s Tale</i> — staged as the animation of a statue,'
    ' proceeding through stages from stasis to warmth to movement — follows the alchemical'
    ' sequence of mortification, fermentation, and animation that characterizes the'
    ' philosophical interpretation of the Great Work. Whether this is deliberate alchemical'
    ' symbolism or a convergent use of shared symbolic resources is a question that scholars'
    ' including Linda Woodbridge and Stanton Linden have debated.</p>'
    '<p>Prospero\'s magic in <i>The Tempest</i> draws on the tradition of learned natural'
    ' magic associated with [LINK:john-dee] and [LINK:henry-cornelius-agrippa] — the wise'
    ' man who commands natural forces through knowledge of their properties rather than through'
    ' demonic pacts. This positive version of magical knowledge, which Shakespeare presents'
    ' with sympathy though also with the tragic-comic awareness that the magician must'
    ' eventually renounce his art, reflects the Elizabethan and Jacobean cultural ambivalence'
    ' about natural magic and alchemy: powerful, potentially beneficial, but also dangerous,'
    ' corrupting, and ultimately requiring renunciation. The dramatic arc from magical'
    ' aspiration through power to renunciation mirrors the narrative of the alchemical'
    ' quest and its failure, as [LINK:geoffrey-chaucer] had analyzed it two centuries earlier.</p>'
),

'dante-alighieri': (
    '<h2>Medieval Scientific Culture and the Inferno\'s Falsifiers</h2>'
    '<p>The placement of alchemists in the eighth circle of Hell alongside other falsifiers'
    ' — counterfeiters, impersonators, forgers — reflects the medieval legal and moral'
    ' framework for understanding fraudulent alchemy. In medieval law, making false metals'
    ' was a form of counterfeiting and was treated as a serious crime; the English statute'
    ' of 1403 (Multipliers Act) that attempted to restrict alchemical practice addressed'
    ' exactly this concern about fraudulent multiplication of false coin. Dante\'s'
    ' identification of alchemy with counterfeiting thus reflects not eccentric moralizing'
    ' but mainstream medieval legal and ethical classification of what fraudulent alchemists'
    ' were doing.</p>'
    '<p>The specific diseases Dante assigns to the alchemists — Griffolino suffers mange'
    ' and Capocchio\'s skin is scratched by his claws — are parallel to what was believed'
    ' about the occupational hazards of alchemical work: the exposure to sulfurous fumes,'
    ' to mercury vapor, to corrosive substances produced skin and lung diseases that'
    ' contemporary observers connected to the laboratory. This medical dimension of Dante\'s'
    ' punishment imagery suggests familiarity with the actual conditions of alchemical'
    ' practice rather than purely symbolic invention.</p>'
    '<p>Dante\'s natural philosophy, elaborated most fully in the <i>Convivio</i> and'
    ' deployed throughout the <i>Divine Comedy</i>, was the most sophisticated literary'
    ' expression of the Aristotelian-Thomist synthesis in medieval vernacular writing.'
    ' His accounts of the generation of metals in the earth, of the role of celestial'
    ' influence in terrestrial processes, and of the relationship between form and matter'
    ' in material change all engage with exactly the natural philosophical questions that'
    ' medieval alchemical theory addressed. Understanding Dante\'s natural philosophy thus'
    ' provides insight into the broader intellectual context of medieval Latin alchemy —'
    ' the same traditions of Aristotelian natural philosophy and Thomist synthesis within'
    ' which the most serious alchemical theorists of the thirteenth and fourteenth centuries'
    ' worked.</p>'
),

# ── Remaining stubs not yet addressed ─────────────────────────────────────────

'christiaan-huygens': (
    '<p>Christiaan Huygens (1629–1695) was a Dutch mathematician, astronomer, and physicist'
    ' who made foundational contributions to optics (wave theory of light), mechanics (the'
    ' pendulum clock, centripetal force), and astronomy (the rings of Saturn, the largest moon'
    ' of Saturn which he named Titan). He worked in Paris as a founding member of the French'
    ' Académie Royale des Sciences from 1666 to 1681 and corresponded with all the major'
    ' natural philosophers of his era.</p>'
    '<h2>Mechanism and Its Context</h2>'
    '<p>Huygens\'s natural philosophy was thoroughly mechanist: he sought to explain all'
    ' natural phenomena, including light, in terms of the motion of material particles.'
    ' His wave theory of light — published in <i>Traité de la Lumière</i> (1690) — explained'
    ' reflection, refraction, and double refraction in Iceland spar through a mechanical'
    ' model of pressure waves in the ether. This commitment to mechanical explanation'
    ' placed him firmly in the tradition that excluded the qualitative, vital, and occult'
    ' principles that alchemical natural philosophy invoked.</p>'
    '<p>Huygens\'s relationship to alchemy was thus primarily that of an intellectual'
    ' opponent. His mechanical natural philosophy provided no place for the sulphur-mercury'
    ' theory, for the Philosophers\' Stone, or for the vital principles of Helmontian'
    ' chemistry; and the experimental program he pursued — mathematical physics of motion,'
    ' geometric optics, astronomical observation — was parallel to but not intersecting with'
    ' the laboratory chemistry tradition. His significance for the history of alchemy is'
    ' therefore primarily as a marker of the alternative natural philosophical program that'
    ' coexisted with and eventually displaced the alchemical tradition.</p>'
    '<p>Joella Yoder\'s scholarly work on Huygens and Robert Hooke provides the historical'
    ' context for his natural philosophy. His correspondence with [LINK:robert-boyle]'
    ' and his engagement with the early Royal Society placed him in the same intellectual'
    ' network as practitioners whose work intersected with alchemy, but Huygens\'s own'
    ' contributions were consistently in the domain of mathematical physics rather than'
    ' chemical inquiry. The contrast between his mechanist program and the chymical'
    ' tradition of Boyle, Newton, and Starkey illustrates the breadth of natural philosophical'
    ' approaches available in the seventeenth century and the diversity of the programs'
    ' that were pursued simultaneously within the emerging community of experimental'
    ' natural philosophy.</p>'
),

'franciscus-patricius': (
    '<p>Francesco Patrizi (Franciscus Patricius, 1529–1597) was an Italian philosopher and'
    ' humanist who developed a systematic neo-Platonist natural philosophy in explicit'
    ' opposition to Aristotelian scholasticism. His major work, <i>Nova de Universis'
    ' Philosophia</i> (New Philosophy of the Universe, 1591), proposed a comprehensive'
    ' alternative to Aristotle based on Neoplatonic metaphysics and Hermetic natural'
    ' philosophy, with a central role for light as the fundamental principle of reality.</p>'
    '<h2>Light Metaphysics and Natural Philosophy</h2>'
    '<p>Patrizi\'s account of the universe as fundamentally constituted by light, space, and'
    ' heat — replacing Aristotle\'s four elements with these three principles — drew on'
    ' both Neoplatonic metaphysics (light as the first emanation of the One) and the'
    ' Hermetic tradition (the divine light of the Poimandres). His rejection of Aristotelian'
    ' forms in favor of an active light-principle that penetrated and animated all matter'
    ' had implications for natural philosophy that overlapped with the alchemical tradition\'s'
    ' account of how subtle spiritual principles operated through and transformed material'
    ' substances.</p>'
    '<p>Patrizi\'s relationship to alchemy was indirect: he was a philosopher rather than a'
    ' laboratory practitioner, and his program of philosophical reform was directed at the'
    ' academic curriculum rather than at chemical practice specifically. But his substitution'
    ' of Hermetic Neoplatonism for Aristotelianism as the proper foundation of natural'
    ' philosophy was part of the same intellectual movement that gave alchemy its'
    ' philosophical legitimation. [LINK:marsilio-ficino]\'s earlier synthesis of Neoplatonism'
    ' and Hermeticism had established the basic framework; Patrizi\'s <i>Nova Philosophia</i>'
    ' was a later, more systematic attempt to develop this framework into a complete alternative'
    ' natural philosophy. His influence on later Neoplatonic and Hermetic natural philosophers,'
    ' including those who also engaged with alchemy, made him a significant background figure'
    ' in the intellectual history of the late Renaissance.</p>'
    '<p>Donald Kelly\'s work on Renaissance philosophy and Anna Corrias\'s recent analysis'
    ' of Patrizi\'s relationship to the Hermetic tradition provide the scholarly context.'
    ' His condemnation by the Inquisition — his <i>Nova Philosophia</i> was placed on the'
    ' Index of Prohibited Books — reflects the degree to which Hermetic natural philosophy'
    ' remained theologically problematic even in late Renaissance Italy, a constraint that'
    ' shaped the conditions under which both Patrizi and alchemical practitioners worked.</p>'
),

'jacob-grimm': (
    '<p>Jacob Grimm (1785–1863) was a German philologist, folklorist, and scholar who, with'
    ' his brother Wilhelm, collected and published the fairy tales known as <i>Kinder- und'
    ' Hausmärchen</i> (Children\'s and Household Tales, 1812–1815). A major contribution'
    ' to German Romantic folklore scholarship, the collection is significant for the history'
    ' of alchemy primarily through the alchemical and transformational themes in many of'
    ' its tales.</p>'
    '<h2>Transformation, Folklore, and Alchemical Symbolism</h2>'
    '<p>The alchemical resonances in fairy tale imagery — the transformation of base materials'
    ' into gold, the purification of the worthy through ordeal, the magical substances that'
    ' enable transformation, the wise hermit-like helpers who possess secret knowledge of'
    ' natural processes — have been analyzed by scholars including C.G. Jung, who argued'
    ' that fairy tale imagery encoded the same psychological archetypes that alchemical'
    ' symbolism expressed. Whether or not the Jungian interpretation is accepted, the'
    ' structural parallels between alchemical symbolism and fairy tale motifs are real'
    ' and reflect the shared cultural roots of both in pre-modern European popular and'
    ' learned culture.</p>'
    '<p>Grimm\'s own scholarly work was primarily in historical linguistics and mythology'
    ' rather than in the history of natural philosophy. His <i>Deutsche Mythologie</i>'
    ' (German Mythology, 1835) analyzed the survivals of pre-Christian Germanic religious'
    ' belief in folk customs and tales, including transformation beliefs and magical'
    ' practices. His approach — treating folk tradition as a reservoir of ancient cultural'
    ' memory that could be recovered through scholarly analysis — connects him to the'
    ' broader Romantic project of recovering pre-modern forms of knowledge and experience'
    ' that the Enlightenment had dismissed.</p>'
    '<p>For the history of alchemy, Grimm\'s significance is primarily as evidence for'
    ' the cultural afterlife of alchemical symbolism in the Romantic period. The transformation'
    ' motifs in the tales he collected reflect a popular cultural tradition that ran parallel'
    ' to the learned alchemical tradition and that preserved, in folk form, symbolic and'
    ' narrative structures that practitioners of learned alchemy had developed in more'
    ' systematic and theoretically articulated ways. The Romantic recovery of these popular'
    ' traditions alongside the rediscovery of learned alchemy in the work of Goethe and'
    ' others reflects a broader Romantic interest in forms of natural knowledge that the'
    ' Enlightenment had marginalized.</p>'
),

'jabir-ibn-aflah': (
    '<p>Jabir ibn Aflah (c. 1100–1160 CE) was an Andalusian astronomer whose <i>Islah'
    ' al-Majisti</i> (Correction of the Almagest) was translated into Latin as <i>Gebri'
    ' filii Affla Hispalensis de astronomia libri IX</i>. He should not be confused with'
    ' the eighth-century Islamic alchemist Jabir ibn Hayyan, with whom he shares a given name'
    ' but nothing else. Despite this potential for confusion, the Latin name "Geber" is most'
    ' commonly associated with the alchemical tradition of pseudo-Geber, while "Jabir ibn Aflah"'
    ' identifies the astronomer.</p>'
    '<h2>Astronomical Contributions and the Latin Transmission</h2>'
    '<p>Jabir ibn Aflah\'s astronomical work was critical of Ptolemy\'s <i>Almagest</i>'
    ' in specific technical respects: he argued that Mercury and Venus orbited the Sun'
    ' rather than the Earth (an important step toward heliocentrism), he criticized'
    ' Ptolemy\'s treatment of parallax, and he proposed modifications to the mathematical'
    ' models for several planetary motions. His text was translated into Latin by Gerard'
    ' of Cremona in the twelfth century and influenced subsequent European astronomy, being'
    ' used by Regiomontanus and eventually cited by Copernicus.</p>'
    '<p>His relevance to the history of alchemy is primarily through the confusion of names:'
    ' the medieval and early modern Latin tradition sometimes conflated the astronomer Jabir'
    ' ibn Aflah with the alchemist Jabir ibn Hayyan (Pseudo-Geber), creating a composite'
    ' "Geber" figure of astronomical and alchemical wisdom. This confusion is one example'
    ' of the broader pattern of name-based attribution in the history of Arabic-Latin'
    ' transmission, in which the prestige of famous Arabic names attracted additional texts'
    ' and enhanced the authority of works circulating under those names.</p>'
    '<p>The distinction between the two Jabirs matters for understanding what "Geber" meant'
    ' to medieval Latin readers. When [LINK:roger-bacon] cited Geber as an alchemical'
    ' authority, he was citing the pseudo-Geberian tradition derived from the alchemist'
    ' Jabir ibn Hayyan; when astronomers cited Geber, they might be citing the astronomer'
    ' Jabir ibn Aflah. The shared name created interpretive opportunities for authors who'
    ' wanted to enhance the authority of their claims by association with the most prestigious'
    ' Arabic tradition available, and this kind of strategic citation of shared names was'
    ' part of the broader culture of attributed authority that characterized both Arabic'
    ' and Latin alchemical and astronomical writing.</p>'
),

'juan-huarte-de-san-juan': (
    '<p>Juan Huarte de San Juan (c. 1529–1588) was a Spanish physician and natural philosopher'
    ' whose <i>Examen de Ingenios para las Ciencias</i> (Examination of Men\'s Wits, 1575)'
    ' was one of the most widely read works of Renaissance psychology. Translated into Italian,'
    ' French, English, Latin, and Dutch, it was influential across Europe in the late sixteenth'
    ' and seventeenth centuries as an account of natural individual differences in intelligence'
    ' and their relationship to different intellectual pursuits.</p>'
    '<h2>Natural Philosophy of Mind and Its Relation to Chemical Inquiry</h2>'
    '<p>Huarte\'s central thesis was that individual differences in intelligence — the capacity'
    ' for different kinds of intellectual work — were physiologically determined by the specific'
    ' humoral constitution of the brain. Different intellectual pursuits required different'
    ' balances of the humors: medicine required one balance, theology another, mathematics'
    ' a third. This naturalistic account of intellectual ability, grounded in the Galenic'
    ' humoral physiology, was controversial for its implications about human freedom and divine'
    ' grace but was also scientifically interesting as an early attempt to connect natural'
    ' philosophical theory to psychological observation.</p>'
    '<p>Huarte\'s relationship to alchemy is indirect but historically interesting. His'
    ' account of the natural philosophical basis of different intellectual capacities drew'
    ' on the same humoral-elemental framework that medical alchemy used, and his empirical'
    ' observations about individual differences in the ability to learn and practice different'
    ' skills touched on questions that were relevant to the apprenticeship model of alchemical'
    ' training: not everyone was suited to the laboratory, and the question of what natural'
    ' qualities fitted a person for alchemical work was one that practitioners sometimes'
    ' addressed explicitly.</p>'
    '<p>The broader significance of Huarte\'s work for the history of early modern natural'
    ' philosophy lies in his combination of classical humoral physiology with empirical'
    ' psychological observation in a systematic framework. This combination — theory and'
    ' observation together — characterizes the best early modern natural philosophy in'
    ' other domains as well, and Huarte\'s text serves as evidence for the breadth and'
    ' sophistication of Spanish Renaissance natural philosophy, which has been somewhat'
    ' underrepresented in standard accounts of the Scientific Revolution that have focused'
    ' primarily on Italian, English, and French figures.</p>'
),
}

def load_all():
    conn = sqlite3.connect(DB)
    for slug, extra in extras.items():
        app(conn, slug, extra)
    conn.commit()
    conn.close()

    # Final audit
    c = conn.cursor()
    c2 = sqlite3.connect(DB)
    c = c2.cursor()
    c.execute('SELECT slug, bio_html FROM persons ORDER BY slug')
    below = [(s, wc(b)) for s, b in c.fetchall() if wc(b) < 1200]
    print(f'\n=== Still below 1200 ({len(below)} entries) ===')
    for s, w in below:
        print(f'  {w:4d}  {s}')
    c2.close()

if __name__ == '__main__':
    load_all()
