#!/usr/bin/env python3
"""
expand_batch4_renaissance_medieval.py

Full bios: Ficino, Ripley, Dee, Agrippa, Flamel, Hildegard (medieval/Renaissance cluster)
Expansions: Albertus Magnus, Avicenna, Newman, Principe
Text expansions: alchemia, splendor-solis, mutus-liber, book-of-lambspring,
                 amphitheatre-of-eternal-wisdom, liber-xxiv-philosophorum,
                 de-sex-rerum-principiis, picatrix, chymisches-cabinett
"""
import sqlite3, re
DB = 'db/alchemy_timeline.db'

def wc(h): return len(re.sub('<[^>]+>', ' ', h or '').split())
def app(conn, table, field, slug, extra):
    c = conn.cursor()
    c.execute(f'SELECT {field} FROM {table} WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    new = cur + extra
    c.execute(f'UPDATE {table} SET {field}=?, source_method=?, review_status=? '
              'WHERE slug=?', (new, 'AI_ASSISTED', 'DRAFT', slug))
    print(f'  {slug}: {wc(cur)} -> {wc(new)}')

def setp(conn, slug, bio):
    c = conn.cursor()
    c.execute('UPDATE persons SET bio_html=?, source_method=?, review_status=? WHERE slug=?',
              (bio, 'AI_ASSISTED', 'DRAFT', slug))
    print(f'  {slug}: set to {wc(bio)} words')

# ---------------------------------------------------------------------------
# FULL BIOS
# ---------------------------------------------------------------------------

def ficino_bio():
    return (
        '<p>Marsilio Ficino (1433-1499) was an Italian philosopher, physician, and priest who served '
        'as the head of the Platonic Academy in Florence under the patronage of Cosimo and Lorenzo de\' '
        'Medici, and whose Latin translations of Plato, Plotinus, and the Corpus Hermeticum made the '
        'Neoplatonic and Hermetic traditions of late antiquity accessible to the Latin West for the first '
        'time. Born in Figline Valdarno near Florence, Ficino received a humanist education and medical '
        'training before being commissioned by Cosimo de\' Medici around 1462 to translate the recently '
        'recovered Greek manuscripts of the Hermetic corpus. His translation of the [LINK:corpus-hermeticum] '
        'as <i>Pimander</i> (completed 1463, printed 1471) predated his Plato translations and reflected '
        'Cosimo\'s belief that the Hermetic texts, attributed to an ancient Egyptian sage named Hermes '
        'Trismegistus, preserved a pre-Christian divine wisdom. Ficino\'s philosophical synthesis — '
        'combining Platonic metaphysics, Neoplatonic theurgy, Hermetic magic, and Christian theology — '
        'shaped Renaissance learned culture across Europe and had lasting consequences for the history of '
        'alchemy, esotericism, and natural magic.</p>'
        '<h2>Works and Intellectual Context</h2>'
        '<p>Ficino\'s major works include his Latin translations of Plato (completed 1469, printed 1484), '
        'his translation and commentary on Plotinus\'s <i>Enneads</i> (1492), and his own philosophical '
        'synthesis <i>Theologia Platonica de Immortalitate Animorum</i> (1474, printed 1482). His '
        '<i>De Vita</i> (Three Books on Life, 1489) combines medical, astrological, and magical material: '
        'Book Three, <i>De Vita Coelitus Comparanda</i> (On Obtaining Life from the Heavens), presents a '
        'systematic account of astral magic — drawing on correspondences between planets, metals, plants, '
        'stones, and musical tones — that had immediate relevance to alchemical theory. The doctrine that '
        'celestial bodies (Sun, Moon, and the five planets of ancient astronomy) governed the formation '
        'and quality of the corresponding metals in the earth provided a philosophical framework for '
        'understanding why gold was the most perfect metal (governed by the Sun, the most perfect planet) '
        'and why transmutation might be possible (manipulating the celestial correspondences that'
        ' determined metallic quality). This Ficinian astral magic, transmitted through texts like '
        'Agrippa\'s [LINK:de-occulta-philosophia], became part of the theoretical background against which '
        'early modern alchemists worked.</p>'
        '<p>Ficino\'s influence on alchemy operated primarily through the prestige he gave to the '
        '[LINK:corpus-hermeticum] and to the figure of Hermes Trismegistus as an ancient authority on '
        'natural magic and matter transformation. By presenting the Hermetic texts as the work of a '
        'pre-Christian Egyptian sage contemporary with Moses, Ficino validated the claim that alchemical '
        'knowledge derived from ancient divine wisdom — a legitimizing move that alchemical writers '
        'exploited throughout the sixteenth and seventeenth centuries. The real significance of this '
        'was rhetorical rather than operational: Ficino\'s Hermetism provided alchemy with philosophical '
        'prestige, not new laboratory techniques. What practitioners actually did in their laboratories '
        'derived from the Arabic and Latin technical traditions, not from Hermetic philosophy.</p>'
        '<h2>Alchemical Significance</h2>'
        '<p>Ficino\'s direct engagement with alchemy was limited but philosophically significant. His '
        'medical writings drew on a theory of the spiritus mundi — a subtle, semi-material spirit '
        'pervading the cosmos and mediating between the celestial and earthly realms — that had '
        'implications for alchemical theory about how celestial influences affected metallic generation. '
        'His concept of [LINK:prisca-theologia] — the ancient theology common to all wise traditions, of '
        'which Hermetism, Platonism, and Christianity were expressions — provided a framework in which '
        'alchemical claims to ancient Egyptian origin could be accommodated and taken seriously. The '
        'alchemical writers of the late sixteenth and early seventeenth centuries — including the '
        'Rosicrucian movement and figures like [LINK:michael-maier] — drew heavily on Ficinian Hermetism '
        'as a philosophical legitimation for their work, even when the actual laboratory content of their '
        'texts owed nothing to Ficino.</p>'
        '<h2>Scholarly Debates</h2>'
        '<p>Frances Yates\'s influential but contested thesis — articulated in <i>Giordano Bruno and the '
        'Hermetic Tradition</i> (1964) and related works — argued that Ficinian Hermetism was a primary '
        'driver of the Scientific Revolution, that Renaissance magi who believed they could manipulate '
        'nature through Hermetic magic created the intellectual climate for experimental natural '
        'philosophy. Brian Copenhaver, Wouter Hanegraaff, and others have substantially qualified this '
        'thesis, arguing that Yates overstated the continuity between Ficinian magic and seventeenth- '
        'century natural philosophy. Newman and Principe\'s revisionary project has been explicitly '
        'critical of the Yates paradigm as it applies to alchemy: they argue that alchemical practice '
        'was experimental and operational in ways that Ficinian Hermetism was not, and that the '
        'symbolic and philosophical apparatus that alchemists borrowed from Hermetism was a rhetorical '
        'overlay rather than a constitutive element of their laboratory inquiry. This critique does not '
        'diminish Ficino\'s historical significance but relocates it: he matters for the history of '
        'esotericism and for the rhetorical culture of Renaissance learning more than for the history '
        'of chemical practice.</p>'
        '<h2>Literature</h2>'
        '<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. '
        'Cambridge University Press, 1992.<br>'
        'Hanegraaff, Wouter J. <i>Esotericism and the Academy: Rejected Knowledge in Western Culture</i>. '
        'Cambridge University Press, 2012.<br>'
        'Kristeller, Paul Oskar. <i>The Philosophy of Marsilio Ficino</i>. Columbia University Press, 1943.<br>'
        'Voss, Angela. <i>Marsilio Ficino</i>. North Atlantic Books, 2006.<br>'
        'Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. University of Chicago Press, '
        '1964.<br>'
        'Newman, William R. <i>Atoms and Alchemy</i>. University of Chicago Press, 2006.</p>'
    )

def ripley_bio():
    return (
        '<p>George Ripley (c. 1415-1490) was an English Augustinian canon and alchemist whose major work, '
        '<i>The Compound of Alchymy, or The Twelve Gates</i> (composed c. 1470-1471, printed 1591), '
        'established the template for vernacular English alchemical poetry and remained an authoritative '
        'text in the English alchemical tradition through the seventeenth century. Born in Yorkshire and '
        'educated at the Augustinian priory of Bridlington, Ripley travelled to Italy and Rome, where he '
        'reportedly studied alchemy with Italian practitioners, and was associated with the papal court. '
        'He returned to England and spent the latter part of his career at Bridlington and Boston, '
        'Lincolnshire. His alchemical works — primarily verse and allegorical prose — became central '
        'texts in the English chymical tradition: [LINK:george-starkey]\'s pseudonymous Philalethes '
        'published <i>Ripley Reviv\'d</i>, an extended commentary on Ripley, demonstrating the '
        'fifteenth-century canon\'s continued authority in seventeenth-century laboratory practice.</p>'
        '<h2>Works and Intellectual Context</h2>'
        '<p>Ripley\'s <i>Compound of Alchymy</i> divides the alchemical process into twelve "gates" or '
        'stages — calcination, dissolution, separation, conjunction, putrefaction, congelation, '
        'cibation, sublimation, fermentation, exaltation, multiplication, and projection — corresponding '
        'to twelve verse stanzas in rhyme royal. This twelve-gate structure became the canonical '
        'organization of English alchemical verse. His <i>Medulla Alchymiae</i>, the <i>Epistle to '
        'Edward IV</i>, and several shorter works circulated widely in manuscript before and after '
        'printing. His Latin work <i>Liber de Mercurio et Lapide Philosophorum</i> addresses the '
        'preparation of philosophical mercury, the stage on which [LINK:george-starkey] and '
        '[LINK:isaac-newton] would focus their most intense laboratory efforts. The theoretical '
        'framework of Ripley\'s alchemy is sulphur-mercury theory: all metals composed of sulphur and '
        'mercury in varying ratios, gold the most perfect combination, the Stone the agent of perfecting '
        'impure combinations.</p>'
        '<p>Ripley\'s verse makes extensive use of allegory — the alchemical process described in terms '
        'of dragons, eagles, kings and queens, death and resurrection — while simultaneously encoding '
        'specific laboratory procedures. The allegorical language functioned as a form of concealment '
        '(restricting knowledge to initiated readers) and as a form of expression (mapping the '
        'transformations of matter onto narrative and mythological frameworks that gave them additional '
        'meaning). This dual function of alchemical allegory, analyzed by Lawrence Principe and William '
        'Newman, is well illustrated in Ripley: practitioners reading his verse understood that the '
        '"green lion devouring the sun" referred to a specific chemical operation with gold, while '
        'uninitiated readers encountered only impenetrable imagery.</p>'
        '<h2>Alchemical Significance</h2>'
        '<p>Ripley\'s significance in the broader alchemical tradition extends beyond his individual '
        'works to his role in shaping the English vernacular alchemical canon. His twelve-gate structure '
        'was reproduced, commented upon, and built upon by English practitioners for two centuries. '
        'Elias Ashmole\'s monumental anthology <i>Theatrum Chemicum Britannicum</i> (1652) placed Ripley '
        'prominently in the English alchemical tradition. [LINK:george-starkey]\'s <i>Ripley Reviv\'d</i> '
        '(attributed to Philalethes) presented extended commentary that treated Ripley\'s verses as '
        'encoded practical guidance for preparing philosophical mercury — demonstrating that seventeenth- '
        'century practitioners read Ripley as a technical manual requiring careful decoding, not as '
        'poetry or allegory detached from laboratory practice. Newton\'s alchemical reading included '
        'Ripley texts, and his laboratory notebooks show him attempting to decode Ripley\'s allegorical '
        'procedures into specific chemical operations.</p>'
        '<h2>Scholarly Debates</h2>'
        '<p>Stanton Linden\'s <i>Dark Hierogliphicks: Alchemy in English Literature from Chaucer to the '
        'Restoration</i> (1996) provides important context for Ripley\'s literary significance. Jennifer '
        'Rampling\'s recent work on Ripley\'s manuscripts and sources, including her critical examination '
        'of the Ripley corpus in relation to earlier Latin and vernacular traditions, has substantially '
        'advanced understanding of what Ripley read and how he transformed his sources. Newman and '
        'Principe\'s framework — that alchemical allegory encodes laboratory practice — is well supported '
        'by the Ripley tradition: the specific procedures described under allegorical cover in Ripley\'s '
        'verse correspond to identifiable chemical operations in the sulphur-mercury tradition, and the '
        'commentary tradition initiated by Starkey\'s Philalethes texts represents practitioners actively '
        'decoding those operations for laboratory use.</p>'
        '<h2>Literature</h2>'
        '<p>Linden, Stanton J. <i>Dark Hierogliphicks: Alchemy in English Literature from Chaucer to the '
        'Restoration</i>. University Press of Kentucky, 1996.<br>'
        'Newman, William R. <i>Gehennical Fire: The Lives of George Starkey</i>. Harvard University Press, '
        '1994.<br>'
        'Principe, Lawrence M. <i>The Secrets of Alchemy</i>. University of Chicago Press, 2013.<br>'
        'Rampling, Jennifer M. <i>The Experimental Fire: Inventing English Alchemy, 1300-1700</i>. '
        'University of Chicago Press, 2020.<br>'
        'Ashmole, Elias, ed. <i>Theatrum Chemicum Britannicum</i>. London, 1652.</p>'
    )

def nicholas_flamel_bio():
    return (
        '<p>Nicholas Flamel (c. 1330-1418) was a French scribe and manuscript dealer from Pontoise who '
        'became, centuries after his death, the most famous alchemist in popular European tradition — '
        'a figure credited with having achieved transmutation of base metal into gold and to have '
        'attained immortality. The historical Flamel was a successful Parisian businessman who made '
        'substantial charitable donations, endowing churches and hospitals; the legendary Flamel, '
        'constructed from a single autobiographical account first published in 1612 nearly two centuries '
        'after his death, was an unlettered scribe who deciphered a mysterious illustrated manuscript '
        'attributed to Abraham the Jew, made a pilgrimage to Santiago de Compostela where he met a '
        'Jewish converso who explained the manuscript\'s secrets, and returned to Paris to achieve '
        'transmutation in 1382. The gap between the historical and the legendary Flamel is itself a '
        'significant historical document: it illustrates how alchemical celebrity was constructed and '
        'propagated in early modern Europe.</p>'
        '<h2>The Flamel Legend and Its Construction</h2>'
        '<p>The primary source for Flamel\'s alchemical legend is the <i>Livre des figures hieroglyphiques</i> '
        '(Book of Hieroglyphic Figures), first published in Paris in 1612 under the title <i>Exposition '
        'des figures hieroglyphiques</i>. This text — purportedly Flamel\'s own account of his alchemical '
        'journey — describes his purchase of a mysterious book of Abraham the Jew, his struggle to decode '
        'it, his pilgrimage to Santiago, and his eventual transmutation. Scholars have established that '
        'this text was composed long after Flamel\'s death, probably in the late sixteenth or early '
        'seventeenth century, as a pseudonymous alchemical autobiography in the tradition of constructing '
        'legendary adepts. The fictional Flamel joined the Philosopher\'s Stone\'s other legendary '
        'possessors — Nicolas de Cusa, Paracelsus, Eirenaeus Philalethes — in the mythology of achieved '
        'transmutation that gave the alchemical tradition its social authority.</p>'
        '<p>The historical Flamel is documented through genuine archival sources: notarial records, '
        'property transactions, charitable foundation documents, and a genuine tombstone (now in the '
        'Musee de Cluny, Paris). He was indeed a prosperous Parisian manuscript dealer and scribe who '
        'became wealthy, and his charitable donations — endowing churches in Paris with elaborate portal '
        'decorations — were genuine. Some of these decorations included imagery later interpreted as '
        'alchemical; the alchemical interpretation, however, postdates Flamel\'s life and reflects the '
        'retroactive attribution of alchemical significance to imagery that was probably conventional '
        'religious iconography in its original context.</p>'
        '<h2>Alchemical Significance</h2>'
        '<p>Flamel\'s significance for the history of alchemy is primarily as a case study in the '
        'construction of alchemical authority and celebrity. The Flamel legend demonstrates how '
        'alchemical tradition generated authoritative figures — legendary adepts who had achieved the '
        'Stone — whose existence validated the tradition\'s aspirations and whose published works could '
        'claim the authority of genuine practical achievement. The same mechanism operated in George '
        'Starkey\'s construction of the Eirenaeus Philalethes persona, as William Newman showed in '
        '[LINK:gehennical-fire] (1994): the legendary adept was a rhetorical construction that gave '
        'practical alchemical knowledge a form of authority that the known identity of its author could '
        'not provide. Flamel\'s enduring popularity in occultist and popular culture — he appears in '
        'Harry Potter, in Dan Brown\'s fiction, and in numerous occultist publications — demonstrates '
        'the resilience of the legendary tradition but also its distance from the serious experimental '
        'practice that the scholarly historiography of Newman and Principe has recovered.</p>'
        '<h2>Scholarly Debates</h2>'
        '<p>Didier Kahn\'s research on the construction of the Flamel legend is definitive for establishing '
        'the textual history of the pseudo-Flamel corpus. Lawrence Principe\'s discussions of alchemical '
        'celebrity construction in <i>The Secrets of Alchemy</i> (2013) situate Flamel within the broader '
        'pattern of pseudo-historical adepts. Umberto Eco\'s cultural analysis of Flamel\'s afterlife in '
        'popular and occultist culture illustrates how the legend\'s appeal persists independently of its '
        'historical foundations. The most important historiographical point is the one Newman and Principe '
        'consistently make: the legendary Flamel, the historical Flamel, and the laboratory chemistry of '
        'the alchemical tradition are three different things that should not be conflated.</p>'
        '<h2>Literature</h2>'
        '<p>Kahn, Didier. <i>Alchimie et Paracelsisme en France a la fin de la Renaissance</i>. Droz, '
        '2007.<br>'
        'Principe, Lawrence M. <i>The Secrets of Alchemy</i>. University of Chicago Press, 2013.<br>'
        'Newman, William R. <i>Gehennical Fire: The Lives of George Starkey</i>. Harvard University Press, '
        '1994.<br>'
        'Pereira, Michela. <i>The Alchemical Corpus Attributed to Raymond Lull</i>. Warburg Institute, '
        '1989.</p>'
    )

def hildegard_bio():
    return (
        '<p>Hildegard of Bingen (1098-1179) was a German Benedictine abbess, visionary, composer, and '
        'natural philosopher whose encyclopedic writings on medicine, cosmology, and natural history made '
        'her one of the most intellectually productive figures of the twelfth century. Born in Bermersheim '
        'vor der Hohe in the Rhineland to a noble family, she was offered to the Church as a child oblate '
        'and educated at the Benedictine monastery of Disibodenberg under the anchoress Jutta von '
        'Sponheim. After Jutta\'s death in 1136 she became head of the female community and in 1150 led '
        'her community to a new foundation at Rupertsberg near Bingen. Her major works — <i>Scivias</i> '
        '(Know the Ways, 1141-1151), <i>Liber Vitae Meritorum</i> (Book of Life\'s Merits, 1158-1163), '
        '<i>Liber Divinorum Operum</i> (Book of Divine Works, 1163-1173), and the natural history '
        'encyclopedias <i>Physica</i> and <i>Causae et Curae</i> — combine prophetic vision, theological '
        'speculation, and practical knowledge of herbs, minerals, and medicines in ways that reflect the '
        'intellectual culture of twelfth-century monastic learning.</p>'
        '<h2>Natural Philosophy and Medicine</h2>'
        '<p>Hildegard\'s <i>Physica</i> (also known as <i>Liber Simplicis Medicinae</i>) is a nine-book '
        'encyclopedic treatment of natural substances: plants, elements, trees, stones, fish, birds, '
        'animals, reptiles, and metals, each entry describing the substance\'s properties, its relationship '
        'to human health, and its medical uses. Her <i>Causae et Curae</i> provides a systematic account '
        'of human physiology and pathology based on a humoral framework adapted from Galenic medicine and '
        'modified by her own theological and cosmological principles. The theory of <i>viriditas</i> '
        '(greening power or vitality) — Hildegard\'s concept of the living force animating plants, '
        'animals, and healthy human bodies — represents a distinctively Hildegardian modification of '
        'the standard Galenic framework, integrating theological ideas about divine creative power with '
        'practical medical knowledge.</p>'
        '<p>Her treatment of minerals and metals in the <i>Physica</i> is relevant to the history of '
        'alchemy, though Hildegard was not an alchemist in any technical sense. She describes the '
        'properties of gold, silver, copper, iron, lead, tin, and mercury — and their medical uses — '
        'in terms that reflect the overlap between mineralogy, medicine, and the nascent Latin alchemical '
        'tradition of her period. The twelfth century was precisely the era in which the first Arabic '
        'alchemical texts were being translated into Latin by [LINK:gerard-of-cremona] and others; '
        'Hildegard\'s natural philosophy represents the pre-translation Latin tradition — grounded in '
        'Isidore of Seville, Bede, and Pliny — against which the new Arabic learning would be assimilated. '
        'Pamela Smith\'s framework for artisanal epistemology and embodied knowledge is applicable to '
        'Hildegard: her practical knowledge of plants, minerals, and medicines reflects direct engagement '
        'with material substances as well as textual learning.</p>'
        '<h2>Scholarly Debates</h2>'
        '<p>Scholars have debated the authenticity of works attributed to Hildegard and the relationship '
        'between her prophetic writings and her natural-philosophical encyclopedias. The <i>Physica</i> '
        'and <i>Causae et Curae</i> were long treated as authentically Hildegardian but more recent '
        'scholarship has raised questions about their precise relationship to her acknowledged prophetic '
        'works. Barbara Newman\'s <i>Sister of Wisdom: Saint Hildegard\'s Theology of the Feminine</i> '
        '(1987) provides the most comprehensive theological analysis; Priscilla Throop\'s translations '
        'of the <i>Physica</i> and <i>Causae et Curae</i> have made them accessible to non-specialists. '
        'Hildegard\'s significance for the history of alchemy and chemistry is as a representative of '
        'pre-scholastic Latin natural philosophy — the tradition that the Arabic translations would '
        'transform in the later twelfth and thirteenth centuries into the systematic natural philosophy '
        'within which Latin alchemy developed.</p>'
        '<h2>Literature</h2>'
        '<p>Newman, Barbara. <i>Sister of Wisdom: Saint Hildegard\'s Theology of the Feminine</i>. '
        'University of California Press, 1987.<br>'
        'Throop, Priscilla, trans. <i>Hildegard von Bingen\'s Physica</i>. Healing Arts Press, 1998.<br>'
        'Maddocks, Fiona. <i>Hildegard of Bingen: The Woman of Her Age</i>. Doubleday, 2001.<br>'
        'Strehlow, Wighard, and Gottfried Hertzka. <i>Hildegard of Bingen\'s Medicine</i>. Bear, 1988.<br>'
        'Principe, Lawrence M. <i>The Secrets of Alchemy</i>. University of Chicago Press, 2013.</p>'
    )

# ---------------------------------------------------------------------------
# EXPANSIONS FOR NEAR-MINIMUM BIOS
# ---------------------------------------------------------------------------

ALBERTUS_EXTRA = (
    '<h2>Alchemical Writings and Their Authenticity</h2>'
    '<p>The question of Albertus Magnus\'s alchemical writings is one of the most contested in medieval '
    'intellectual history. Several alchemical treatises circulated under his name, most importantly '
    '<i>Libellus de Alchimia</i> (also known as <i>Semita Recta</i>, "The Right Path") and the '
    '<i>Compositum de Compositis</i>. Scholars have debated the authenticity of these works: some '
    'argue that they are genuine, reflecting Albertus\'s interest in mineralogical and experimental '
    'matters evident in his genuine <i>De Mineralibus</i>; others maintain they are pseudonymous works '
    'composed after Albertus\'s death to benefit from his scholarly authority. William Newman\'s '
    'critical edition of the <i>Libellus de Alchimia</i> examines the question carefully, finding '
    'evidence of genuine Albertan material reworked or supplemented by later hands. The circulation '
    'of alchemical texts under Albertus\'s name reflects the broader pattern of medieval pseudonymous '
    'attribution: attaching alchemical works to the most authoritative philosopher of the period gave '
    'them academic legitimacy and deflected the suspicion that alchemy was fraudulent or theologically '
    'dangerous. The genuine <i>De Mineralibus</i> engaged seriously with the question of metallic '
    'composition and the possibility of alchemical transmutation, providing a scholastic framework that '
    'subsequent alchemists could cite as authoritative support for their work.</p>'
    '<p>Newman and Principe situate Albertus\'s engagement with alchemy within the broader context of '
    'thirteenth-century scholastic natural philosophy\'s attempt to absorb and rationalize the new '
    'Arabic learning — including both Aristotelian natural philosophy and Arabic alchemical theory — '
    'within a theological framework. Albertus\'s conclusion in <i>De Mineralibus</i> that alchemists '
    'can produce substances resembling gold but not genuine gold (i.e., that art can imitate but not '
    'replicate nature) established a position that subsequent scholastic alchemical writers had to '
    'either accept or argue against, making his authoritative skepticism a productive provocation '
    'for the tradition.</p>'
)

AVICENNA_EXTRA = (
    '<h2>Alchemical Theory and Its Transmission</h2>'
    '<p>Avicenna\'s relationship to alchemy is complex and contested. His mineralogical writings — '
    'especially the section on minerals in <i>Kitab al-Shifa</i> (Book of Healing), translated into '
    'Latin as <i>De Mineralibus</i> and attributed to Aristotle in some manuscripts — provided the '
    'most influential scholastic account of the sulphur-mercury theory of metallic composition: all '
    'metals form underground through the interaction of sulphurous exhalations and mercurial vapors; '
    'their specific character depends on the ratio and purity of these components; gold forms when '
    'the combination is perfect. This account, transmitted through [LINK:gerard-of-cremona]\'s '
    'translations, became the standard scholastic explanation for metallic generation and '
    'transformation and provided the theoretical foundation for the alchemical aspiration to '
    'replicate underground processes above ground in the laboratory.</p>'
    '<p>Simultaneously, a famous passage in Avicenna\'s writings — the <i>Sciant artifices</i> '
    'passage, sometimes attributed to him but possibly a later interpolation — argued that alchemists '
    'could produce substances resembling gold but not genuine gold, since only nature could achieve '
    'the specific form required. This apparent rejection of alchemical transmutation created a '
    'long-running scholarly debate in medieval Latin alchemy about whether art could reproduce nature. '
    'Newman has analyzed this debate in detail, showing that it was a productive provocation: medieval '
    'Latin alchemists argued strenuously against Avicenna\'s skeptical position, developing sophisticated '
    'arguments about the relationship between natural and artificial processes. Whether the skeptical '
    'passage is genuinely Avicennan or a later interpolation remains debated, but its impact on the '
    'Latin tradition was enormous regardless of its origin. The pseudo-Geber <i>Summa Perfectionis</i> '
    'is in part a response to this Avicennan challenge.</p>'
)

NEWMAN_EXTRA = (
    '<h2>The Chymistry of Isaac Newton Project</h2>'
    '<p>Newman\'s most sustained institutional contribution to the field has been directing the '
    'Chymistry of Isaac Newton project at Indiana University, funded by the National Science Foundation '
    'and the National Endowment for the Humanities. This digital initiative has transcribed, encoded, '
    'and published online the entire corpus of Newton\'s alchemical manuscripts — over a million words, '
    'much of it previously inaccessible or available only to researchers who could travel to the '
    'Keynes Collection at King\'s College Cambridge, the Smithsonian Babson Collection, and other '
    'repositories. The project makes Newton\'s alchemical manuscripts available for full-text search, '
    'cross-referencing with published alchemical texts, and systematic analysis for the first time. '
    'Newman\'s monograph [LINK:newton-the-alchemist] (Princeton University Press, 2019) represents '
    'the scholarly synthesis built from this project, providing the first comprehensive account of '
    'what Newton was actually doing in his laboratory and how his alchemical work connected to his '
    'natural philosophy. Newman\'s work on Newton completes the arc of the Newman-Principe project: '
    'from George Starkey as practitioner through Robert Boyle as the bridge figure to Isaac Newton '
    'as the canonical scientific revolutionary whose career nevertheless integrated the Helmontian '
    'chymical tradition at its core.</p>'
    '<h2>Broader Significance</h2>'
    '<p>Newman\'s most important methodological contribution is arguably the combination of archival '
    'manuscript work with laboratory replication of historical procedures — a form of experimental '
    'historiography that treats alchemical laboratory notebooks as technical documents whose claims '
    'can be tested by attempting to reproduce the described procedures in a modern laboratory. This '
    'approach, developed with Principe, has produced several important findings: that alchemical '
    'procedures could produce specific, reproducible chemical results; that alchemical "cover names" '
    'corresponded to actual chemical substances and operations; and that the laboratory practice '
    'recorded in manuscripts was in many cases more systematic, quantitative, and rigorous than the '
    'published symbolic texts had suggested. Newman\'s broader argument — that early modern '
    'experimental science and alchemical practice were not opposed but continuous — has been widely '
    'adopted in the historiography of the Scientific Revolution and has substantially reshaped how '
    'historians understand the period.</p>'
)

PRINCIPE_EXTRA = (
    '<h2>Laboratory Replication and Textual Analysis</h2>'
    '<p>Principe\'s distinctive methodological contribution to the historiography of alchemy is his '
    'combination of archival manuscript research with laboratory replication. Working with actual '
    'chemical procedures described in alchemical texts — conducting the experiments in a modern '
    'laboratory to determine what the procedures actually produced — he has demonstrated that many '
    'alchemical claims corresponded to real, reproducible chemical reactions. His replications of '
    'procedures described in the Philalethes corpus (George Starkey\'s pseudonymous texts) and in '
    'Boyle\'s alchemical manuscripts have produced substances whose properties correspond to '
    'the descriptions in the texts, providing direct evidence that alchemical "cover names" referred '
    'to specific chemical operations. This approach, which requires both chemical training and '
    'historical expertise, represents a form of experimental historiography that produces kinds of '
    'evidence not available through purely textual analysis.</p>'
    '<h2>Scholarly Debates and Impact</h2>'
    '<p>Principe\'s revisionary reading of [LINK:robert-boyle] — demonstrating through manuscript '
    'evidence that Boyle was an "aspiring adept" who pursued transmutation throughout his life and '
    'used nine different ciphers to conceal his alchemical activities — was initially controversial '
    'among Boyle scholars but is now the dominant interpretation. His reinterpretation of '
    '[LINK:sceptical-chymist] as an attack on vulgar chymists rather than on alchemists has similarly '
    'become standard in the field. His broader contribution, developed jointly with Newman, is the '
    '"chymistry" framework: the argument that the modern distinction between alchemy and chemistry '
    'was constructed retrospectively in the eighteenth and nineteenth centuries and does not reflect '
    'the actual intellectual landscape of early modern natural philosophy. This framework has been '
    'productive but has also attracted criticism, most notably from Brian Vickers, who argues that '
    'Newman and Principe underweight the genuine discontinuities between alchemical and scientific '
    'ways of knowing. Principe\'s <i>The Secrets of Alchemy</i> (2013) provides the most accessible '
    'synthetic account of his position for a general scholarly audience.</p>'
)

# ---------------------------------------------------------------------------
# TEXT EXPANSIONS
# ---------------------------------------------------------------------------

TEXT_EXTRAS = {
    'alchemia': (
        '<p>Libavius\'s significance for the history of chemistry was recognized by J.R. Partington and '
        'subsequent historians as marking the moment when chemistry received its first systematic '
        'pedagogical organization as an academic discipline. The text\'s organization around specific '
        'chemical substances and operations — rather than around the philosophical categories of '
        'Paracelsian tria prima or Aristotelian elements — represented a practical turn that anticipated '
        'the approach of later chemistry textbooks. Newman and Principe\'s analysis situates Libavius as '
        'a transitional figure who sought to make alchemical and chemical knowledge academically '
        'respectable without abandoning the practical content that gave it value. His critique of '
        'Paracelsus\'s obscurantism — Libavius argued that Paracelsus\'s deliberately difficult language '
        'prevented the communication of genuine knowledge — anticipates the later argument, made by '
        'Newman and Principe, that alchemical cover names encoded rather than replaced practical '
        'knowledge. Libavius wanted the encoding abandoned in favor of clear, communicable procedure; '
        'Newman and Principe argue instead that the encoding can be decoded to reveal the practical '
        'knowledge beneath. The <i>Alchemia</i> thus stands at the beginning of a long debate about '
        'transparency versus concealment in chemical communication that continued through Boyle, Stahl, '
        'and Lavoisier.</p>'
    ),
    'splendor-solis': (
        '<p>The <i>Splendor Solis</i> belongs to a tradition of elaborately illustrated alchemical '
        'manuscripts produced in early modern Germany that combined technical alchemical content with '
        'sophisticated artistic presentation aimed at courtly patrons. Its relationship to the courts '
        'of the Holy Roman Empire — the manuscript appears to have been produced for a noble or princely '
        'patron, possibly in the Wittelsbach orbit — reflects the important role of princely patronage in '
        'supporting alchemical practice in the sixteenth century, documented by Pamela Smith in '
        '<i>The Business of Alchemy</i> (1994). The courts of the Holy Roman Empire were centers not '
        'only of alchemical patronage but of the broader culture of <i>Kunstkammer</i> collecting — '
        'assembling rarities, curiosities, and demonstrations of craft mastery — within which alchemy '
        'occupied a prestigious position. The <i>Splendor Solis</i>\'s extraordinary illustrations, '
        'combining alchemical symbolism with Renaissance ornament and naturalistic detail, represent '
        'alchemy at its most aesthetically ambitious and socially aspirational, and illustrate how '
        'the tradition mobilized visual culture in the service of legitimation and patronage appeal.</p>'
    ),
    'mutus-liber': (
        '<p>The <i>Mutus Liber</i>\'s sequence of fifteen plates — depicting alchemical operations '
        'including the collection of dew from linen sheets, the heating of substances in sealed vessels, '
        'the separation and purification of materials, and the final production of the Stone — has '
        'attracted sustained attention from historians attempting to decode its imagery in terms of '
        'specific chemical operations. Lawrence Principe\'s laboratory work and textual analysis have '
        'shown that the dew-collection sequences correspond to the preparation of a specific fermented '
        'mercury preparation using organic material, while the sealed-vessel heating corresponds to '
        'known sulphur-mercury distillation procedures. If Principe\'s decoding is correct, the '
        '<i>Mutus Liber</i> is not merely symbolic but a practical recipe presented in pictorial code '
        '— consistent with the broader pattern, identified by Newman and Principe, of alchemical '
        'cover encoding in both verbal and visual form. The text\'s publication history is also '
        'significant: it appeared at La Rochelle in 1677, in the heart of the period when the '
        'Helmontian chymical tradition was being challenged by the phlogiston framework of Stahl, '
        'and was reprinted several times through the eighteenth century, suggesting a sustained '
        'readership committed to the emblematic alchemical tradition.</p>'
    ),
    'book-of-lambspring': (
        '<p>The fifteen emblematic images in the <i>Book of Lambspring</i> have been decoded by '
        'Lawrence Principe and others as encoding stages of mercury-sulphur preparation: the '
        '"sea with two fishes" represents mercury acting on a sulphur compound; the "lion and '
        'unicorn in the forest" represents the philosophical sulphur and mercury approaching '
        'conjunction; the "father and son" reconciled represents the completed philosophical stone. '
        'This decoding — characteristic of Newman and Principe\'s approach to alchemical allegory — '
        'situates the <i>Book of Lambspring</i> within the practical tradition of sulphur-mercury '
        'alchemy rather than treating it as purely spiritual symbolism. The text\'s inclusion in the '
        'monumental <i>Musaeum Hermeticum</i> anthology (Frankfurt, 1625/1677) alongside major '
        'theoretical and practical alchemical works gave it wide circulation in the seventeenth '
        'century and ensured that it was read by the generation of Starkey, Boyle, and Newton '
        'alongside more explicitly technical texts.</p>'
    ),
    'amphitheatre-of-eternal-wisdom': (
        '<p>Khunrath\'s <i>Amphitheatre</i> belongs to the tradition of religious alchemy that '
        'flourished in the late sixteenth and early seventeenth centuries alongside the more strictly '
        'practical alchemical tradition — the tradition that Newman and Principe have recovered as '
        'the true history of experimental chymistry. The relationship between these two traditions '
        'is historically significant: practitioners like Starkey and Boyle worked primarily in the '
        'practical laboratory tradition, but their reading included emblematic and spiritual works '
        'like Khunrath\'s, and the symbolic vocabulary of religious alchemy provided a rhetorical '
        'framework within which practical alchemical claims could be expressed and legitimated. '
        'Wouter Hanegraaff\'s analysis of the Western esoteric tradition in the <i>Dictionary of '
        'Gnosis and Western Esotericism</i> situates Khunrath within the broader current of '
        'Christian theosophy that included Paracelsus, Jacob Boehme, and later Rosicrucianism. '
        'The circular engraving in the <i>Amphitheatre</i> — with its combination of prayer, '
        'musical instruments, laboratory apparatus, and philosophical texts — is among the most '
        'frequently reproduced images in the history of alchemy and has been interpreted variously '
        'as a manifesto for the unity of natural and spiritual knowledge.</p>'
    ),
    'liber-xxiv-philosophorum': (
        '<p>The <i>Liber XXIV Philosophorum</i> has attracted sustained philosophical attention '
        'because several of its propositions — including the famous "God is an infinite sphere whose '
        'center is everywhere and whose circumference is nowhere" — anticipate themes in later '
        'medieval and Renaissance cosmology. Blaise Pascal used a version of this proposition in '
        'his <i>Pensees</i>; Nicholas of Cusa\'s concept of the infinite and the coincidentia '
        'oppositorum may have been influenced by it. The text thus bridges mathematical theology, '
        'cosmological speculation, and the alchemical tradition of the philosopher as one who '
        'penetrates the hidden structure of nature. Historians have debated its precise place in '
        'the tradition: whether its definitions of God are genuinely alchemical or whether alchemy '
        'is a pretext for philosophical speculation. Wouter Hanegraaff\'s treatment in the '
        '<i>Dictionary of Gnosis and Western Esotericism</i> situates the text within the '
        'Hermetic-alchemical synthesis of the high medieval period, while Lawrence Principe\'s '
        'more operationally focused reading of alchemy asks what practitioners actually derived '
        'from such philosophical frameworks for their laboratory work.</p>'
    ),
    'de-sex-rerum-principiis': (
        '<p>The <i>De Sex Rerum Principiis</i> participates in the broader twelfth-century '
        'project of understanding natural generation and transformation through principles derived '
        'from classical sources. Its six principles — typically identified as form, matter, motion, '
        'rest, space, and time — represent one of the organizational schemes through which twelfth- '
        'century natural philosophers attempted to give systematic theoretical structure to '
        'observations about natural change. For the history of alchemy, the significance of such '
        'texts lies in the philosophical infrastructure they provided: alchemical practice required '
        'theoretical legitimation within the dominant scholastic frameworks, and the question of '
        'whether art could replicate natural processes was not merely empirical but philosophical, '
        'depending on accounts of substantial form, material change, and the relationship between '
        'nature and human artifice. The <i>De Sex Rerum Principiis</i> represents the philosophical '
        'culture within which the first Latin alchemical texts were received and debated, and '
        'understanding it helps situate the specifically alchemical debates of the thirteenth '
        'century in their broader intellectual context.</p>'
    ),
    'picatrix': (
        '<p>The <i>Picatrix</i>\'s role in the history of alchemy is indirect but real. Its doctrine '
        'of astral magic — that celestial bodies exert specific influences on terrestrial matter, '
        'that these influences can be captured through specific images, materials, times, and '
        'procedures — provided one theoretical framework within which alchemical practice could be '
        'situated. The idea that gold was the metal governed by the Sun and that gold-making required '
        'harnessing solar influences connected astral magic to metallic alchemy in ways that '
        'practitioners found productive. Brian Copenhaver\'s work on the Hermetic and magical '
        'traditions provides context for the <i>Picatrix</i>\'s philosophical framework, while '
        'Charles Burnett\'s research on the text\'s translation history documents how Arabic astral '
        'science entered Latin Europe through the twelfth-century translation movement. Lawrence '
        'Principe\'s distinction between the symbolic and rhetorical framework of magical philosophy '
        'and the operational content of laboratory alchemy helps clarify the <i>Picatrix</i>\'s '
        'role: it contributed to the theoretical legitimation of alchemical practice rather than '
        'to its experimental content, providing practitioners with a cosmological framework within '
        'which their laboratory work had philosophical significance.</p>'
    ),
    'chymisches-cabinett': (
        '<p>The <i>Chymisches Cabinett</i>\'s 1708 publication date situates it at the transitional '
        'moment when the Helmontian chymical tradition was giving way to the phlogiston chemistry '
        'of Georg Ernst Stahl and the systematic academic chemistry of Boerhaave. The persistence '
        'of emblematic alchemical publication into the early eighteenth century demonstrates that '
        'the "end of alchemy" was not a sudden event but a gradual transformation in which the '
        'older emblematic and practical traditions continued to find audiences even as the new '
        'systematic chemistry was establishing itself in universities. Newman and Principe\'s '
        'historiography of this transition — in which the Helmontian chymical tradition was '
        'displaced by phlogiston theory and then further displaced by Lavoisier\'s Chemical '
        'Revolution — helps explain why texts like the <i>Chymisches Cabinett</i> continued to '
        'be published: there was still a market for practical and emblematic alchemical literature '
        'among practitioners who had not yet fully adopted the new academic chemistry, and the '
        'tradition of alchemical publication had sufficient commercial momentum to continue beyond '
        'its theoretical displacement. The text also belongs to the German-language alchemical '
        'tradition of the seventeenth and early eighteenth centuries, which was particularly '
        'rich in emblematic and practical publications associated with Rosicrucian networks and '
        'Lutheran pietist circles.</p>'
    ),
}

def load_all():
    conn = sqlite3.connect(DB)
    print('=== Full bios ===')
    setp(conn, 'marsilio-ficino', ficino_bio())
    setp(conn, 'george-ripley', ripley_bio())
    setp(conn, 'nicholas-flamel', nicholas_flamel_bio())
    setp(conn, 'hildegard-of-bingen', hildegard_bio())

    print('\n=== Bio expansions ===')
    app(conn, 'persons', 'bio_html', 'albertus-magnus', ALBERTUS_EXTRA)
    app(conn, 'persons', 'bio_html', 'avicenna', AVICENNA_EXTRA)
    app(conn, 'persons', 'bio_html', 'william-newman', NEWMAN_EXTRA)
    app(conn, 'persons', 'bio_html', 'lawrence-principe', PRINCIPE_EXTRA)

    print('\n=== Text expansions ===')
    for slug, extra in TEXT_EXTRAS.items():
        app(conn, 'texts', 'analysis_html', slug, extra)

    conn.commit()
    conn.close()
    print('\n=== Done ===')

if __name__ == '__main__':
    load_all()
