#!/usr/bin/env python3
"""expand_batch6b_more.py — Continue expanding batch 6 persons to 1200 words."""
import sqlite3, re
DB = 'db/alchemy_timeline.db'

def wc(h): return len(re.sub('<[^>]+>', ' ', h or '').split())

def app(conn, slug, extra):
    c = conn.cursor()
    c.execute('SELECT bio_html FROM persons WHERE slug=?', (slug,))
    row = c.fetchone()
    if not row: print(f'  [MISS] {slug}'); return
    cur = row[0] or ''
    new = cur + extra
    c.execute('UPDATE persons SET bio_html=? WHERE slug=?', (new, slug))
    print(f'  {slug}: {wc(cur)} -> {wc(new)}')

FLUDD_2 = (
    '<p>The controversy between Fludd and Marin Mersenne deserves particular attention for what'
    ' it reveals about the competing visions of natural philosophy in the early seventeenth century.'
    ' Mersenne attacked Fludd\'s Neoplatonic-Hermetic natural philosophy in his <i>Quaestiones'
    ' Celeberrimae in Genesim</i> (1623) and several subsequent works, arguing that Fludd\'s'
    ' account of nature as animated by divine light and number was both theologically dangerous'
    ' (tending toward pantheism) and epistemologically inadequate (incapable of producing certain'
    ' knowledge). Fludd\'s responses were eloquent but unable to answer Mersenne\'s fundamental'
    ' point: that a qualitative, holistic natural philosophy organized around analogies, sympathies,'
    ' and divine correspondences did not offer the kind of precise, mechanically explicable,'
    ' and mathematically tractable knowledge that the mechanical philosophy was beginning to deliver.'
    ' The Mersenne-Fludd exchange is one of the clearest markers of the point at which the'
    ' Hermetic-qualitative tradition lost the initiative in European natural philosophy.</p>'
    '<p>Fludd\'s alchemical work was embedded in his medical practice: he used chemical medicines,'
    ' prepared following Paracelsian methods, and understood the human body as a microcosm whose'
    ' functioning could be supported and corrected by substances that corresponded to its'
    ' different principles — a view consistent with Paracelsian iatrochemistry and with the'
    ' broader doctrine of sympathies that organized his natural philosophy. His advocacy for'
    ' the weapon-salve was in this sense not an aberration but a logical extension of his'
    ' theoretical framework, in which action-at-a-distance through sympathetic correspondences'
    ' was a legitimate natural mechanism. That this mechanism was challenged and eventually'
    ' rejected by the mechanical philosophy does not change the fact that it was a serious'
    ' theoretical position with its own internal coherence.</p>'
)

THEOSEBEIA_2 = (
    '<p>The specific chemical content of the treatises Zosimos addresses to Theosebeia'
    ' — accounts of the preparation of divine water (a corrosive substance, possibly nitric'
    ' acid or aqua regia), the treatment of copper to produce yellow and white metals, and'
    ' the extraction of tinctures from minerals — places her engagement with alchemy firmly'
    ' in the domain of practical laboratory work rather than purely contemplative or religious'
    ' inquiry. Zosimos writes to her about the practical as well as the philosophical aspects'
    ' of the work, suggesting that she had laboratory experience rather than only theoretical'
    ' knowledge. This combination of practical engagement with philosophical sophistication'
    ' makes her significant as early evidence for the broad social range of participation in'
    ' Greek laboratory alchemy.</p>'
    '<p>The problem of evidence for Theosebeia illustrates the broader challenge of recovering'
    ' women\'s participation in early natural inquiry. The texts survive only in their'
    ' attribution to Zosimos; Theosebeia\'s own writings, if any existed, have not survived.'
    ' Her presence in the tradition is visible only through being addressed: she is known'
    ' because Zosimos wrote to her, not because her own work is preserved. This is a common'
    ' pattern in the history of women in early science, and it means that the record'
    ' systematically undercounts women\'s participation while making visible the participation'
    ' of those who happened to be interlocutors of male authors whose work was transmitted.'
    ' The pattern has been analyzed in the broader context of women and alchemy by Barbara'
    ' Obrist and others who have examined the evidence for women practitioners in the Greek,'
    ' Arabic, and medieval Latin traditions.</p>'
)

AGRICOLA_2 = (
    '<h2>Earlier Works and Theoretical Framework</h2>'
    '<p>Agricola\'s earlier <i>Bermannus, sive de re metallica</i> (1530), written as a Socratic'
    ' dialogue set in the mining district of Joachimsthal, was the first humanist natural'
    ' philosophical engagement with mining and metallurgy. The dialogue form allowed Agricola'
    ' to address both theoretical questions (what are ores? how do metals form in the earth?'
    ' what is the relationship between alchemical theory and mining practice?) and practical'
    ' ones, within the literary conventions of humanist dialogue. The theoretical account of'
    ' metallic generation draws on the sulphur-mercury theory derived from [LINK:avicenna]\'s'
    ' <i>De Mineralibus</i> and from the Latin alchemical tradition: metals form in the earth'
    ' through the combination of sulfurous and mercurial vapors under the influence of heat.'
    ' This theoretical framework is consistent with alchemy\'s account of why transmutation'
    ' might be possible (art can replicate what nature does) without endorsing the specific'
    ' claims of transmutational practitioners.</p>'
    '<p><i>De Natura Fossilium</i> (1546) classified minerals systematically — the first'
    ' systematic mineralogical classification in Latin natural philosophy — using a taxonomy'
    ' based on physical properties (color, transparency, texture, taste) rather than on'
    ' their theoretical generation. This empirical approach to mineral classification was'
    ' adopted and developed by subsequent mineralogists and contributed to the tradition'
    ' of systematic natural history that would eventually feed into the development of'
    ' chemistry as a discipline concerned with the properties and classification of'
    ' material substances.</p>'
    '<p>The <i>De Re Metallica</i>\'s remarkable illustrations — produced by the wood-engraver'
    ' Hans Rudolf Manuel Deutsch after Agricola\'s specifications — represent the most'
    ' detailed visual record of sixteenth-century mining and metallurgical technology'
    ' available. The images show specific equipment (pumps, bellows, furnaces, stamping'
    ' mills) with enough detail that historians of technology have been able to reconstruct'
    ' and analyze the machinery depicted. Herbert Clark Hoover (later US President) and'
    ' his wife Lou Henry Hoover translated <i>De Re Metallica</i> into English in 1912,'
    ' a project that required them to identify the obsolete technical vocabulary through'
    ' reference to actual mining equipment of the period — a remarkable exercise in practical'
    ' scholarship that produced a translation still used by historians today.</p>'
)

ASHMOLE_2 = (
    '<h2>Astrology, Freemasonry, and Royalist Networks</h2>'
    '<p>Ashmole\'s <i>Theatrum Chemicum Britannicum</i> appeared during the Interregnum with'
    ' an explicitly nationalist and historical project: to demonstrate that England possessed'
    ' a distinguished tradition of alchemical learning going back to the medieval period,'
    ' connected to the tradition of English learning and royal patronage that the Commonwealth'
    ' had disrupted. His annotations to the alchemical texts he collected — particularly his'
    ' notes on [LINK:george-ripley], John Dee, and other practitioners — constitute a'
    ' significant early effort at the history of English alchemy, drawing on manuscripts'
    ' in the collections he could access and on correspondence with other antiquaries.'
    ' The project was antiquarian as much as practical: Ashmole was interested in documenting'
    ' the tradition as much as in practicing it.</p>'
    '<p>Ashmole\'s astrological practice was central to his intellectual life and his social'
    ' network. He cast horoscopes for clients and maintained extensive astrological records.'
    ' His initiation into Freemasonry in 1646 — the earliest well-documented Masonic'
    ' initiation in England — connected him to networks of craftsmen and gentlemen who'
    ' shared interests in operative and speculative arts. His position as Windsor Herald'
    ' from 1660, secured through his Royalist connections and his assistance to Charles II'
    ' on his return, gave him institutional standing and access to the royal collections'
    ' that supported his antiquarian work. The founding of the Ashmolean Museum in 1683'
    ' represented the culmination of his collecting career: the first public repository'
    ' in Britain for natural specimens, coins, antiquities, and manuscripts, housed at'
    ' Oxford and accompanied by a school of natural history.</p>'
    '<p>The relationship between Ashmole\'s alchemy, his astrology, his Freemasonry, and'
    ' his antiquarianism illustrates the cultural landscape of mid-seventeenth-century England'
    ' in which these pursuits were not yet clearly separated. He was simultaneously a'
    ' serious collector of alchemical manuscripts, a practicing astrologer with a clientele,'
    ' an early Mason, a Royalist politician, and the founder of Britain\'s first public museum —'
    ' a range of activities that made sense within the undivided world of learned culture'
    ' before the Enlightenment classifications that would eventually sort these pursuits'
    ' into legitimate scholarship, legitimate science, and disreputable occultism.</p>'
)

KHUNRATH_2 = (
    '<h2>Laboratory Practice and Spiritual Aspiration</h2>'
    '<p>Khunrath\'s practical engagement with laboratory alchemy is attested both by the'
    ' chemical content of the <i>Amphitheatrum</i> and by his manuscript writings and'
    ' correspondence. He was not merely a philosophical alchemist but a practitioner who'
    ' worked with actual materials, even if the surviving record does not allow us to'
    ' reconstruct his specific procedures in the detail available for [LINK:george-starkey]'
    ' or [LINK:robert-boyle]. His emphasis on the unity of oratory (prayer) and laboratory'
    ' (work) was not rhetorical decoration but a statement about what the alchemical work'
    ' actually required: the practitioner who approached the work without spiritual preparation'
    ' and continued prayerful orientation would fail not for spiritual reasons alone but because'
    ' the right disposition was a necessary condition for the careful, patient, and attentive'
    ' observation that successful alchemical work required.</p>'
    '<p>The specific combination of Lutheran piety, Paracelsian natural philosophy, and'
    ' Neoplatonic-Hermetic cosmology in the <i>Amphitheatrum</i> reflects the distinctive'
    ' religious and intellectual culture of late sixteenth-century German Protestantism.'
    ' Lutheran theologians had generally been more tolerant of natural magic and alchemy'
    ' than their Catholic counterparts — Luther himself had expressed interest in Paracelsian'
    ' ideas, and the association of alchemy with divinely established natural processes'
    ' was consistent with Lutheran theology of creation. Khunrath\'s work represents the'
    ' apex of this Lutheran alchemical tradition before the Thirty Years\' War disrupted'
    ' the intellectual and institutional landscape of German Protestant learning.</p>'
    '<p>The fate of the <i>Amphitheatrum</i> after publication reflects the tensions between'
    ' alchemical culture and Catholic ecclesiastical authority. An edition published in'
    ' Magdeburg in 1608 was condemned by the Faculty of Theology at Paris in 1625 as'
    ' containing magical and heretical content. This condemnation did not suppress the text'
    ' — it continued to circulate and influence alchemical writers — but it marks the point'
    ' at which the synthesis of practical alchemy with ceremonial magic and Neoplatonic'
    ' cosmology became officially problematic in Catholic Europe, a distinction that'
    ' contributed to the separation between northern (Protestant) and southern (Catholic)'
    ' alchemical cultures in the seventeenth century.</p>'
)

VALENTINUS_2 = (
    '<h2>Antimony and Chemical Medicine</h2>'
    '<p>The controversy over antimony in seventeenth-century medicine was one of the most'
    ' bitter pharmaceutical disputes of the early modern period. Antimony compounds —'
    ' particularly antimony potassium tartrate (tartar emetic) and antimony oxide — were'
    ' powerful emetics that could cause severe illness or death in large doses and were'
    ' therapeutically useful in smaller ones for treating fevers and other conditions.'
    ' The Paris Faculty of Medicine banned their use in 1566 (though the ban was intermittently'
    ' enforced); Paracelsian and chymical practitioners defended them against Galenic'
    ' opposition; and the controversy reached its climax when the court physician Guy-Crescent'
    ' Fagon successfully treated Louis XIV with antimony in 1658, after which the ban was'
    ' effectively lifted. The Valentine texts were central to the antimony controversy as'
    ' authoritative sources on antimony preparations and their medical uses.</p>'
    '<p>The chemical content of <i>Triumphwagen Antimonii</i> includes detailed descriptions'
    ' of how to prepare antimony glass (by fusing stibnite), antimony oxide (by roasting),'
    ' antimony butter (antimony trichloride, by treating stibnite with aqua regia), and'
    ' various medicinal preparations including the cup of antimony (a cup of antimony oxide'
    ' into which wine was poured, producing soluble antimony compounds through reaction'
    ' with the organic acids in the wine). [LINK:lawrence-principe]\'s laboratory work has'
    ' confirmed that these preparations are chemically coherent and produce the effects'
    ' described. The text is thus a genuine repository of practical chemical knowledge'
    ' about antimony, whatever its historical provenance, and its influence on seventeenth-century'
    ' pharmaceutical chemistry was significant and lasting.</p>'
)

PEREIRA_2 = (
    '<h2>Methodology and Contribution to Alchemy Studies</h2>'
    '<p>Pereira\'s methodological approach combines manuscript philology — critical examination'
    ' of the textual tradition to establish what texts actually say and how they were transmitted'
    ' — with intellectual history of the theoretical concepts they contain. Her work on the'
    ' pseudo-Lullian corpus required tracing hundreds of manuscripts across European libraries'
    ' to establish the textual relationships between different versions of texts that circulated'
    ' under Lull\'s name. This is labor-intensive scholarship of the traditional kind, made more'
    ' productive by her combination of philological skill with theoretical sophistication about'
    ' the chemistry and natural philosophy the texts discuss.</p>'
    '<p>Her contribution to the broader historiography of medieval alchemy has been to demonstrate'
    ' that the late medieval period — the fourteenth and fifteenth centuries, between the arrival'
    ' of the Arabic-Latin translation movement and the Paracelsian revolution — was a period of'
    ' genuine intellectual activity in alchemy rather than mere transmission and compilation.'
    ' The pseudo-Lullian tradition developed new theoretical positions on the philosophical'
    ' mercury, new accounts of the stages of the alchemical work, and new forms of textual'
    ' legitimation. [LINK:john-of-rupescissa]\'s quintessence concept was appropriated and'
    ' transformed. The debate over whether alchemy was scientifically legitimate — the'
    ' <i>Sciant artifices</i> controversy — was actively engaged. Pereira\'s scholarship'
    ' makes it possible to see this period as a creative phase of development rather than'
    ' a gap between more visible earlier and later periods.</p>'
    '<p>Her collaborative work with other medievalists and historians of science has produced'
    ' important reference tools for the field, including her contribution to the <i>Corpus'
    ' Philosophorum Medii Aevi</i> project and her work with the Scientiae project on'
    ' knowledge systems in the pre-modern period. Her influence on graduate students and'
    ' younger scholars working on medieval and Renaissance alchemy reflects the importance'
    ' of the institutional and pedagogical dimensions of scholarly program-building that'
    ' are as significant as publication for the long-term development of the field.</p>'
)

RAZI_2 = (
    '<h2>Theoretical Framework and Classification System</h2>'
    '<p>Al-Razi\'s classification of substances was organized around their observable physical'
    ' and chemical properties rather than their theoretical generation — a pragmatic approach'
    ' that made the classification directly useful for laboratory practitioners. His six-class'
    ' mineral taxonomy (spirits, bodies, stones, vitriols, boraces, salts) identified the most'
    ' chemically significant categories of inorganic substances known in the ninth century and'
    ' provided a framework that remained influential through the medieval period. The "spirits"'
    ' category — volatile substances that could be driven off by heat — is particularly'
    ' significant: it grouped mercury, sulfur, arsenic oxide, and sal ammoniac (ammonium'
    ' chloride) on the basis of their shared volatility, a grouping that had practical'
    ' consequences for how practitioners thought about and worked with these substances.</p>'
    '<p>Al-Razi\'s alchemical theoretical framework differed from the later Islamic tradition'
    ' in his relative skepticism about transmutation. His <i>Kitab al-Shawahid</i> (Book of'
    ' Proofs) discusses the possibility and impossibility of transmutation in terms that'
    ' are more empirically cautious than the Jabirian corpus. This cautious empiricism'
    ' is consistent with his approach to medicine, where he emphasized clinical observation'
    ' and the testing of treatments through systematic comparison rather than reliance on'
    ' theoretical authority. His medical writings record extensive clinical observations'
    ' — he is credited with the first accurate clinical description of smallpox and measles'
    ' (in <i>Kitab fi al-Jadari wa al-Hasba</i>) — and this clinical orientation apparently'
    ' carried over into his chemical work.</p>'
    '<p>His influence in the Latin West was primarily through his medical works rather than'
    ' his explicitly alchemical texts. The twelfth-century translation of <i>Liber Almansoris</i>'
    ' (the <i>Kitab al-Mansuri</i>) and the thirteenth-century translation of portions of'
    ' <i>Al-Hawi</i> (the <i>Continens</i>) made his clinical methodology and pharmaceutical'
    ' knowledge available to European medical education. The chemical knowledge embedded in'
    ' these medical texts — particularly his accounts of the preparation and properties of'
    ' mineral drugs — entered the Latin medical-chemical tradition and contributed to the'
    ' development of the pharmaceutical chemistry that would eventually become chemistry'
    ' proper. His standing as a major medical authority meant that his chemical contributions'
    ' arrived in Europe with the authority of one of the most respected physicians in the'
    ' Islamic tradition, giving them a reception that they might not have received as purely'
    ' alchemical texts would have done.</p>'
)

CHAUCER_2 = (
    '<h2>Literary Context and Alchemical Culture</h2>'
    '<p>The Canon\'s Yeoman\'s Tale presents alchemy within the social and economic world of'
    ' late medieval London: the fraudulent canon targets a London chantry priest with disposable'
    ' income and insufficient critical judgment, exploiting the combination of alchemical'
    ' excitement and commercial opportunity that characterized the urban environment in which'
    ' Chaucer himself worked. The tale is set in London, and the details of the setting —'
    ' the meeting in Cheapside, the priest\'s eagerness to invest, the systematic extraction'
    ' of his funds — reflect the specific dynamics of alchemical fraud in the city that'
    ' Chaucer would have observed at first hand.</p>'
    '<p>The prologue to the Canon\'s Yeoman\'s Tale, in which the Yeoman describes his years'
    ' of unsuccessful pursuit of the Stone and the poverty that resulted, is one of the most'
    ' vivid first-person accounts of the experience of failed alchemical practice in medieval'
    ' literature. The Yeoman\'s description of the laboratory failures — the explosions,'
    ' the spilled preparations, the wasted materials — and of the psychological mechanism'
    ' of continued pursuit despite repeated failure ("when we be strongest, yet we fail most")'
    ' captures something that would have resonated with practitioners who had experienced'
    ' the same cycle. This psychological observation — that proximity to apparent success'
    ' paradoxically intensifies commitment to a failing program — connects Chaucer\'s literary'
    ' analysis to questions about the sociology of failed inquiry that have been addressed'
    ' by historians of science examining why intelligent people pursue impossible goals.</p>'
    '<p>Chaucer\'s other works touch on alchemical and natural philosophical themes: his'
    ' translation of Boethius, his astronomical works including <i>Treatise on the Astrolabe</i>'
    ' (1391), and various references to natural philosophy in the <i>Canterbury Tales</i>'
    ' demonstrate a sustained engagement with learned culture that provided the context'
    ' for his alchemical knowledge. The Canon\'s Yeoman\'s Tale is thus not an isolated'
    ' experiment in technical subject matter but an expression of a broader intellectual'
    ' engagement with natural philosophy and its social uses that runs through Chaucer\'s work.</p>'
)

BRAHE_2 = (
    '<h2>Chemical Medicine and the Integration of Astronomy and Alchemy</h2>'
    '<p>Tycho\'s medical alchemy was organized around the production of specific chemical remedies'
    ' rather than the pursuit of transmutational gold. His <i>panacea</i> — a preparation'
    ' that he distributed to local peasants as a universal medicine — was a standard'
    ' feature of Renaissance physician-alchemists who combined the legitimacy of medical'
    ' practice with the prestige of alchemical knowledge. The social role of the'
    ' physician-alchemist, combining healing practice with access to the most advanced'
    ' natural philosophical knowledge, was a model that appears across late sixteenth-century'
    ' learned culture in the figures of [LINK:heinrich-khunrath], [LINK:robert-fludd],'
    ' Oswald Croll, and others who combined Paracelsian medicine with Hermetic natural'
    ' philosophy.</p>'
    '<p>The integration of Tycho\'s astronomical and alchemical work within a single'
    ' theoretical framework is visible in his commitment to the Paracelsian correspondence'
    ' between macrocosm and microcosm. Astronomical events — eclipses, planetary conjunctions,'
    ' comets — influenced terrestrial matter according to this framework, and alchemical'
    ' practice could work with these influences rather than against them. Tycho\'s careful'
    ' observation of the comet of 1577, which he showed was supralunar rather than an'
    ' atmospheric phenomenon (disproving Aristotle\'s account of comets as atmospheric'
    ' exhalations), was not separate from his alchemical interests but part of the same'
    ' program of empirical investigation of the cosmos that included the laboratory.</p>'
    '<p>The loss of Tycho\'s laboratory records — most of his personal papers did not survive'
    ' the Thirty Years\' War and the subsequent dispersal of his Bohemian materials —'
    ' means that the alchemical dimension of his work can only be partially reconstructed'
    ' from secondary sources and the few surviving documents. This archival situation is'
    ' characteristic of the broader problem of reconstructing early modern alchemical'
    ' practice: the laboratory records that would allow detailed reconstruction of what'
    ' practitioners actually did have disproportionately not survived, leaving the printed'
    ' texts as the primary evidence and creating a systematic bias toward theoretical'
    ' over practical knowledge in the historical record.</p>'
)

TRITHEMIUS_2 = (
    '<h2>Library, Network, and Transmission</h2>'
    '<p>Trithemius\'s library at Sponheim grew from virtually nothing at his arrival in 1483'
    ' to approximately 2000 volumes by the time he left in 1506 — an extraordinary achievement'
    ' for a provincial German monastery and evidence for his systematic efforts to collect'
    ' and preserve manuscripts and printed books across a wide range of subjects. The library'
    ' included classical texts, patristic writings, humanist literature, mathematical and'
    ' natural philosophical texts, and works on magic, cryptography, and learned occultism.'
    ' Trithemius\'s collecting activity made Sponheim a center for the transmission of'
    ' learned culture in the Rhineland and attracted scholars and students from a wide area.</p>'
    '<p>His chronicle works — <i>Annales Hirsaugienses</i> and others — established him as'
    ' a significant figure in German humanist historical writing, contributing to the project'
    ' of constructing a continuous German intellectual and ecclesiastical tradition. This'
    ' historical work intersected with his interests in learned magic: his accounts of'
    ' earlier magicians and occult practitioners were part of a broader effort to locate'
    ' occult learning within a venerable tradition reaching back to ancient sources.'
    ' The construction of such traditions was a standard strategy for legitimating'
    ' contemporary practice and is closely related to the pseudepigraphal strategies'
    ' used in alchemical texts to claim ancient authority.</p>'
    '<p>Trithemius\'s influence on [LINK:henry-cornelius-agrippa] was decisive: his advice'
    ' to Agrippa to keep <i>De Occulta Philosophia</i> from the masses and to share it only'
    ' with the learned — which Agrippa initially followed before eventually publishing the work'
    ' in 1531 — reflects a shared understanding of occult knowledge as requiring careful'
    ' management of audience and transmission. This culture of selective disclosure,'
    ' characteristic of the learned magic tradition, connects to the patterns of secrecy'
    ' and selective publication in alchemical culture that [LINK:william-newman] and'
    ' [LINK:lawrence-principe] have analyzed in the seventeenth-century chymical tradition.</p>'
)

CUSA_2 = (
    '<h2>Mathematics, Infinity, and Natural Inquiry</h2>'
    '<p>Cusanus\'s treatment of infinity in mathematics and natural philosophy was distinctive'
    ' in its positive embrace of the infinite as a productive concept rather than a limit'
    ' on human understanding. His argument that the circle, as the polygon with infinite'
    ' sides, was the limit that finite polygons approached but never reached provided a'
    ' mathematical model for the relationship between finite human knowledge and the'
    ' infinite divine reality it sought to approximate. This mathematical conception of'
    ' the infinite as a positive ideal rather than a mere absence of limit influenced'
    ' subsequent Renaissance mathematics and natural philosophy, including the work of'
    ' Giordano Bruno (who cited Cusanus in developing his account of the infinite universe)'
    ' and, more distantly, the mathematical treatments of infinity by Leibniz and others.</p>'
    '<p>The relationship between Cusanus and the alchemical tradition is primarily one of'
    ' shared intellectual context rather than direct influence. Both drew on the Neoplatonic'
    ' tradition of emanation and return; both understood the natural world as a manifestation'
    ' of divine creativity that could be investigated through the intersection of human art'
    ' and natural process; and both grappled with the relationship between theoretical'
    ' knowledge and practical investigation. His philosophical framework — in which the'
    ' pursuit of knowledge is an infinite approximation to an inexhaustible divine reality'
    ' — is compatible with the alchemical practitioner\'s experience of indefinite'
    ' refinement of procedures in pursuit of a goal that remained perpetually just out of reach.</p>'
    '<p>More directly, Cusanus\'s concept of <i>posse-est</i> (can-is, the unity of possibility'
    ' and actuality in God) and his account of how human craft participates in divine'
    ' creativity through the making of artifacts that bring latent possibilities to'
    ' actualization connect to the philosophical legitimation of alchemical practice that'
    ' [LINK:marsilio-ficino]\'s Neoplatonism provided. The line from Cusanus through Ficino'
    ' to the Hermetic-Neoplatonic framework that alchemical practitioners drew on for'
    ' philosophical legitimation is one of the important intellectual genealogies of'
    ' Renaissance thought that contextualizes the history of alchemy.</p>'
)

GROSSETESTE_2 = (
    '<h2>Experiment, Induction, and the Oxford Tradition</h2>'
    '<p>Grosseteste\'s account of scientific method in his commentaries on Aristotle\'s'
    ' <i>Posterior Analytics</i> distinguished between the process of discovering causes'
    ' through induction from observations (resolutio) and the process of demonstrating'
    ' effects from causes (compositio). This distinction, which parallels the later'
    ' distinction between analysis and synthesis in natural philosophical methodology,'
    ' provided a framework for thinking about the relationship between laboratory'
    ' observation and theoretical explanation that subsequent Oxford natural philosophers'
    ' applied in different ways. [LINK:roger-bacon]\'s emphasis on <i>experimentum</i>'
    ' as a criterion in natural philosophy drew on Grosseteste\'s framework; the'
    ' Oxford Calculators\' mathematical treatment of change drew on a different aspect'
    ' of the same tradition.</p>'
    '<p>His optics work — <i>De Luce</i> (On Light), <i>De Lineis, Angulis et Figuris</i>'
    ' (On Lines, Angles, and Figures), and his commentary on Aristotle\'s <i>Meteorologica</i>'
    ' with its treatment of the rainbow — established the study of light and vision as'
    ' a central topic of Oxford natural philosophy. The alchemical tradition\'s treatment'
    ' of color change as evidence of chemical transformation — the black, white, yellow,'
    ' and red stages of the work — was not directly connected to Grosseteste\'s optics,'
    ' but the broader interest in light as a natural philosophical topic that his work'
    ' established created a context in which color phenomena were taken seriously as'
    ' objects of inquiry.</p>'
    '<p>The institutional legacy of Grosseteste\'s Oxford program was the tradition of'
    ' natural philosophical inquiry centered at Merton College, which produced the'
    ' Merton Calculators (Bradwardine, Heytesbury, Swineshead, Dumbleton) in the'
    ' fourteenth century and eventually the tradition that influenced Galileo\'s kinematics.'
    ' The connection between the Oxford tradition Grosseteste founded and the later'
    ' development of experimental science in England — through [LINK:roger-bacon],'
    ' through the Mertonians, through the sixteenth-century reformers — is one of the'
    ' institutional genealogies that contextualizes the development of English chymistry'
    ' in the seventeenth century.</p>'
)

CHESTER_2 = (
    '<h2>Translation Movement and Chemical Knowledge Transmission</h2>'
    '<p>Robert\'s translation of the <i>Liber de Compositione Alchemiae</i> was part of a'
    ' remarkable intellectual transformation: within about a century (roughly 1050–1150),'
    ' European scholars gained access to the entire corpus of Greek and Arabic natural'
    ' philosophy through Latin translations made primarily in Spain and Sicily, where'
    ' Christian, Muslim, and Jewish scholars worked in proximity. The scale of this'
    ' transfer — Aristotle\'s complete natural philosophical corpus, Avicenna\'s medical'
    ' and philosophical works, Ptolemy\'s astronomy, Euclid\'s mathematics, al-Khwarizmi\'s'
    ' algebra, and hundreds of other texts — transformed European intellectual life in'
    ' ways that are difficult to overstate. Alchemy was a small part of this transfer,'
    ' but it arrived with the same wave of texts and within the same institutional context.</p>'
    '<p>The Latin translators understood themselves as engaged in a civilizational project:'
    ' recovering the wisdom of the ancients that had been preserved in Arabic and making'
    ' it available to Latin readers. This self-understanding shaped how translated texts'
    ' were read and how their authority was understood. An Arabic alchemical text, translated'
    ' into Latin and attributed to Khalid ibn Yazid communicating with the philosopher'
    ' Morienus, arrived with the authority of both Arabic learning and ancient precedent.'
    ' This double authority — Arabic transmission plus ancient origin — was characteristic'
    ' of how translated scientific texts were positioned for Latin audiences, and it'
    ' explains why the pseudepigraphal strategies characteristic of Arabic alchemical texts'
    ' transferred successfully into the Latin tradition: they were adapted to work within'
    ' the authority structures that Latin readers brought to the texts.</p>'
    '<p>The specific location of Robert\'s translation activity — twelfth-century Spain,'
    ' particularly in the orbit of the Toledo school of translators — placed him in the'
    ' same intellectual environment as [LINK:gerard-of-cremona], Herman the Dalmatian,'
    ' and other figures who were simultaneously producing translations of Aristotle,'
    ' Ptolemy, Avicenna, and al-Khwarizmi. This context underlines the point that the'
    ' arrival of alchemy in medieval Europe was not a separate event from the broader'
    ' Aristotelian-Arabic translation movement but part of it — alchemy arrived alongside'
    ' the natural philosophy that would provide its theoretical framework and the mathematics'
    ' and astronomy that would provide its cosmological context.</p>'
)

def load_all():
    conn = sqlite3.connect(DB)

    for slug, extra in [
        ('robert-fludd', FLUDD_2),
        ('theosebeia', THEOSEBEIA_2),
        ('george-agricola', AGRICOLA_2),
        ('elias-ashmole', ASHMOLE_2),
        ('heinrich-khunrath', KHUNRATH_2),
        ('basilius-valentinus', VALENTINUS_2),
        ('michela-pereira', PEREIRA_2),
        ('muhammad-al-razi', RAZI_2),
        ('geoffrey-chaucer', CHAUCER_2),
        ('tycho-brahe', BRAHE_2),
        ('johannes-trithemius', TRITHEMIUS_2),
        ('nicholas-of-cusa', CUSA_2),
        ('robert-grosseteste', GROSSETESTE_2),
        ('robert-of-chester', CHESTER_2),
    ]:
        app(conn, slug, extra)

    conn.commit()
    conn.close()
    print('=== Done ===')

if __name__ == '__main__':
    load_all()
