#!/usr/bin/env python3
"""
study_data_gaps.py — a full audit of where the corpus is missing thematic, relational,
and itinerary data. Writes docs/DATA_GAP_STUDY.md (human report) and
staging/enrichment_worklist.json (machine worklist, prioritised by leverage).

Leverage = a figure with many linked events but no itinerary/relations is high-value:
the map can't move them, the network can't connect them.
"""
import sqlite3, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "db" / "alchemy_timeline.db"


def table_exists(c, name):
    return c.execute("select 1 from sqlite_master where type='table' and name=?", (name,)).fetchone() is not None


def main():
    c = sqlite3.connect(DB); c.row_factory = sqlite3.Row
    has_itin = table_exists(c, "person_itinerary")
    has_rel = table_exists(c, "person_relationships")

    persons = c.execute("select slug,name,role_primary,era,review_status,length(coalesce(bio_html,'')) blen from persons").fetchall()
    ev = {r["person_slug"]: r["n"] for r in c.execute("select person_slug,count(*) n from person_event_refs group by person_slug")}
    cp = {r["person_slug"]: r["n"] for r in c.execute("select person_slug,count(*) n from concept_person_refs group by person_slug")}
    itin = {r["person_slug"]: r["n"] for r in c.execute("select person_slug,count(*) n from person_itinerary group by person_slug")} if has_itin else {}
    rel = {}
    if has_rel:
        for r in c.execute("select source_slug,count(*) n from person_relationships group by source_slug"):
            rel[r["source_slug"]] = rel.get(r["source_slug"], 0) + r["n"]
        for r in c.execute("select target_slug,count(*) n from person_relationships group by target_slug"):
            rel[r["target_slug"]] = rel.get(r["target_slug"], 0) + r["n"]

    rows = []
    for p in persons:
        s = p["slug"]
        rows.append({"slug": s, "name": p["name"], "role": p["role_primary"], "era": p["era"],
                     "review_status": p["review_status"], "bio_chars": p["blen"],
                     "events": ev.get(s, 0), "concept_links": cp.get(s, 0),
                     "itinerary": itin.get(s, 0), "relationships": rel.get(s, 0)})

    # leverage score: events without itinerary/relations are most valuable to enrich
    for r in rows:
        r["leverage"] = r["events"] * (2 if r["itinerary"] == 0 else 0) + r["events"] * (1 if r["relationships"] == 0 else 0) + (1 if r["concept_links"] == 0 else 0)
    rows.sort(key=lambda r: (-r["leverage"], -r["events"]))

    # corpus-level counts
    counts = {t: c.execute(f"select count(*) from {t}").fetchone()[0] for t in
              ["persons", "texts", "concepts", "locations", "timeline_events",
               "concept_person_refs", "concept_text_refs", "person_event_refs", "text_event_refs"]}
    counts["person_itinerary"] = c.execute("select count(*) from person_itinerary").fetchone()[0] if has_itin else 0
    counts["person_relationships"] = c.execute("select count(*) from person_relationships").fetchone()[0] if has_rel else 0
    n = len(rows)
    no_itin = sum(1 for r in rows if r["itinerary"] == 0)
    no_rel = sum(1 for r in rows if r["relationships"] == 0)
    no_cp = sum(1 for r in rows if r["concept_links"] == 0)
    draft = sum(1 for r in rows if r["review_status"] == "DRAFT")

    # ---- write worklist ----
    worklist = [r for r in rows if r["events"] >= 1][:40]
    (ROOT / "staging").mkdir(exist_ok=True)
    (ROOT / "staging" / "enrichment_worklist.json").write_text(
        json.dumps({"generated_for": "thematic/relational/itinerary enrichment",
                    "priority": worklist}, ensure_ascii=False, indent=2), encoding="utf-8")

    # ---- write report ----
    top = rows[:25]
    md = []
    md.append("# DATA GAP STUDY — thematic, relational & itinerary holes\n")
    md.append("Auto-generated by `scripts/study_data_gaps.py`. Drives the enrichment worklist.\n")
    md.append("## Corpus-level counts\n")
    md.append("| Table | Rows |\n|---|---:|")
    for k, v in counts.items():
        md.append(f"| {k} | {v} |")
    md.append("")
    md.append("## The three holes, quantified (of %d persons)\n" % n)
    md.append(f"- **Itinerary:** {no_itin}/{n} persons have NO travel data.")
    md.append(f"- **Relational:** {no_rel}/{n} persons have NO person-to-person ties.")
    md.append(f"- **Thematic:** {no_cp}/{n} persons have NO concept links "
              f"(concept_person_refs total = {counts['concept_person_refs']}, concept_text_refs = {counts['concept_text_refs']}).")
    md.append(f"- **Review:** {draft}/{n} persons are still DRAFT.\n")
    md.append("## Top 25 by enrichment leverage (most events, least structured data)\n")
    md.append("| # | Person | Era | Events | Concepts | Itinerary | Relations | Bio chars |")
    md.append("|--:|--------|-----|------:|------:|------:|------:|------:|")
    for i, r in enumerate(top, 1):
        md.append(f"| {i} | {r['name']} | {r['era']} | {r['events']} | {r['concept_links']} | {r['itinerary']} | {r['relationships']} | {r['bio_chars']} |")
    md.append("\n*Leverage = events x (no itinerary) x2 + events x (no relations) + (no concept links). "
              "These are the figures whose enrichment most improves the journey, network, and theme maps.*\n")

    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "DATA_GAP_STUDY.md").write_text("\n".join(md), encoding="utf-8")

    print(f"Wrote docs/DATA_GAP_STUDY.md and staging/enrichment_worklist.json")
    print(f"  persons={n}  no-itinerary={no_itin}  no-relations={no_rel}  no-concept-links={no_cp}  draft={draft}")
    print("  Top 8 by leverage:")
    for r in rows[:8]:
        print(f"    {r['name']:<26} events={r['events']:>3} concepts={r['concept_links']} itin={r['itinerary']} rel={r['relationships']}")
    c.close()


if __name__ == "__main__":
    main()
